"""One-time scope correction on the isolated revision branch. Never run by normal builds."""
from pathlib import Path
import re,json
root=Path.cwd()
p=root/'src/content.mjs';s=p.read_text()
remove_sources=['s-fica','s-flourish','s-duke','s-gwish','s-danielsen','s-rcpsych','s-harvard']
remove_records=['fica-directory','flourishing-directory','duke-resources','gwish-resources','danielsen-resources','rcpsych-resources','harvard-resources']
s='\n'.join(line for line in s.splitlines() if not any("source('"+i+"'" in line for i in remove_sources) and not any("R('"+i+"'" in line for i in remove_records) and not "section('network'" in line)+'\n'
p.write_text(s)
p=root/'src/regional.mjs';s=p.read_text()
s='\n'.join(line for line in s.splitlines() if "{id:'s-uii-pspi'" not in line)
s=re.sub(r",\n \{id:'indonesia-uii-psychology'[\s\S]+?\n\];",'\n];',s)
s=s.replace("sections:['library','network','approaches']","sections:['library','approaches']")
s=s.replace("'Malezya · UKM, İslami danışma literatürü','Malaysia · UKM, Islamic counselling literature','Malaysia · UKM, Literatur zur islamischen Beratung','马来西亚 · UKM，伊斯兰咨询文献','Малайзия · UKM, литература об исламском консультировании','ماليزيا · UKM، أدبيات الإرشاد الإسلامي','Malaysia · UKM, literatur konseling Islam','Malaysia · UKM, literatur kaunseling Islam'", "'İslami danışma ve kaygı üzerine literatür incelemesi','Islamic counselling and anxiety. A literature study','Islamische Beratung und Angst. Eine Literaturstudie','伊斯兰咨询与焦虑文献研究','Исламское консультирование и тревога. Анализ литературы','الإرشاد الإسلامي والقلق. دراسة أدبية','Konseling Islam dan kecemasan. Kajian literatur','Kaunseling Islam dan kebimbangan. Kajian literatur'")
p.write_text(s+'\n')
(root/'src/campus-data.mjs').write_text("/** Public content only. Design comparison is maintained separately under docs. */\nexport {areaRows as collections} from './centre-copy.mjs';\nexport const institutions = [];\nexport const events = [];\n")
p=root/'src/site.mjs';s=p.read_text()
s=re.sub(r'const navGroups=\{[^\n]+?\};',"const navGroups={center:['about','news','events'],research:['collections','projects','participate','methods'],learn:['learning','approaches','practice','ethics','media'],explore:['library','concepts','measures','compare']};",s)
s=s.replace('${e(t.notClinical)} ${e(t.noAffiliation)}','${e(t.notClinical)}')
s=re.sub(r'<section class="wide section network-preview">[\s\S]*?</section>','',s)
p.write_text(s)
p=root/'src/articles.mjs';s=p.read_text().replace("['s-fica','s-flourish','s-toad','s-swift']","['s-toad','s-swift']")
pattern=r"block\(L\('Çeviri, uyarlama ve izin'[\s\S]+?\)\),"
replacement="""block(L('Çeviri, uyarlama ve izin','Translation, adaptation and permission','Übersetzung, Anpassung und Erlaubnis','翻译、适配与许可','Перевод, адаптация и разрешение'),L('Bir ölçme aracını değerlendirirken dil, kullanım izni ve hedef gruba ilişkin araştırmalar ayrı başlıklarda kaydedilmelidir. Bu katalog için önerilen kayıt düzeni, özgün yayının yanında uyarlama çalışmasının ve kullanım koşullarının da incelenmesidir. Bir formun internette bulunması, yeniden yayımlanabileceği veya başka bir grupta geçerli olduğu varsayımına dönüştürülmez.','When reviewing an instrument, record language, permission and research on the target population separately. The catalogue proposes checking the adaptation study and use conditions alongside the original publication. Finding a form online should not be turned into an assumption that it can be republished or is valid for another population.','Bei der Prüfung eines Instruments sollten Sprache, Erlaubnis und Untersuchungen zur Zielgruppe getrennt dokumentiert werden. Vorgeschlagen wird, neben der Originalpublikation die Anpassungsstudie und Nutzungsbedingungen zu prüfen. Die Verfügbarkeit eines Formulars im Internet bedeutet nicht, dass es erneut veröffentlicht werden darf oder für eine andere Gruppe gültig ist.','评估工具时，应分别记录语言、许可及目标群体研究。建议同时核查原始出版物、适配研究和使用条件。在网上找到表格，不应被视为可以转载或对另一群体有效的依据。','При рассмотрении инструмента отдельно фиксируются язык, разрешение и исследования целевой группы. Предлагается проверять адаптационное исследование и условия использования вместе с оригинальной публикацией. Доступность формы в интернете не означает права на переиздание или валидности для другой группы.')),"""
assert len(re.findall(pattern,s))==1
p.write_text(re.sub(pattern,lambda m:replacement,s))
newen='When reviewing an instrument, record language, permission and research on the target population separately. The catalogue proposes checking the adaptation study and use conditions alongside the original publication. Finding a form online should not be turned into an assumption that it can be republished or is valid for another population.'
translations={'ar':'عند مراجعة أداة قياس، تُسجل اللغة وإذن الاستخدام والبحوث المتعلقة بالفئة المستهدفة في حقول منفصلة. يُقترح فحص دراسة التكييف وشروط الاستخدام إلى جانب المنشور الأصلي. وجود نموذج على الإنترنت لا يعني جواز إعادة نشره أو صلاحيته لفئة أخرى.','id':'Saat meninjau instrumen, catat bahasa, izin, dan penelitian pada populasi sasaran secara terpisah. Katalog ini mengusulkan pemeriksaan studi adaptasi dan ketentuan penggunaan bersama publikasi asli. Ketersediaan formulir di internet tidak boleh dianggap sebagai izin untuk menerbitkannya kembali atau bukti validitas bagi populasi lain.','ms':'Semasa meneliti instrumen, catat bahasa, kebenaran dan penyelidikan tentang populasi sasaran secara berasingan. Katalog ini mencadangkan semakan kajian penyesuaian serta syarat penggunaan bersama penerbitan asal. Kewujudan borang dalam talian tidak bererti ia boleh diterbitkan semula atau sah untuk populasi lain.'}
for l,text in translations.items():
 p=root/f'src/locales/{l}.json';j=json.loads(p.read_text());j['translations'][newen]=text;p.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
p=root/'src/campus-copy.mjs';s=p.read_text();p.write_text('\n'.join(line for line in s.splitlines() if not any(line.lstrip().startswith(k+':C(')for k in ['heroFirst','heroSecond','heroQuestion','question','institutionMap','mapLead']))+'\n')
p=root/'package.json';j=json.loads(p.read_text());j['version']='0.4.0';j['scripts']['test']='node --test tests/core.test.mjs tests/locales.test.mjs tests/campus.test.mjs tests/editorial-scope.test.mjs';p.write_text(json.dumps(j,indent=2)+'\n')
p=root/'scripts/build.mjs';p.write_text(p.read_text().replace("version:'0.3.0'","version:'0.4.0'"))
p=root/'public/app.js';p.write_text(p.read_text().replace('data/search-${locale}.json`','data/search-${locale}.json?v=0.4.0`'))
p=root/'public/campus.css';s=p.read_text();p.write_text(s+(root/'.github/scope-style.css').read_text())
p=root/'tests/campus.test.mjs';s=p.read_text()
s=s.replace("test('four requested institutions, no invented partnerships',()=>{assert.deepEqual(institutions.map(x=>x.id),['harvard','duke','smbi','iapr']);for(const x of institutions){assert.equal(x.relationship,'external-resource');assert.ok(x.links.length>=3);for(const l of locales)assert.ok(x.summary[l]);}});", "test('design benchmarks are excluded from the public content',()=>assert.deepEqual(institutions,[]));")
s=s.replace("test('new institution resources preserve bounded provenance',()=>{for(const id of ['s-smbi','s-iapr']){const s=sources.find(x=>x.id===id);assert.ok(s);assert.equal(s.level,'V1');assert.equal(s.status,'PARTIALLY_VERIFIED');assert.equal(s.inspection,'official');}});", "test('institution directory entries are not shipped as scholarly sources',()=>{for(const id of ['s-smbi','s-iapr','s-duke','s-harvard'])assert.ok(!sources.some(x=>x.id===id));});")
p.write_text(s)
p=root/'tests/build.test.mjs';s=p.read_text()+'''\ntest('no design benchmark institutions in public HTML, search or source data',async()=>{\n const banned=/Harvard|Duke|GWish|Danielsen|Columbia|\\bSMBI\\b|\\bIAPR\\b|RCPsych|Bilkent/i;\n for(const{path,html}of pages)assert.ok(!banned.test(html),path);\n for(const l of locales)assert.ok(!banned.test(await readFile(resolve(dist,`data/search-${l}.json`),'utf8')),l);\n assert.ok(!banned.test(await readFile(resolve(dist,'data/source-ledger.json'),'utf8')));\n});\n''';p.write_text(s)
p=root/'tests/campus_e2e.py';s=p.read_text().replace("'network/'","'about/'")
a=s.index("            page.goto(origin+base+l+'/events/'");b=s.index('            ctx.close()',a)
s=s[:a]+"            page.goto(origin+base+l+'/events/',wait_until='networkidle')\n            ck(f'no unapproved external event feed {l}',page.locator('.event-card').count()==0 and page.locator('.centre-empty').count()==1)\n"+s[b:];p.write_text(s)
(root/'docs/SCOPE_CORRECTION_TR.md').write_text('''# MARSAM. Kurumsal içerik düzeltmesi\n\nSürüm 0.4.0.\n\nDış kurumlar tasarım ve bilgi mimarisi incelemesinin örnekleridir. Kurum dizini, marka vitrini veya dış etkinlik akışı olarak kamusal siteye taşınmaz. Önceki karşılaştırmalı raporlar geliştirme belgesi olarak kalır. Bunların kurum kartı ve etkinlik aktarımı yönündeki uygulama kararları bu sürümde geri alınmıştır.\n\nAna sayfa merkezin tam adıyla açılır. Kurumsal kapsam maneviyat ve ruh sağlığı alanında araştırma, eğitim, mesleki gelişim ve bilgi paylaşımıdır. Bir araştırmacının danışan tercihi sorusu merkezin sloganı, tek araştırma gündemi veya kurumsal görüşü olarak kullanılmaz.\n\nBilimsel makale ve kitap künyeleri ile tasarım referansları ayrılır. Alanla ilgili gerçek yayınların kaynak bilgileri korunur. Özel ders dosyaları veya yayımlanmamış çalışmalar web içeriğine aktarılmaz. Onaylı içerik bulunmayan etkinlik, haber, proje ve video alanlarında gerçek durum belirtilir. Dış kurum içeriğiyle veya uydurma kayıtlarla bu boşluklar doldurulmaz.\n\nTürkçe, İngilizce, Almanca, Çince, Rusça, Arapça, Endonezce ve Malayca kapsamı korunur. Çeviriler insan dil ve bilimsel incelemesi bekleyen taslaklardır. Marmara kurumsal işaretleri ve planlanan merkez statüsü korunur. Teknik önizleme yayını resmî kuruluş veya bilimsel onay değildir.\n\nKabul ölçütleri yalnız teknik hatasızlık değildir. Ana başlığın kurumsal kapsamı temsil etmesi, bütün kamuya açık sayfalarda referans kurum vitrininin kaldırılması, arama ve indirilen veri dosyalarında aynı ayrımın korunması ve eski kurum kayıtlarının yayın klasöründe kalmaması ayrıca sınanır.\n''')
