import {sourcesA} from './sources-a.mjs';
import {sourcesB} from './sources-b.mjs';
import {sourcesC} from './sources-c.mjs';
import {sourcesD} from './sources-d.mjs';
export const strategicSources=[...sourcesA,...sourcesB,...sourcesC,...sourcesD];
export const q=(tr,en)=>({tr,en,de:en,zh:en,ru:en,ar:en,id:en,ms:en});
const card={
 's-spirituality-ptsd-review':['Depresyon, anksiyete ve PTSD için güncel sistematik derleme','17 çalışmalık anlatısal sentez, olası yararlı ilişkilerin yanında manevi çatışma ve karşılanmamış manevi ihtiyaçlarla ilişkili sıkıntıyı da ayırır.','A 17-study narrative synthesis separates potentially beneficial associations from distress linked to spiritual conflict and unmet spiritual needs.'],
 's-rss-ff-tr':['RSS-FF Türkiye uyarlaması · 22 madde','Beş faktörlü Türkçe form, mevcut RSS-14 kaydından ayrı bir araç sürümüdür.','The five-factor Turkish form is a distinct instrument version from the existing RSS-14 record.'],
 's-sprs':['Manevi Psikolojik Sağlamlık Ölçeği','Türkiye bağlamında geliştirme çalışmasıdır. Kültürler arası değişmezlik için ayrı kanıt gerekir.','A development study in the Turkish context. Cross-cultural invariance requires separate evidence.'],
 's-sefc':['Manevi Empati Yorgunluğu Ölçeği','İnanç temelli yardım sunan profesyoneller için geliştirilen dört boyutlu ölçme aracıdır. Bağımsız tekrar çalışmaları gerekir.','A four-dimensional measure developed for faith-based care providers. Independent replication remains needed.'],
 's-hemodialysis-spiritual-care':['Hemodiyalizde manevi bakım · randomize kontrollü çalışma','Türkiye’de 71 hemodiyaliz hastasıyla yürütülen randomize çalışma müdahale kanıtı ekler, fakat tek çalışma geniş klinik genelleme için yeterli değildir.','A Turkish randomized trial with 71 haemodialysis patients adds intervention evidence, but one study is insufficient for broad clinical generalisation.'],
 's-muslim-coping-multinational':['Üç Müslüman bağlamda olumlu dini başa çıkma','706 üniversite öğrencisinde olumlu dini başa çıkma yaşam doyumuyla ilişkiliydi, depresif belirtilerle ilişkili değildi.','Among 706 university students in Türkiye, Malaysia and Israel/Palestine, positive religious coping related to life satisfaction but not depressive symptoms.'],
 's-refugee-faith-coping':['Berlin’de Arapça konuşan mültecilerde inanç temelli başa çıkma','Ruh sağlığı hizmeti arayan 17 mülteciyle nitel çalışma, inanç temelli başa çıkmayı göç ve hizmet erişimi bağlamında inceler.','A qualitative study with 17 refugees seeking mental-health services examines faith-based coping in migration and service-access contexts.'],
 's-nonreligious-turkiye':['Türkiye’de ateist, deist ve agnostik bireylerin sağlık hizmeti deneyimleri','Samsun’da 17 katılımcıyla çalışma, dinsiz kimlik, görünmezlik, yargılanma ve profesyonel tarafsızlık beklentilerini inceler.','A phenomenological study with 17 participants in Samsun examines nonreligious identity, invisibility, judgement and expectations of professional neutrality.'],
 's-religious-sexual-stigma':['Dinsel temelli cinsel stigma, dini mücadele ve psikolojik sağlık','Dinsel stigma, içselleştirme ve dini mücadeleyi birlikte ele alarak maneviyatın her bağlamda koruyucu olduğu varsayımını sınar.','The study links religious-based sexual stigma, internalization and religious struggle, challenging any assumption of universal spiritual protection.'],
 's-atheist-minority-stress':['Ateist azınlık stresi ve psikolojik sonuçlar','522 ateist yetişkinde ayrımcılık, stigma bilinci, içselleştirilmiş anti-ateizm ve açılma süreçlerini psikolojik sıkıntı ve benlik saygısıyla ilişkilendirir.','Links discrimination, stigma consciousness, internalized anti-atheism and outness with distress and self-esteem in 522 atheist adults.'],
 's-sexual-minority-rs-meta':['Cinsel azınlıklarda din, maneviyat ve sağlık · meta-analiz','73 çalışmadaki 279 etki büyüklüğü küçük ve heterojen bir genel ilişki gösterir. Düzeltme kaydı sonuçların yönünü değiştirmemiştir.','Across 279 effect sizes in 73 studies, the overall association is small and heterogeneous. A published correction did not change the conclusions.'],
 's-lgbq-religious-family-therapy':['Dindar ailelerden LGBQ genç yetişkinlerin psikoterapi deneyimleri','Nitel çalışma terapi ilişkisi, aile, din ve görünmez dini söylemlerin deneyimdeki rolünü inceler.','A qualitative inquiry examines therapy relationships, family, religion and often-invisible religious discourses in psychotherapy.'],
 's-lebanon-sexual-stigma':['Lübnan’da cinsel yönelim stigması, din ve ruh sağlığı','200 katılımcılı kesitsel çalışma dini bağlamın hem stigma hem başa çıkma ile ilişkili olabileceğini gösterir, nedensellik kurmaz.','A cross-sectional study of 200 participants shows religion can be associated with both stigma context and coping, without establishing causality.'],
 's-icsg-2':['ICSG 2.0 · karmaşık manevi yas','440 yaslı yetişkinde geliştirilen 28 maddelik üç faktörlü revize araçtır. Madde yeniden yayım hakkı varsayılmaz.','A revised 28-item, three-factor measure studied in 440 bereaved adults. Item-reproduction rights are not inferred.'],
 's-icsg-2-fa':['ICSG 2.0 · Farsça psikometrik çalışma','355 İranlı yetişkinde Farsça formun psikometrik kanıtını inceler. Kültürler arası uyarlama, ölçüm değişmezliğiyle aynı şey değildir.','Examines the Persian ICSG 2.0 in 355 Iranian adults. Cross-cultural adaptation is not the same as measurement invariance.'],
 's-p-sds':['Manevi Sıkıntı Ölçeği · Farsça uyarlama','Kanserli 300 ileri yaş yetişkinde P-SDS uyarlamasını inceler ve manevi sıkıntıyı düşük iyi oluştan ayrı bir ölçme problemi olarak görünür kılar.','Examines P-SDS adaptation in 300 older adults with cancer and helps distinguish spiritual distress from simply low wellbeing.'],
 's-religious-minority-context':['Dini azınlıklar, bağlam ve depresif duygular','ESS 2012 ve 2014 verilerinde 28 ülkedeki 268 bölgeyi karşılaştırır. Bağlam düzeyindeki ilişkiler bireysel nedensellik olarak okunmamalıdır.','Uses ESS 2012 and 2014 data across 268 regions in 28 countries. Context-level associations should not be read as individual causation.']
};
export const strategicResources=strategicSources.map(s=>{const [tr,trSummary,en]=card[s.id];return {id:s.id.slice(2),title:q(tr,s.title),summary:q(trSummary,en),sections:['library',s.kind==='measure'?'measurement-observatory':'evidence-bridges'],topic:s.kind==='measure'?'assessment':'evidence',sources:[s.id],kind:s.kind,review:'draft',translation:'draft',rights:'link-only',approval:null};});
export const strategicSections=[
 {id:'measurement-observatory',title:q('Ölçme Gözlemevi','Measurement Observatory'),summary:q('Ölçek ailesi, sürüm, dil formu, geliştirme veya uyarlama statüsü, psikometrik kanıt ve izin durumunu birbirinden ayır.','Separate instrument family, version, language form, development or adaptation status, psychometric evidence and permissions.'),group:'research',topic:'assessment'},
 {id:'evidence-bridges',title:q('Türkiye · Uluslararası Kanıt Köprüleri','Türkiye · International Evidence Bridges'),summary:q('Türkiye bulgularını uluslararası çalışmalarla aynı tasarım türüymüş gibi birleştirmeden karşılaştır.','Compare Turkish and international evidence without treating unlike designs as equivalent.'),group:'research',topic:'evidence'},
 {id:'datasets',title:q('Araştırma Veri Setleri Dizini','Research Dataset Registry'),summary:q('Veriyi yeniden barındırmadan erişim, kapsam, tasarım ve çıkarım sınırlarını birlikte göster.','Show access, scope, design and inferential limits without rehosting datasets.'),group:'research',topic:'methods'},
 {id:'construct-dictionary',title:q('Yapı ve Kavram Sözlüğü','Construct Dictionary'),summary:q('Yakın görünen kavramları tanı, ölçme ve klinik iddia üretmeden birbirinden ayır.','Distinguish adjacent constructs without turning definitions into diagnoses, measures or clinical claims.'),group:'explore',topic:'foundations'}
];
export const instruments=[
 {id:'rss-ff-tr',family:'religious-spiritual-struggles',sourceId:'s-rss-ff-tr',title:'RSS-FF Türkiye · 22',status:'adaptation',language:'tr',construct:'religious and spiritual struggles',properties:['CFA','internal consistency','convergent/divergent validity'],invariance:'not reported in inspected abstract',rights:'link-only; item text not republished'},
 {id:'sprs',family:'spiritual-psychological-robustness',sourceId:'s-sprs',title:'SPRS',status:'development',language:'tr',construct:'spiritual psychological robustness',properties:['EFA','CFA','internal consistency','criterion validity'],invariance:'cross-cultural invariance not established',rights:'link-only; item text not republished'},
 {id:'sefc',family:'spiritual-empathy-fatigue',sourceId:'s-sefc',title:'SEFC',status:'development',language:'tr',construct:'spiritual empathy fatigue',properties:['EFA','CFA','internal consistency','test-retest'],invariance:'not established',rights:'link-only; item text not republished'},
 {id:'swbs-eksi-kardas',family:'spiritual-wellbeing-eksi-kardas',sourceId:'s-swbs-eksi-kardas',title:'SWBS · Ekşi & Kardaş · 29',status:'development',language:'tr',construct:'spiritual well-being',properties:['factor structure','internal consistency'],invariance:'see source record',rights:'permission must be checked before item reproduction'},
 {id:'swbs-paloutzian-ellison',family:'spiritual-wellbeing-paloutzian-ellison',sourceId:'s-swbs-paloutzian-ellison',title:'SWBS · Paloutzian & Ellison · 20',status:'development',language:'en',construct:'spiritual well-being',properties:['original conceptualization and measurement'],invariance:'language and population specific evidence required',rights:'permission must be checked before item reproduction'},
 {id:'icsg-2',family:'inventory-complicated-spiritual-grief',sourceId:'s-icsg-2',title:'ICSG 2.0 · 28',status:'validation',language:'en',construct:'complicated spiritual grief',properties:['factor structure','convergent validity','incremental validity'],invariance:'cross-language invariance not established by this record',rights:'link-only; item text not republished'},
 {id:'icsg-2-fa',family:'inventory-complicated-spiritual-grief',sourceId:'s-icsg-2-fa',title:'ICSG 2.0 · Persian',status:'adaptation',language:'fa',construct:'complicated spiritual grief',properties:['CFA','internal consistency','test-retest','convergent/divergent validity'],invariance:'adaptation evidence does not establish cross-language invariance',rights:'link-only; item text not republished'},
 {id:'p-sds',family:'spiritual-distress-scale',sourceId:'s-p-sds',title:'P-SDS',status:'adaptation',language:'fa',construct:'spiritual distress',properties:['content validity','CFA','internal consistency','test-retest','concurrent validity'],invariance:'cross-language invariance not established by this record',rights:'link-only; item text not republished'}
];
const instrumentForms={
 'rss-ff-tr':{form:'five-factor-22-item',itemCount:22},
 'swbs-eksi-kardas':{form:'eksi-kardas-29-item',itemCount:29},
 'swbs-paloutzian-ellison':{form:'paloutzian-ellison-20-item',itemCount:20},
 'icsg-2':{form:'2.0',itemCount:28},
 'icsg-2-fa':{form:'2.0-persian',itemCount:28},
 'p-sds':{form:'persian-adaptation',itemCount:null}
};
for(const instrument of instruments){
 Object.assign(instrument,instrumentForms[instrument.id]||{form:null,itemCount:null});
 instrument.measurementProperties=instrument.properties.map(property=>({property,method:null,resultSummary:null,sourceId:instrument.sourceId,appraisal:{framework:'COSMIN',status:'NOT_YET_APPRAISED'}}));
 instrument.rightsDetail={itemReproduction:'NOT_CLEARED',scoringInstructions:'NOT_CLEARED',translationReuse:'NOT_CLEARED'};
}
export const datasets=[
 {id:'ess',title:'European Social Survey',url:'https://www.europeansocialsurvey.org/data-portal',scope:'Cross-national repeated surveys. Inspect round-specific religion, wellbeing and health variables before analysis.',access:'Official ESS data portal. Round-specific terms and documentation govern use.'},
 {id:'evs',title:'European Values Study',url:'https://www.gesis.org/en/european-values-study/data-and-documentation',scope:'Values, religion, family, work, politics and society. Not every wave contains a mental-health outcome suitable for a MARSAM question.',access:'EVS/GESIS documentation and data access. Registration and usage terms may apply.'},
 {id:'wvs',title:'World Values Survey',url:'https://www.worldvaluessurvey.org/WVSDocumentationWV7.jsp',scope:'Cross-national values and beliefs. Repeated cross-sections are not respondent-level longitudinal panels.',access:'Official WVS documentation. Registration and non-redistribution terms may apply.'},
 {id:'midus',title:'MIDUS · Midlife in the United States',url:'https://midus.wisc.edu/religion-and-spirituality/',scope:'Longitudinal US study with religion/spirituality, psychological wellbeing, purpose, mental illness and health domains. US context limits transfer.',access:'Official MIDUS documentation and public data resources; study-specific terms remain authoritative.'}
];
export const constructs=[
 {id:'spiritual-distress',tr:'Manevi sıkıntı',en:'Spiritual distress',boundary:'Distress involving spiritual meaning, connection or conflict. It is not interchangeable with low spiritual well-being and is not a diagnosis.'},
 {id:'rs-struggle',tr:'Dini ve manevi mücadele',en:'Religious and spiritual struggle',boundary:'Conflict or tension involving divine, interpersonal, moral, doubt or ultimate-meaning domains. Positive and negative consequences are both possible.'},
 {id:'religious-trauma',tr:'Dinle ilişkili travma',en:'Religious trauma',boundary:'A contested umbrella term. Distinguish traumatic events, adverse religious experiences, coercion, stigma and post-traumatic outcomes rather than assume a single syndrome.'},
 {id:'worldview-nonreligion',tr:'Dünya görüşü ve dinsizlik',en:'Worldview and nonreligion',boundary:'Religious, spiritual, secular, atheist, agnostic and other meaning systems are possible worldviews. None is treated as the default.'},
 {id:'spiritual-bypassing',tr:'Manevi bypass',en:'Spiritual bypassing',boundary:'Use of spiritual frameworks in ways that may avoid unresolved psychological distress. It is culturally contingent and not a diagnostic label.'},
 {id:'cultural-humility',tr:'Kültürel alçakgönüllülük',en:'Cultural humility',boundary:'An ongoing reflective stance toward power, assumptions and the person’s own meaning system, not a claim of mastering a culture.'},
 {id:'measurement-invariance',tr:'Ölçüm değişmezliği',en:'Measurement invariance',boundary:'Evidence that scores can be compared across groups or time under specified assumptions. Translation or good internal consistency alone does not establish invariance.'},
 {id:'adverse-religious-experiences',tr:'Olumsuz dini deneyimler',en:'Adverse religious experiences',boundary:'A descriptive category for coercion, stigma, abuse, exclusion or spiritually harmful experiences. Mechanism and outcome should be recorded separately.'}
];
export const bridges=[
 {id:'muslim-coping',title:q('Müslüman bağlamlarda dini başa çıkma','Religious coping across Muslim contexts'),text:q('Türkiye, Malezya ve İsrail/Filistin karşılaştırması olumlu dini başa çıkmanın depresif belirtiyle otomatik olarak ilişkili olmadığını gösterir. Mülteci çalışması ise başa çıkmanın göç ve hizmet erişimi bağlamında nasıl yaşandığını nitel olarak açar.','A multinational Muslim comparison shows that positive religious coping is not automatically linked to depressive symptoms. Refugee evidence adds contextual accounts of coping, migration and service access.'),sourceIds:['s-muslim-coping-multinational','s-refugee-faith-coping']},
 {id:'turkiye-intervention',title:q('Türkiye’de müdahale kanıtını doğru okumak','Reading intervention evidence from Türkiye'),text:q('Hemodiyaliz RCT’si nedensel sorular için kesitsel çalışmalardan daha güçlü bir tasarım sunar. Yine de tek merkez, örneklem ve raporlama ayrıntıları genellenebilirliği sınırlar.','The haemodialysis RCT is stronger for causal questions than cross-sectional evidence, while single-study context and reporting still limit generalisation.'),sourceIds:['s-hemodialysis-spiritual-care']},
 {id:'worldview-plurality',title:q('Dünya görüşü çoğulluğu ve zarar','Worldview plurality and harm'),text:q('Dinsiz bireylerin sağlık hizmeti deneyimleri ile dinsel temelli cinsel stigma çalışmaları, maneviyatın her kullanıcı için koruyucu veya istenen bir çerçeve olmadığını görünür kılar.','Evidence on nonreligious healthcare experiences and religious-based sexual stigma makes visible that spiritual framing is not universally protective or desired.'),sourceIds:['s-nonreligious-turkiye','s-religious-sexual-stigma']},
 {id:'measurement-lineage',title:q('Ölçek soy ağacı ve kültürel geçerlik','Instrument lineage and cultural validity'),text:q('RSS-FF, RSS-14 ile aynı kayıt değildir. SPRS ve SEFC ise Türkiye’de geliştirilmiş ayrı yapılardır. Geliştirme, uyarlama, doğrulama ve değişmezlik kanıtı ayrı tutulmalıdır.','RSS-FF is not the same record as RSS-14. SPRS and SEFC are separate constructs developed in Türkiye. Development, adaptation, validation and invariance evidence must remain distinct.'),sourceIds:['s-rss-ff-tr','s-sprs','s-sefc']},
 {id:'minority-context',title:q('Azınlık stresi, din ve bağlam','Minority stress, religion and context'),text:q('Ateist azınlık stresi, cinsel azınlık meta-analizi ve Lübnan çalışması din veya maneviyatın tek yönlü bir koruyucu değişken olmadığını gösterir. Stigma, kimlik gelişimi ve sosyal çevre sonuçların yönünü değiştirebilir.','Atheist minority stress, the sexual-minority meta-analysis and Lebanon evidence show that religion or spirituality is not a one-direction protective variable. Stigma, identity development and social context can change the direction of associations.'),sourceIds:['s-atheist-minority-stress','s-sexual-minority-rs-meta','s-lebanon-sexual-stigma']},
 {id:'spiritual-distress-grief',title:q('Manevi sıkıntı, yas ve ölçme','Spiritual distress, grief and measurement'),text:q('ICSG 2.0, Farsça uyarlaması ve P-SDS manevi sıkıntının düşük manevi iyi oluşla özdeş olmadığını gösteren ayrı ölçme geleneklerini temsil eder. Uyarlama ve değişmezlik kanıtı ayrı tutulur.','ICSG 2.0, its Persian adaptation and P-SDS represent distinct measurement traditions showing that spiritual distress is not identical to low spiritual wellbeing. Adaptation and invariance evidence remain separate.'),sourceIds:['s-icsg-2','s-icsg-2-fa','s-p-sds']},
 {id:'context-level-evidence',title:q('Bireysel skorun ötesinde dini bağlam','Religious context beyond individual scores'),text:q('ESS temelli çok düzeyli çalışma dini azınlık ve depresif duygular ilişkisini bölgesel bağlamla birlikte inceler. Bu, bireysel başa çıkma çalışmalarından farklı bir çıkarım düzeyidir.','The ESS-linked multilevel study examines religious-minority status and depressive feelings together with regional context. This is a different level of inference from individual coping studies.'),sourceIds:['s-religious-minority-context']}
];
export const claims=bridges.map(b=>({id:'bridge:'+b.id,sourceIds:b.sourceIds,support:'editorial-synthesis',reviewStatus:'AI_ASSISTED_DRAFT',checked:'2026-10-05'}));
