import {rc} from './copy.mjs';
import {sourcesA} from './sources-a.mjs';
import {sourcesB} from './sources-b.mjs';
import {sourcesC} from './sources-c.mjs';
import {sourcesD} from './sources-d.mjs';
export const strategicSources=[...sourcesA,...sourcesB,...sourcesC,...sourcesD];
import qLocales from './q-locales.json' with {type:'json'};
/** Turkish source keys bind the localizations; a missing entry fails the build instead of shipping English. */
export const q=(tr,en)=>{const t=qLocales[tr];if(!t)throw new Error(`Missing roadmap localization: ${tr} / ${en}`);return {tr,...t};};
const card={
 's-spirituality-ptsd-review':['Depresyon, anksiyete ve PTSD için güncel sistematik derleme','17 çalışmanın anlatısal sentezi, olası yararlı ilişkilerin yanı sıra manevi çatışma ve karşılanmamış manevi ihtiyaçlarla ilişkili sıkıntıyı da ayrıca ele almaktadır.','A 17-study narrative synthesis separates potentially beneficial associations from distress linked to spiritual conflict and unmet spiritual needs.'],
 's-rss-ff-tr':['RSS-FF Türkiye uyarlaması · 22 madde','Beş faktörlü Türkçe form, RSS-14’ten ayrı bir ölçek sürümüdür.','The five-factor Turkish form is a distinct instrument version from the existing RSS-14 record.'],
 's-sprs':['Manevi Psikolojik Sağlamlık Ölçeği','Türkiye’de yürütülmüş bir ölçek geliştirme çalışmasıdır. Ölçeğin farklı kültürlerde karşılaştırılabilir olduğunu göstermek için ayrı kanıt gerekir.','A development study in the Turkish context. Cross-cultural invariance requires separate evidence.'],
 's-sefc':['Manevi Empati Yorgunluğu Ölçeği','İnanç temelli yardım sunan profesyoneller için geliştirilmiş dört boyutlu bir ölçme aracıdır. Bulguların bağımsız çalışmalarla tekrarlanması gerekmektedir.','A four-dimensional measure developed for faith-based care providers. Independent replication remains needed.'],
 's-hemodialysis-spiritual-care':['Hemodiyalizde manevi bakım · randomize kontrollü çalışma','Türkiye’de 71 hemodiyaliz hastasıyla yürütülen randomize çalışma müdahaleye ilişkin kanıt sunmaktadır; ancak tek bir çalışma geniş klinik genelleme için yeterli değildir.','A Turkish randomized trial with 71 haemodialysis patients adds intervention evidence, but one study is insufficient for broad clinical generalisation.'],
 's-muslim-coping-multinational':['Üç Müslüman bağlamda olumlu dini başa çıkma','706 üniversite öğrencisinde olumlu dini başa çıkma yaşam doyumuyla ilişkili bulunmuş, depresif belirtilerle ilişkili bulunmamıştır.','Among 706 university students in Türkiye, Malaysia and Israel/Palestine, positive religious coping related to life satisfaction but not depressive symptoms.'],
 's-refugee-faith-coping':['Berlin’de Arapça konuşan mültecilerde inanç temelli başa çıkma','Ruh sağlığı hizmeti arayan 17 mülteciyle yürütülen nitel çalışma, inanç temelli başa çıkmayı göç ve hizmete erişim koşulları içinde incelemektedir.','A qualitative study with 17 refugees seeking mental-health services examines faith-based coping in migration and service-access contexts.'],
 's-nonreligious-turkiye':['Türkiye’de ateist, deist ve agnostik bireylerin sağlık hizmeti deneyimleri','Samsun’da 17 katılımcıyla yürütülen çalışma, dini olmayan kimliği, görünmezliği, yargılanmayı ve sağlık profesyonellerinden beklenen tarafsızlığı incelemektedir.','A phenomenological study with 17 participants in Samsun examines nonreligious identity, invisibility, judgement and expectations of professional neutrality.'],
 's-religious-sexual-stigma':['Dinsel temelli cinsel stigma, dini mücadele ve psikolojik sağlık','Dine dayalı damgalanmayı, bu damgalanmanın içselleştirilmesini ve dini mücadeleyi birlikte ele alarak maneviyatın her bağlamda koruyucu olduğu varsayımını sınamaktadır.','The study links religious-based sexual stigma, internalization and religious struggle, challenging any assumption of universal spiritual protection.'],
 's-atheist-minority-stress':['Ateist azınlık stresi ve psikolojik sonuçlar','522 ateist yetişkinde ayrımcılık, damgalanma farkındalığı, içselleştirilmiş ateizm karşıtlığı ve kimliğini açma süreçlerinin psikolojik sıkıntı ve benlik saygısıyla ilişkisini incelemektedir.','Links discrimination, stigma consciousness, internalized anti-atheism and outness with distress and self-esteem in 522 atheist adults.'],
 's-sexual-minority-rs-meta':['Cinsel azınlıklarda din, maneviyat ve sağlık · meta-analiz','73 çalışmadan elde edilen 279 etki büyüklüğü, küçük ve çalışmalar arasında değişkenlik gösteren bir genel ilişkiye işaret etmektedir. Yapılan düzeltme sonuçların yönünü değiştirmemiştir.','Across 279 effect sizes in 73 studies, the overall association is small and heterogeneous. A published correction did not change the conclusions.'],
 's-lgbq-religious-family-therapy':['Dindar ailelerden LGBQ genç yetişkinlerin psikoterapi deneyimleri','Nitel çalışma, terapötik ilişkinin, ailenin, dinin ve açıkça dile getirilmeyen dini söylemlerin bu deneyimdeki rolünü incelemektedir.','A qualitative inquiry examines therapy relationships, family, religion and often-invisible religious discourses in psychotherapy.'],
 's-lebanon-sexual-stigma':['Lübnan’da cinsel yönelim stigması, din ve ruh sağlığı','200 katılımcılı kesitsel çalışma, dini bağlamın hem damgalanmayla hem de başa çıkmayla ilişkili olabileceğini göstermektedir; ancak neden-sonuç ilişkisi kurmamaktadır.','A cross-sectional study of 200 participants shows religion can be associated with both stigma context and coping, without establishing causality.'],
 's-icsg-2':['ICSG 2.0 · karmaşık manevi yas','Yas tutan 440 yetişkinle geliştirilen 28 maddelik ve üç faktörlü gözden geçirilmiş bir ölçme aracıdır. Ölçek maddelerinin yeniden yayımlanabileceği varsayılmamalıdır.','A revised 28-item, three-factor measure studied in 440 bereaved adults. Item-reproduction rights are not inferred.'],
 's-icsg-2-fa':['ICSG 2.0 · Farsça psikometrik çalışma','355 İranlı yetişkinle yürütülmüştür. Farsça formun psikometrik özelliklerini incelemektedir. Bir ölçeğin başka bir kültüre uyarlanması, gruplar arasında karşılaştırılabilir sonuçlar verdiği anlamına gelmez.','Examines the Persian ICSG 2.0 in 355 Iranian adults. Cross-cultural adaptation is not the same as measurement invariance.'],
 's-p-sds':['Manevi Sıkıntı Ölçeği · Farsça uyarlama','Kanser tanılı 300 ileri yaş yetişkinde P-SDS uyarlamasını inceleyen çalışma, manevi sıkıntının düşük iyi oluştan ayrı bir ölçme konusu olduğunu göstermektedir.','Examines P-SDS adaptation in 300 older adults with cancer and helps distinguish spiritual distress from simply low wellbeing.'],
 's-religious-minority-context':['Dini azınlıklar, bağlam ve depresif duygular','ESS’nin 2012 ve 2014 verilerinde 28 ülkedeki 268 bölgeyi karşılaştırmaktadır. Bölge düzeyinde bulunan ilişkiler, bireyler için neden-sonuç ilişkisi olarak okunmamalıdır.','Uses ESS 2012 and 2014 data across 268 regions in 28 countries. Context-level associations should not be read as individual causation.']
};
export const strategicResources=strategicSources.map(s=>{const [tr,trSummary,en]=card[s.id];return {id:s.id.slice(2),title:q(tr,s.title),summary:q(trSummary,en),sections:['library',s.kind==='measure'?'measurement-observatory':'evidence-bridges'],topic:s.kind==='measure'?'assessment':'evidence',sources:[s.id],kind:s.kind,review:'draft',translation:'draft',rights:'link-only',approval:null};});
const localeField=key=>Object.fromEntries(Object.entries(rc).map(([locale,copy])=>[locale,copy[key]]));
export const strategicSections=[
 {id:'measurement-observatory',title:localeField('measurementTitle'),summary:localeField('measurementLead'),group:'research',topic:'assessment'},
 {id:'evidence-bridges',title:localeField('bridgesTitle'),summary:localeField('bridgesLead'),group:'research',topic:'evidence'},
 {id:'datasets',title:localeField('datasetsTitle'),summary:localeField('datasetsLead'),group:'research',topic:'methods'},
 {id:'construct-dictionary',title:localeField('constructsTitle'),summary:localeField('constructsLead'),group:'explore',topic:'foundations'}
];
export const instruments=[
 {id:'rss-ff-tr',family:'religious-spiritual-struggles',sourceId:'s-rss-ff-tr',title:'RSS-FF Türkiye · 22',status:'adaptation',language:'tr',construct:'religious and spiritual struggles',properties:['CFA','internal consistency','convergent/divergent validity'],invariance:'not reported in inspected abstract',rights:'link-only; item text not republished'},
 {id:'sprs',family:'spiritual-psychological-robustness',sourceId:'s-sprs',title:'SPRS',status:'development',language:'tr',construct:'spiritual psychological robustness',properties:['EFA','CFA','internal consistency','criterion validity'],invariance:'cross-cultural invariance not established',rights:'link-only; item text not republished'},
 {id:'sefc',family:'spiritual-empathy-fatigue',sourceId:'s-sefc',title:'SEFC',status:'development',language:'tr',construct:'spiritual empathy fatigue',properties:['EFA','CFA','internal consistency','test-retest'],invariance:'not established',rights:'link-only; item text not republished'},
 {id:'swbs-eksi-kardas',family:'spiritual-wellbeing-eksi-kardas',sourceId:'s-swbs-eksi-kardas',title:'SWBS · Ekşi & Kardaş · 29',status:'development',language:'tr',construct:'spiritual well-being',properties:['factor structure','internal consistency'],invariance:'see source record',rights:'permission must be checked before item reproduction'},
 {id:'swbs-paloutzian-ellison',family:'spiritual-wellbeing-paloutzian-ellison',sourceId:'s-swbs-paloutzian-ellison',title:'SWBS · Paloutzian & Ellison · 20',status:'development',language:'en',construct:'spiritual well-being',properties:['original conceptualization and measurement'],invariance:'language and population specific evidence required',rights:'permission must be checked before item reproduction'},
 {id:'icsg-2',family:'inventory-complicated-spiritual-grief',sourceId:'s-icsg-2',title:'ICSG 2.0 · 28',status:'validation',language:'en',construct:'complicated spiritual grief',properties:['factor structure','convergent validity','incremental validity'],invariance:'cross-language invariance not established by this record',rights:'link-only; item text not republished'},
 {id:'icsg-2-fa',family:'inventory-complicated-spiritual-grief',sourceId:'s-icsg-2-fa',title:'ICSG 2.0 · Persian',status:'adaptation',language:'fa',construct:'complicated spiritual grief',properties:['CFA','internal consistency','test-retest','convergent/divergent validity'],invariance:'adaptation evidence does not establish cross-language invariance',rights:'link-only; item text not republished'},
 {id:'p-sds',family:'spiritual-distress-scale',sourceId:'s-p-sds',title:'P-SDS',status:'adaptation',language:'fa',construct:'spiritual distress',properties:['content validity','CFA','internal consistency','test-retest','concurrent validity'],invariance:'cross-language invariance not established by this record',rights:'link-only; item text not republished'}
];
const instrumentForms={
 'rss-ff-tr':{form:'five-factor-22-item',itemCount:22},
 'swbs-eksi-kardas':{form:'eksi-kardas-29-item',itemCount:29},
 'swbs-paloutzian-ellison':{form:'paloutzian-ellison-20-item',itemCount:20},
 'icsg-2':{form:'2.0',itemCount:28},
 'icsg-2-fa':{form:'2.0-persian',itemCount:28},
 'p-sds':{form:'persian-adaptation',itemCount:null}
};
for(const instrument of instruments){
 Object.assign(instrument,instrumentForms[instrument.id]||{form:null,itemCount:null});
 instrument.measurementProperties=instrument.properties.map(property=>({property,method:null,resultSummary:null,sourceId:instrument.sourceId,appraisal:{framework:'COSMIN',status:'NOT_YET_APPRAISED'}}));
 instrument.rightsDetail={itemReproduction:'NOT_CLEARED',scoringInstructions:'NOT_CLEARED',translationReuse:'NOT_CLEARED'};
}
export const datasets=[
 {id:'ess',title:'European Social Survey',url:'https://www.europeansocialsurvey.org/data-portal',scope:'Cross-national repeated surveys. Inspect round-specific religion, wellbeing and health variables before analysis.',access:'Official ESS data portal. Round-specific terms and documentation govern use.'},
 {id:'evs',title:'European Values Study',url:'https://www.gesis.org/en/european-values-study/data-and-documentation',scope:'Values, religion, family, work, politics and society. Not every wave contains a mental-health outcome suitable for a MARSAM question.',access:'EVS/GESIS documentation and data access. Registration and usage terms may apply.'},
 {id:'wvs',title:'World Values Survey',url:'https://www.worldvaluessurvey.org/WVSDocumentationWV7.jsp',scope:'Cross-national values and beliefs. Repeated cross-sections are not respondent-level longitudinal panels.',access:'Official WVS documentation. Registration and non-redistribution terms may apply.'},
 {id:'midus',title:'MIDUS · Midlife in the United States',url:'https://midus.wisc.edu/religion-and-spirituality/',scope:'Longitudinal US study with religion/spirituality, psychological wellbeing, purpose, mental illness and health domains. US context limits transfer.',access:'Official MIDUS documentation and public data resources; study-specific terms remain authoritative.'}
];
export const constructs=[
 {id:'spiritual-distress',tr:'Manevi sıkıntı',en:'Spiritual distress',boundary:'Distress involving spiritual meaning, connection or conflict. It is not interchangeable with low spiritual well-being and is not a diagnosis.'},
 {id:'rs-struggle',tr:'Dini ve manevi mücadele',en:'Religious and spiritual struggless',boundary:'Conflict or tension involving divine, interpersonal, moral, doubt or ultimate-meaning domains. Positive and negative consequences are both possible.'},
 {id:'religious-trauma',tr:'Dinle ilişkili travma',en:'Religious trauma',boundary:'A contested umbrella term. Distinguish traumatic events, adverse religious experiences, coercion, stigma and post-traumatic outcomes rather than assume a single syndrome.'},
 {id:'worldview-nonreligion',tr:'Dünya görüşü ve dinsizlik',en:'Worldview and nonreligion',boundary:'Religious, spiritual, secular, atheist, agnostic and other meaning systems are possible worldviews. None is treated as the default.'},
 {id:'spiritual-bypassing',tr:'Manevi bypass',en:'Spiritual bypassing',boundary:'Use of spiritual frameworks in ways that may avoid unresolved psychological distress. It is culturally contingent and not a diagnostic label.'},
 {id:'cultural-humility',tr:'Kültürel alçakgönüllülük',en:'Cultural humility',boundary:'An ongoing reflective stance toward power, assumptions and the person’s own meaning system, not a claim of mastering a culture.'},
 {id:'measurement-invariance',tr:'Ölçme değişmezliği',en:'Measurement invariance',boundary:'Evidence that scores can be compared across groups or time under specified assumptions. Translation or good internal consistency alone does not establish invariance.'},
 {id:'adverse-religious-experiences',tr:'Olumsuz dini deneyimler',en:'Adverse religious experiences',boundary:'A descriptive category for coercion, stigma, abuse, exclusion or spiritually harmful experiences. Mechanism and outcome should be recorded separately.'}
];
export const bridges=[
 {id:'muslim-coping',title:q('Müslüman bağlamlarda dini başa çıkma','Religious coping across Muslim contexts'),text:q('Türkiye, Malezya ve İsrail/Filistin’i karşılaştıran çalışma, olumlu dini başa çıkmanın depresif belirtilerle her zaman ilişkili olmadığını göstermektedir. Mültecilerle yapılan nitel çalışma ise başa çıkmanın göç ve hizmete erişim koşullarında nasıl yaşandığını ortaya koymaktadır.','A multinational Muslim comparison shows that positive religious coping is not automatically linked to depressive symptoms. Refugee evidence adds contextual accounts of coping, migration and service access.'),sourceIds:['s-muslim-coping-multinational','s-refugee-faith-coping']},
 {id:'turkiye-intervention',title:q('Türkiye’deki müdahale çalışmalarını doğru değerlendirmek','Reading intervention evidence from Türkiye'),text:q('Hemodiyaliz hastalarıyla yapılan randomize kontrollü çalışma, neden-sonuç sorularını yanıtlamada kesitsel çalışmalardan daha güçlü bir tasarıma sahiptir. Yine de tek merkezde yürütülmesi, örneklemi ve raporlama ayrıntıları bulguların genellenmesini sınırlamaktadır.','The haemodialysis RCT is stronger for causal questions than cross-sectional evidence, while single-study context and reporting still limit generalisation.'),sourceIds:['s-hemodialysis-spiritual-care']},
 {id:'worldview-plurality',title:q('Dünya görüşlerinin çeşitliliği ve olası zararlar','Worldview plurality and harm'),text:q('Dini olmayan bir dünya görüşüne sahip kişilerin sağlık hizmeti deneyimleri ile dine dayalı cinsel damgalanmaya ilişkin çalışmalar, maneviyatın herkes için koruyucu ya da istenen bir çerçeve olmadığını göstermektedir.','Evidence on nonreligious healthcare experiences and religious-based sexual stigma makes visible that spiritual framing is not universally protective or desired.'),sourceIds:['s-nonreligious-turkiye','s-religious-sexual-stigma']},
 {id:'measurement-lineage',title:q('Ölçeklerin kökeni ve kültürel geçerlik','Instrument lineage and cultural validity'),text:q('RSS-FF ile RSS-14 farklı ölçme araçlarıdır. SPRS ve SEFC ise Türkiye’de geliştirilmiş, ayrı yapıları ölçen araçlardır. Bir ölçeğin geliştirilmesi, başka bir dile uyarlanması, geçerliğinin sınanması ve gruplar arasında karşılaştırılabilirliği ayrı ayrı değerlendirilmelidir.','RSS-FF is not the same record as RSS-14. SPRS and SEFC are separate constructs developed in Türkiye. Development, adaptation, validation and invariance evidence must remain distinct.'),sourceIds:['s-rss-ff-tr','s-sprs','s-sefc']},
 {id:'minority-context',title:q('Azınlık stresi, din ve bağlam','Minority stress, religion and context'),text:q('Ateist azınlık stresi üzerine yapılan çalışma, cinsel azınlıklarla ilgili meta-analiz ve Lübnan’da yürütülen araştırma, din ya da maneviyatın her zaman koruyucu bir etken olmadığını göstermektedir. Damgalanma, kimlik gelişimi ve sosyal çevre, sonuçların yönünü değiştirebilmektedir.','Atheist minority stress, the sexual-minority meta-analysis and Lebanon evidence show that religion or spirituality is not a one-direction protective variable. Stigma, identity development and social context can change the direction of associations.'),sourceIds:['s-atheist-minority-stress','s-sexual-minority-rs-meta','s-lebanon-sexual-stigma']},
 {id:'spiritual-distress-grief',title:q('Manevi sıkıntı, yas ve ölçme','Spiritual distress, grief and measurement'),text:q('ICSG 2.0, onun Farsça uyarlaması ve P-SDS, manevi sıkıntının düşük manevi iyi oluşla aynı şey olmadığını gösteren farklı ölçme geleneklerini temsil etmektedir. Bir ölçeğin uyarlanması ile gruplar arasında karşılaştırılabilir olması ayrı ayrı değerlendirilir.','ICSG 2.0, its Persian adaptation and P-SDS represent distinct measurement traditions showing that spiritual distress is not identical to low spiritual wellbeing. Adaptation and invariance evidence remain separate.'),sourceIds:['s-icsg-2','s-icsg-2-fa','s-p-sds']},
 {id:'context-level-evidence',title:q('Kişisel puanların ötesinde dini bağlam','Religious context beyond individual scores'),text:q('Avrupa Sosyal Araştırması (ESS) verilerine dayanan çok düzeyli çalışma, dini azınlıkta olmak ile depresif duygular arasındaki ilişkiyi kişinin yaşadığı bölgenin özellikleriyle birlikte incelemektedir. Bu çalışma, bireysel başa çıkmayı inceleyen araştırmalardan farklı düzeyde bir çıkarım sunar.','The ESS-linked multilevel study examines religious-minority status and depressive feelings together with regional context. This is a different level of inference from individual coping studies.'),sourceIds:['s-religious-minority-context']}
];
export const claims=bridges.map(b=>({id:'bridge:'+b.id,sourceIds:b.sourceIds,support:'editorial-synthesis',reviewStatus:'AI_ASSISTED_DRAFT',checked:'2026-10-05'}));
