const common={checked:'2026-10-05',level:'V1',status:'PARTIALLY_VERIFIED',limit:'Bibliographic identity and the stated inspection scope were checked. Inclusion is not clinical endorsement, comprehensive risk-of-bias appraisal, permission to reproduce instrument items, or human scientific approval.'};
const S=(id,title,year,doi,pmid,kind,design,citation,access)=>({id,title,year,url:'https://doi.org/'+doi,citation,kind,language:'en',inspection:access.startsWith('Open full text')?'fulltext':'abstract',...common,access,bibliography:{type:'article',authors:[],date:String(year),journal:'',doi,pmid,identityVerified:true,collection:'research-roadmap'},roadmap:{design}});
export const sourcesC=[
 S('s-refugee-faith-coping','Faith-Based Coping Among Arabic-Speaking Refugees Seeking Mental Health Services in Berlin, Germany: An Exploratory Qualitative Study',2021,'10.3389/fpsyt.2021.595979','33633605','study','qualitative','Rayes, D., Karnouk, C., Churbaji, D., Walther, L., & Bajbouj, M. (2021). Faith-Based Coping Among Arabic-Speaking Refugees Seeking Mental Health Services in Berlin, Germany: An Exploratory Qualitative Study. Frontiers in Psychiatry, 12, 595979. https://doi.org/10.3389/fpsyt.2021.595979','Open full text inspected for abstract, methods, themes and limitations. Seventeen Arabic-speaking refugees seeking mental-health services in Berlin were interviewed; qualitative transferability is contextual.'),
 S('s-nonreligious-turkiye','Healthcare Experiences and Expectations of Atheists, Deists and Agnostics in Türkiye: A Qualitative Study of Mental Well-Being',2026,'10.1111/jpm.70148','42171513','study','qualitative','Soner, G., Güven, E., & Tunç, E. (2026). Healthcare Experiences and Expectations of Atheists, Deists and Agnostics in Türkiye: A Qualitative Study of Mental Well-Being. Journal of Psychiatric and Mental Health Nursing, 33(4), 715–730. https://doi.org/10.1111/jpm.70148','Open full text and PubMed record inspected. Descriptive phenomenology with 17 participants in Samsun; findings concern reported healthcare experiences and should not be generalised to all nonreligious people in Türkiye.'),
 S('s-religious-sexual-stigma','Religious-Based Sexual Stigma and Psychological Health: Roles of Internalization, Religious Struggle, and Religiosity',2020,'10.1080/00918369.2019.1601439','31017532','study','cross-sectional','Szymanski, D. M., & Carretta, R. F. (2020). Religious-Based Sexual Stigma and Psychological Health: Roles of Internalization, Religious Struggle, and Religiosity. Journal of Homosexuality, 67(8), 1062–1080. https://doi.org/10.1080/00918369.2019.1601439','PubMed bibliographic record and abstract inspected. The study examines enacted religious-based sexual stigma, internalized heterosexism, religious struggle and psychological outcomes; context and design limit causal inference.')
];
const authors={
 's-refugee-faith-coping':['Diana Rayes','Carine Karnouk','Dana Churbaji','Lena Walther','Malek Bajbouj'],
 's-nonreligious-turkiye':['Güven Soner','Emel Güven','Ercan Tunç'],
 's-religious-sexual-stigma':['Dawn M. Szymanski','Rachel F. Carretta']
};
const journals={'s-refugee-faith-coping':'Frontiers in Psychiatry','s-nonreligious-turkiye':'Journal of Psychiatric and Mental Health Nursing','s-religious-sexual-stigma':'Journal of Homosexuality'};
for(const s of sourcesC){s.bibliography.authors=authors[s.id];s.bibliography.journal=journals[s.id];}
