import {locales} from './languages.mjs';
export const C=(...values)=>{if(values.length!==8||values.some(x=>typeof x!=='string'||!x.trim()))throw new Error('Eight explicit translations required');return Object.fromEntries(locales.map((l,i)=>[l,values[i]]));};
const rows={
 university:C('Marmara Üniversitesi','Marmara University','Marmara Universität','马尔马拉大学','Университет Мармара','جامعة مرمرة','Universitas Marmara','Universiti Marmara'),
 preview:C('Marmara Üniversitesi için kurumsal web taslağı','Institutional website proposal for Marmara University','Institutioneller Webentwurf für die Marmara Universität','马尔马拉大学机构网站提案','Проект институционального сайта для Университета Мармара','تصور موقع مؤسسي لجامعة مرمرة','Rancangan situs institusional untuk Universitas Marmara','Cadangan laman institusi untuk Universiti Marmara'),
 status:C('Marmara Üniversitesi bünyesinde planlanan MARSAM için hazırlanmış dijital taslaktır. Kuruluş ve resmî yayın onayı yerine geçmez.','A digital proposal for MARSAM, planned within Marmara University. This is not formal establishment or institutional publication approval.','Digitaler Entwurf für das an der Marmara Universität geplante MARSAM. Keine formale Gründung oder institutionelle Publikationsfreigabe.','为计划设于马尔马拉大学的 MARSAM 制作的数字提案，不代表正式成立或机构发布批准。','Цифровой проект MARSAM, планируемого в составе Университета Мармара. Не означает официального учреждения или одобрения публикации.','تصور رقمي لمركز MARSAM المزمع إنشاؤه ضمن جامعة مرمرة. لا يمثل قرار تأسيس أو موافقة مؤسسية على النشر.','Rancangan digital MARSAM yang direncanakan di lingkungan Universitas Marmara. Bukan keputusan pendirian atau persetujuan publikasi institusi.','Cadangan digital MARSAM yang dirancang di bawah Universiti Marmara. Bukan pengesahan penubuhan atau kelulusan penerbitan institusi.'),
 heroLead:C('Araştırmayı, danışanın anlam dünyasını ve mesleki uygulamayı aynı bilgi alanında buluşturan akademik kaynak platformu.','An academic resource platform connecting research, the client’s world of meaning and professional practice.','Eine akademische Ressourcenplattform für Forschung, die Sinnwelt der Klient:innen und berufliche Praxis.','连接研究、来访者意义世界与专业实践的学术资源平台。','Академическая платформа, объединяющая исследования, мир смыслов клиента и профессиональную практику.','منصة موارد أكاديمية تجمع البحث وعالم المعنى لدى المستفيد والممارسة المهنية.','Platform sumber akademik yang menghubungkan penelitian, dunia makna klien, dan praktik profesional.','Platform sumber akademik yang menghubungkan penyelidikan, dunia makna klien dan amalan profesional.'),
 collections:C('Tematik koleksiyonlar','Thematic collections','Thematische Sammlungen','主题合集','Тематические коллекции','مجموعات موضوعية','Koleksi tematik','Koleksi bertema'),
 collectionLead:C('Bir sorudan başlayın. İlgili okumayı, dayanak kaynağı ve yöntem tartışmasını birlikte bulun.','Begin with a question. Find its readings, sources and methodological discussion together.','Mit einer Frage beginnen. Lektüre, Quellen und methodische Diskussion gemeinsam finden.','从问题出发，同时找到相关阅读、依据与方法讨论。','Начните с вопроса. Найдите вместе тексты, источники и обсуждение методов.','ابدأ بسؤال، ثم اجمع القراءات والمصادر والنقاش المنهجي المرتبط به.','Mulai dari pertanyaan. Temukan bacaan, sumber, dan pembahasan metodologinya bersama.','Mulakan dengan soalan. Temui bacaan, sumber dan perbincangan kaedah yang berkaitan.'),
 compare:C('Kaynakları karşılaştır','Compare sources','Quellen vergleichen','比较来源','Сравнить источники','مقارنة المصادر','Bandingkan sumber','Bandingkan sumber'),
 compareLead:C('En fazla dört kaynağı tür, kapsam ve inceleme sınırı bakımından yan yana okuyun. Bu görünüm bir etkililik sıralaması değildir.','Read up to four sources side by side by type, scope and inspection limits. This is not an efficacy ranking.','Bis zu vier Quellen nach Typ, Umfang und Prüfgrenzen vergleichen. Keine Wirksamkeitsrangliste.','按类型、范围及核查局限并列阅读最多四个来源，不构成疗效排名。','Сопоставляйте до четырёх источников по типу, охвату и границам проверки. Это не рейтинг эффективности.','اقرأ حتى أربعة مصادر جنباً إلى جنب بحسب النوع والنطاق وحدود الفحص. ليست هذه مرتبة للفعالية.','Baca hingga empat sumber berdampingan menurut jenis, cakupan, dan batas pemeriksaan. Bukan peringkat efektivitas.','Bandingkan sehingga empat sumber mengikut jenis, skop dan batas semakan. Bukan pemeringkatan keberkesanan.'),
 compareAdd:C('Karşılaştırmaya ekle','Add to comparison','Zum Vergleich hinzufügen','加入比较','Добавить к сравнению','إضافة للمقارنة','Tambahkan ke perbandingan','Tambah untuk perbandingan'),
 compareAdded:C('Karşılaştırmada','In comparison','Im Vergleich','已加入比较','В сравнении','ضمن المقارنة','Dalam perbandingan','Dalam perbandingan'),
 compareLimit:C('En fazla dört kaynak seçilebilir.','Select no more than four sources.','Höchstens vier Quellen auswählen.','最多选择四个来源。','Можно выбрать не более четырёх источников.','يمكن اختيار أربعة مصادر كحد أقصى.','Pilih maksimal empat sumber.','Pilih maksimum empat sumber.'),
 choose:C('Kaynak seçin','Select a source','Quelle auswählen','选择来源','Выберите источник','اختر مصدراً','Pilih sumber','Pilih sumber'),
 none:C('Seçilmedi','Not selected','Nicht ausgewählt','未选择','Не выбрано','غير محدد','Belum dipilih','Belum dipilih'),
 selected:C('Seçilen kaynaklar','Selected sources','Ausgewählte Quellen','已选来源','Выбранные источники','المصادر المختارة','Sumber terpilih','Sumber terpilih'),
 export:C('Karşılaştırmayı JSON indir','Download comparison JSON','Vergleich als JSON herunterladen','下载比较 JSON','Скачать сравнение JSON','تنزيل المقارنة بصيغة JSON','Unduh JSON perbandingan','Muat turun JSON perbandingan'),
 share:C('Bu karşılaştırmanın bağlantısı','Link to this comparison','Link zu diesem Vergleich','此比较的链接','Ссылка на это сравнение','رابط هذه المقارنة','Tautan perbandingan ini','Pautan perbandingan ini'),
 events:C('Etkinlik takvimi','Events calendar','Veranstaltungskalender','活动日历','Календарь событий','تقويم الفعاليات','Kalender kegiatan','Kalendar acara'),
 eventsLead:C('Dış kurumların tarihli etkinlikleri. Kayıt, ücret ve program koşulları için düzenleyicinin sayfasına gidin. Bunlar MARSAM etkinlikleri değildir.','Dated events from external institutions. Check registration, fees and program conditions with the organizer. These are not MARSAM events.','Terminierte Veranstaltungen externer Einrichtungen. Anmeldung, Kosten und Bedingungen beim Veranstalter prüfen. Keine MARSAM-Veranstaltungen.','外部机构的定期活动。报名、费用及安排须向主办方核实，这些并非 MARSAM 活动。','События внешних организаций. Условия регистрации, оплаты и программы уточняйте у организатора. Это не события MARSAM.','فعاليات مؤسسات خارجية ذات مواعيد محددة. تحقق من التسجيل والرسوم والبرنامج لدى المنظم. ليست فعاليات MARSAM.','Kegiatan bertanggal dari institusi eksternal. Periksa pendaftaran, biaya, dan ketentuan pada penyelenggara. Bukan kegiatan MARSAM.','Acara bertarikh institusi luar. Semak pendaftaran, yuran dan syarat dengan penganjur. Ini bukan acara MARSAM.'),
 upcoming:C('Yaklaşan','Upcoming','Bevorstehend','即将举行','Предстоящие','قادمة','Mendatang','Akan datang'),
 past:C('Arşiv','Archive','Archiv','历史活动','Архив','الأرشيف','Arsip','Arkib'),
 today:C('Bugün','Today','Heute','今天','Сегодня','اليوم','Hari ini','Hari ini'),
 organizer:C('Düzenleyici','Organizer','Veranstalter','主办方','Организатор','المنظم','Penyelenggara','Penganjur'),
 agenda:C('Tarihi görmek, kaydın açık olduğu anlamına gelmez.','A displayed date does not mean registration is open.','Ein Datum bedeutet nicht, dass die Anmeldung geöffnet ist.','显示日期并不表示报名仍然开放。','Наличие даты не означает, что регистрация открыта.','ظهور الموعد لا يعني أن التسجيل مفتوح.','Tanggal yang tercantum tidak berarti pendaftaran masih dibuka.','Tarikh dipaparkan tidak bermaksud pendaftaran masih dibuka.'),
 sourceFirst:C('Kaynakla başlayan keşif','Discovery begins with a source','Entdeckung beginnt mit einer Quelle','探索始于来源','Поиск начинается с источника','الاستكشاف يبدأ بالمصدر','Penelusuran dimulai dari sumber','Penerokaan bermula dengan sumber'),
 reviewNote:C('Kaynak, yorum ve öneri ayrı gösterilir.','Sources, interpretations and proposals are kept distinct.','Quellen, Deutungen und Vorschläge bleiben getrennt.','分别呈现来源、解释与建议。','Источники, интерпретации и предложения разделены.','تُعرض المصادر والتفسيرات والمقترحات بصورة منفصلة.','Sumber, interpretasi, dan usulan ditampilkan terpisah.','Sumber, tafsiran dan cadangan dipaparkan berasingan.'),
 viewCollection:C('Koleksiyonu incele','Explore collection','Sammlung ansehen','查看合集','Открыть коллекцию','استكشاف المجموعة','Jelajahi koleksi','Terokai koleksi'),
 tools:C('Araştırmacının çalışma alanı','A researcher’s workspace','Arbeitsbereich für Forschende','研究者工作区','Рабочее пространство исследователя','مساحة عمل الباحث','Ruang kerja peneliti','Ruang kerja penyelidik'),
 toolsLead:C('Biriktirmekten karşılaştırmaya. Okuma listesini oluşturun, kaynakların farklarını görün, atıfları dışa aktarın.','Move from collecting to comparing. Build a reading list, inspect differences and export citations.','Vom Sammeln zum Vergleichen. Leseliste erstellen, Unterschiede prüfen und Zitationen exportieren.','从收集走向比较。建立阅读清单，核查差异并导出引文。','От сбора к сравнению. Составляйте список, изучайте различия и экспортируйте ссылки.','من التجميع إلى المقارنة. أنشئ قائمة قراءة وافحص الفروق وصدّر الاستشهادات.','Dari mengumpulkan menuju membandingkan. Susun daftar baca, periksa perbedaan, dan ekspor sitasi.','Daripada mengumpul kepada membanding. Bina senarai bacaan, semak perbezaan dan eksport sitasi.'),
 institutionalTitle:C('Marmara Üniversitesi için planlanan merkez','A center planned within Marmara University','Ein an der Marmara Universität geplantes Zentrum','计划设于马尔马拉大学的中心','Центр, планируемый в составе Университета Мармара','مركز مزمع ضمن جامعة مرمرة','Pusat yang direncanakan di Universitas Marmara','Pusat yang dirancang di Universiti Marmara'),
 institutionalBody:C('MARSAM, Marmara Üniversitesi bünyesinde maneviyat ve ruh sağlığı araştırmalarını, mesleki öğrenmeyi ve kaynak paylaşımını bir araya getirecek merkez olarak planlanmaktadır. Bu web taslağı söz konusu kurumsal hedefi temel alır. Resmî kuruluş kararı, yönetim atamaları ve üniversite alan adındaki yayın süreci bu taslaktan ayrı kurumsal işlemlerdir.','MARSAM is planned as a center within Marmara University connecting spirituality and mental health research, professional learning and resource sharing. This website proposal follows that institutional objective. Formal establishment, governance appointments and publication on a university domain remain separate institutional actions.','MARSAM ist als Zentrum der Marmara Universität für Spiritualität, psychische Gesundheit, berufliches Lernen und Ressourcenaustausch geplant. Der Webentwurf folgt diesem Ziel. Gründungsentscheidung, Leitungsbestellung und Veröffentlichung auf einer Hochschuldomain sind gesonderte institutionelle Schritte.','MARSAM 计划设于马尔马拉大学，汇集灵性与心理健康研究、专业学习与资源共享。本网站提案以此机构目标为基础。正式成立、管理任命及大学域名发布仍属于独立的机构程序。','MARSAM планируется как центр Университета Мармара для исследований духовности и психического здоровья, обучения и обмена ресурсами. Проект следует этой цели. Официальное учреждение, назначение руководства и публикация на домене университета остаются отдельными процедурами.','يُخطط لإنشاء MARSAM ضمن جامعة مرمرة للجمع بين أبحاث الروحانية والصحة النفسية والتعلم المهني وتبادل الموارد. يستند التصور إلى هذا الهدف. ويبقى التأسيس الرسمي وتعيين الإدارة والنشر ضمن نطاق الجامعة إجراءات مؤسسية مستقلة.','MARSAM direncanakan sebagai pusat di Universitas Marmara yang menghubungkan penelitian spiritualitas dan kesehatan mental, pembelajaran profesional, serta berbagi sumber. Rancangan ini mengikuti tujuan institusional tersebut. Pendirian resmi, penunjukan pengelola, dan publikasi pada domain universitas merupakan proses tersendiri.','MARSAM dirancang sebagai pusat di bawah Universiti Marmara yang menghubungkan penyelidikan kerohanian dan kesihatan mental, pembelajaran profesional serta perkongsian sumber. Cadangan ini berasaskan tujuan institusi tersebut. Penubuhan rasmi, pelantikan pentadbiran dan penerbitan pada domain universiti ialah proses berasingan.'),
 committeeNote:C('Kurumsal yapılanma ve yayın sorumluları resmî olarak belirlendiğinde bu alan güncellenecektir. Bu önizlemede yönetici, kurul üyesi, adres veya kurumsal e-posta atanmamıştır.','This area will be updated when institutional governance and publishing responsibilities are formally assigned. No director, board member, address or institutional email is assigned in this preview.','Aktualisierung nach formaler Festlegung der Leitung und Publikationsverantwortung. In dieser Vorschau werden keine Leitung, Beiratsmitglieder, Anschrift oder institutionelle E-Mail bestimmt.','正式确定治理与出版责任后将更新此处。本预览未指定主任、委员会成员、地址或机构邮箱。','Раздел обновится после официального определения управления и ответственности за публикации. Директор, совет, адрес и корпоративная почта здесь не назначаются.','يُحدّث هذا القسم بعد تحديد الإدارة ومسؤوليات النشر رسمياً. لا يعيّن التصور مديراً أو أعضاء مجلس أو عنواناً أو بريداً مؤسسياً.','Bagian ini diperbarui setelah tata kelola dan tanggung jawab publikasi ditetapkan resmi. Pratinjau ini tidak menunjuk direktur, anggota dewan, alamat, atau surel institusi.','Bahagian ini dikemas kini selepas tadbir urus dan tanggungjawab penerbitan ditetapkan secara rasmi. Tiada pengarah, ahli lembaga, alamat atau e-mel institusi ditetapkan di sini.')
};
export const campusCopy=Object.fromEntries(locales.map(l=>[l,Object.fromEntries(Object.entries(rows).map(([k,v])=>[k,v[l]]))]));
export const campusRows=rows;
