import {locales} from './languages.mjs';
export const C=(...values)=>{if(values.length!==8||values.some(x=>typeof x!=='string'||!x.trim()))throw new Error('Eight explicit translations required');return Object.fromEntries(locales.map((l,i)=>[l,values[i]]));};
const rows={
 university:C('Marmara Üniversitesi','Marmara University','Marmara Universität','马尔马拉大学','Университет Мармара','جامعة مرمرة','Universitas Marmara','Universiti Marmara'),
 preview:C('Marmara Üniversitesi · Kurumsal web sitesi','Marmara University · Institutional website','Marmara Universität · Institutionelle Website','马尔马拉大学 · 机构网站','Университет Мармара · Институциональный сайт','جامعة مرمرة · الموقع المؤسسي','Universitas Marmara · Situs institusional','Universiti Marmara · Laman institusi'),
 status:C('Marmara Üniversitesi bünyesinde maneviyat ve ruh sağlığı araştırmalarına, mesleki öğrenmeye ve kaynak paylaşımına odaklanan araştırma merkezi.','A research center at Marmara University dedicated to spirituality and mental health research, professional learning and resource sharing.','Forschungszentrum der Marmara-Universität für Forschung zu Spiritualität und psychischer Gesundheit, berufliches Lernen und Ressourcenaustausch.','马尔马拉大学下属研究中心，专注于灵性与心理健康研究、专业学习与资源共享。','Исследовательский центр Университета Мармара, посвящённый исследованиям духовности и психического здоровья, профессиональному обучению и обмену ресурсами.','مركز بحثي في جامعة مرمرة يُعنى بأبحاث الروحانية والصحة النفسية والتعلم المهني وتبادل الموارد.','Pusat penelitian di Universitas Marmara yang berfokus pada penelitian spiritualitas dan kesehatan mental, pembelajaran profesional, serta berbagi sumber.','Pusat penyelidikan di bawah Universiti Marmara yang memberi tumpuan kepada penyelidikan kerohanian dan kesihatan mental, pembelajaran profesional serta perkongsian sumber.'),
 heroLead:C('Araştırmayı, danışanın anlam dünyasını ve mesleki uygulamayı aynı bilgi alanında buluşturan akademik kaynak platformu.','An academic resource platform connecting research, the client’s world of meaning and professional practice.','Eine akademische Ressourcenplattform für Forschung, die Sinnwelt der Klient:innen und berufliche Praxis.','连接研究、来访者意义世界与专业实践的学术资源平台。','Академическая платформа, объединяющая исследования, мир смыслов клиента и профессиональную практику.','منصة موارد أكاديمية تجمع البحث وعالم المعنى لدى المستفيد والممارسة المهنية.','Platform sumber akademik yang menghubungkan penelitian, dunia makna klien, dan praktik profesional.','Platform sumber akademik yang menghubungkan penyelidikan, dunia makna klien dan amalan profesional.'),
 collections:C('Tematik koleksiyonlar','Thematic collections','Thematische Sammlungen','主题合集','Тематические коллекции','مجموعات موضوعية','Koleksi tematik','Koleksi bertema'),
 collectionLead:C('Bir sorudan başlayın. İlgili okumayı, dayanak kaynağı ve yöntem tartışmasını birlikte bulun.','Begin with a question. Find its readings, sources and methodological discussion together.','Mit einer Frage beginnen. Lektüre, Quellen und methodische Diskussion gemeinsam finden.','从问题出发，同时找到相关阅读、依据与方法讨论。','Начните с вопроса. Найдите вместе тексты, источники и обсуждение методов.','ابدأ بسؤال، ثم اجمع القراءات والمصادر والنقاش المنهجي المرتبط به.','Mulai dari pertanyaan. Temukan bacaan, sumber, dan pembahasan metodologinya bersama.','Mulakan dengan soalan. Temui bacaan, sumber dan perbincangan kaedah yang berkaitan.'),
 compare:C('Kaynakları karşılaştırın','Compare sources','Quellen vergleichen','比较来源','Сравнить источники','مقارنة المصادر','Bandingkan sumber','Bandingkan sumber'),
 compareLead:C('En fazla dört kaynağı tür, kapsam ve inceleme sınırı bakımından yan yana okuyun. Bu görünüm bir etkililik sıralaması değildir.','Read up to four sources side by side by type, scope and inspection limits. This is not an efficacy ranking.','Bis zu vier Quellen nach Typ, Umfang und Prüfgrenzen vergleichen. Keine Wirksamkeitsrangliste.','按类型、范围及核查局限并列阅读最多四个来源，不构成疗效排名。','Сопоставляйте до четырёх источников по типу, охвату и границам проверки. Это не рейтинг эффективности.','اقرأ حتى أربعة مصادر جنباً إلى جنب بحسب النوع والنطاق وحدود الفحص. ليست هذه مرتبة للفعالية.','Baca hingga empat sumber berdampingan menurut jenis, cakupan, dan batas pemeriksaan. Bukan peringkat efektivitas.','Bandingkan sehingga empat sumber mengikut jenis, skop dan batas semakan. Bukan pemeringkatan keberkesanan.'),
 compareAdd:C('Karşılaştırmaya ekleyin','Add to comparison','Zum Vergleich hinzufügen','加入比较','Добавить к сравнению','إضافة للمقارنة','Tambahkan ke perbandingan','Tambah untuk perbandingan'),
 compareAdded:C('Karşılaştırmada','In comparison','Im Vergleich','已加入比较','В сравнении','ضمن المقارنة','Dalam perbandingan','Dalam perbandingan'),
 compareLimit:C('En fazla dört kaynak seçilebilir.','Select no more than four sources.','Höchstens vier Quellen auswählen.','最多选择四个来源。','Можно выбрать не более четырёх источников.','يمكن اختيار أربعة مصادر كحد أقصى.','Pilih maksimal empat sumber.','Pilih maksimum empat sumber.'),
 choose:C('Kaynak seçin','Select a source','Quelle auswählen','选择来源','Выберите источник','اختر مصدراً','Pilih sumber','Pilih sumber'),
 none:C('Seçilmedi','Not selected','Nicht ausgewählt','未选择','Не выбрано','غير محدد','Belum dipilih','Belum dipilih'),
 selected:C('Seçilen kaynaklar','Selected sources','Ausgewählte Quellen','已选来源','Выбранные источники','المصادر المختارة','Sumber terpilih','Sumber terpilih'),
 export:C('Karşılaştırmayı JSON olarak indir','Download comparison JSON','Vergleich als JSON herunterladen','下载比较 JSON','Скачать сравнение JSON','تنزيل المقارنة بصيغة JSON','Unduh JSON perbandingan','Muat turun JSON perbandingan'),
 share:C('Bu karşılaştırmanın bağlantısı','Link to this comparison','Link zu diesem Vergleich','此比较的链接','Ссылка на это сравнение','رابط هذه المقارنة','Tautan perbandingan ini','Pautan perbandingan ini'),
 events:C('Etkinlik takvimi','Events calendar','Veranstaltungskalender','活动日历','Календарь событий','تقويم الفعاليات','Kalender kegiatan','Kalendar acara'),
 eventsLead:C('Dış kurumların tarihli etkinlikleri. Kayıt, ücret ve program koşulları için düzenleyicinin sayfasına gidin. Bunlar MARSAM etkinlikleri değildir.','Dated events from external institutions. Check registration, fees and program conditions with the organizer. These are not MARSAM events.','Terminierte Veranstaltungen externer Einrichtungen. Anmeldung, Kosten und Bedingungen beim Veranstalter prüfen. Keine MARSAM-Veranstaltungen.','外部机构的定期活动。报名、费用及安排须向主办方核实，这些并非 MARSAM 活动。','События внешних организаций. Условия регистрации, оплаты и программы уточняйте у организатора. Это не события MARSAM.','فعاليات مؤسسات خارجية ذات مواعيد محددة. تحقق من التسجيل والرسوم والبرنامج لدى المنظم. ليست فعاليات MARSAM.','Kegiatan bertanggal dari institusi eksternal. Periksa pendaftaran, biaya, dan ketentuan pada penyelenggara. Bukan kegiatan MARSAM.','Acara bertarikh institusi luar. Semak pendaftaran, yuran dan syarat dengan penganjur. Ini bukan acara MARSAM.'),
 upcoming:C('Yaklaşan','Upcoming','Bevorstehend','即将举行','Предстоящие','قادمة','Mendatang','Akan datang'),
 past:C('Arşiv','Archive','Archiv','历史活动','Архив','الأرشيف','Arsip','Arkib'),
 today:C('Bugün','Today','Heute','今天','Сегодня','اليوم','Hari ini','Hari ini'),
 organizer:C('Düzenleyici','Organizer','Veranstalter','主办方','Организатор','المنظم','Penyelenggara','Penganjur'),
 agenda:C('Tarihi görmek, kaydın açık olduğu anlamına gelmez.','A displayed date does not mean registration is open.','Ein Datum bedeutet nicht, dass die Anmeldung geöffnet ist.','显示日期并不表示报名仍然开放。','Наличие даты не означает, что регистрация открыта.','ظهور الموعد لا يعني أن التسجيل مفتوح.','Tanggal yang tercantum tidak berarti pendaftaran masih dibuka.','Tarikh dipaparkan tidak bermaksud pendaftaran masih dibuka.'),
 sourceFirst:C('Kaynakla başlayan keşif','Discovery begins with a source','Entdeckung beginnt mit einer Quelle','探索始于来源','Поиск начинается с источника','الاستكشاف يبدأ بالمصدر','Penelusuran dimulai dari sumber','Penerokaan bermula dengan sumber'),
 reviewNote:C('Kaynak, yorum ve öneri ayrı gösterilir.','Sources, interpretations and proposals are kept distinct.','Quellen, Deutungen und Vorschläge bleiben getrennt.','分别呈现来源、解释与建议。','Источники, интерпретации и предложения разделены.','تُعرض المصادر والتفسيرات والمقترحات بصورة منفصلة.','Sumber, interpretasi, dan usulan ditampilkan terpisah.','Sumber, tafsiran dan cadangan dipaparkan berasingan.'),
 viewCollection:C('Koleksiyonu incele','Explore collection','Sammlung ansehen','查看合集','Открыть коллекцию','استكشاف المجموعة','Jelajahi koleksi','Terokai koleksi'),
 tools:C('Araştırmacının çalışma alanı','A researcher’s workspace','Arbeitsbereich für Forschende','研究者工作区','Рабочее пространство исследователя','مساحة عمل الباحث','Ruang kerja peneliti','Ruang kerja penyelidik'),
 toolsLead:C('Biriktirmekten karşılaştırmaya. Okuma listesini oluşturun, kaynakların farklarını görün, atıfları dışa aktarın.','Move from collecting to comparing. Build a reading list, inspect differences and export citations.','Vom Sammeln zum Vergleichen. Leseliste erstellen, Unterschiede prüfen und Zitationen exportieren.','从收集走向比较。建立阅读清单，核查差异并导出引文。','От сбора к сравнению. Составляйте список, изучайте различия и экспортируйте ссылки.','من التجميع إلى المقارنة. أنشئ قائمة قراءة وافحص الفروق وصدّر الاستشهادات.','Dari mengumpulkan menuju membandingkan. Susun daftar baca, periksa perbedaan, dan ekspor sitasi.','Daripada mengumpul kepada membanding. Bina senarai bacaan, semak perbezaan dan eksport sitasi.'),
 institutionalTitle:C('Marmara Üniversitesi bünyesinde bir araştırma merkezi','A research center at Marmara University','Ein Forschungszentrum an der Marmara-Universität','马尔马拉大学的研究中心','Исследовательский центр в составе Университета Мармара','مركز بحثي ضمن جامعة مرمرة','Pusat penelitian di Universitas Marmara','Pusat penyelidikan di Universiti Marmara'),
 institutionalBody:C('MARSAM, Marmara Üniversitesi bünyesinde maneviyat ve ruh sağlığı araştırmalarını, mesleki öğrenmeyi ve kaynak paylaşımını bir araya getiren bir merkezdir. Bu web sitesi, merkezin bu amaç doğrultusundaki çalışmalarını ve kaynaklarını ziyaretçilerle paylaşır.','MARSAM is a center within Marmara University that brings together spirituality and mental health research, professional learning and resource sharing. This website presents the center’s work and resources in line with that objective.','MARSAM ist ein Zentrum der Marmara-Universität, das Forschung zu Spiritualität und psychischer Gesundheit, berufliches Lernen und Ressourcenaustausch zusammenführt. Diese Website stellt die Arbeit und die Ressourcen des Zentrums im Sinne dieses Ziels vor.','MARSAM 是马尔马拉大学下属的中心，汇集灵性与心理健康研究、专业学习与资源共享。本网站围绕这一目标介绍中心的工作与资源。','MARSAM — центр Университета Мармара, объединяющий исследования духовности и психического здоровья, профессиональное обучение и обмен ресурсами. Сайт представляет работу и ресурсы центра в соответствии с этой целью.','MARSAM مركز ضمن جامعة مرمرة يجمع بين أبحاث الروحانية والصحة النفسية والتعلم المهني وتبادل الموارد. ويعرض هذا الموقع أعمال المركز وموارده انطلاقاً من هذا الهدف.','MARSAM adalah pusat di Universitas Marmara yang menghubungkan penelitian spiritualitas dan kesehatan mental, pembelajaran profesional, serta berbagi sumber. Situs ini menyajikan kegiatan dan sumber daya pusat sejalan dengan tujuan tersebut.','MARSAM ialah pusat di bawah Universiti Marmara yang menghubungkan penyelidikan kerohanian dan kesihatan mental, pembelajaran profesional serta perkongsian sumber. Laman ini memaparkan kerja dan sumber pusat selaras dengan tujuan tersebut.'),
 committeeNote:C('Merkezin çalışmaları Marmara Üniversitesi Atatürk Eğitim Fakültesi, Eğitim Bilimleri Bölümü, Rehberlik ve Psikolojik Danışmanlık Anabilim Dalı bünyesinde yürütülür.','The center’s work is carried out within the Division of Guidance and Psychological Counseling, Department of Educational Sciences, Atatürk Faculty of Education, Marmara University.','Die Arbeit des Zentrums ist im Arbeitsbereich Orientierung und psychologische Beratung der Abteilung Erziehungswissenschaften an der Atatürk-Fakultät für Pädagogik der Marmara-Universität angesiedelt.','本中心的工作依托马尔马拉大学阿塔图尔克教育学院教育科学系指导与心理咨询专业开展。','Работа центра ведётся на кафедре психологического консультирования и сопровождения отделения педагогических наук Педагогического факультета имени Ататюрка Университета Мармара.','تُنفَّذ أعمال المركز ضمن قسم التوجيه والإرشاد النفسي، شعبة العلوم التربوية، كلية أتاتورك للتربية، جامعة مرمرة.','Kegiatan pusat dijalankan di Program Studi Bimbingan dan Konseling Psikologis, Departemen Ilmu Pendidikan, Fakultas Pendidikan Atatürk, Universitas Marmara.','Kerja pusat dijalankan di bawah Bahagian Bimbingan dan Kaunseling Psikologi, Jabatan Sains Pendidikan, Fakulti Pendidikan Atatürk, Universiti Marmara.')
};
export const campusCopy=Object.fromEntries(locales.map(l=>[l,Object.fromEntries(Object.entries(rows).map(([k,v])=>[k,v[l]]))]));
export const campusRows=rows;
