/** Marmara institutional preview composition. Original source claims are not upgraded. */
import {locales,labels,langTags,sourceNotes} from './i18n.mjs';
import {sources,resources,sections,topics,typeKeys} from './content.mjs';
import {articles} from './articles.mjs';
import {overview,learningPaths} from './info.mjs';
import {shell,icon,sourceById,dossierCard,resourceCard,articleURL,resourceURL} from './site.mjs';
import {escapeHTML as e,route,safeURL} from './lib.mjs';
import {campusCopy,campusRows as cr,C} from './campus-copy.mjs';
import {institutions,collections,events} from './campus-data.mjs';
import {parseSelection,eventState} from '../public/campus-core.js';
export {campusCopy,institutions,collections,events,parseSelection,eventState};
const scopes=C('İçerik özeti','Content summary','Inhaltsübersicht','内容摘要','Краткое содержание','ملخص المحتوى','Ringkasan isi','Ringkasan kandungan');
for(const l of locales)campusCopy[l].scope=scopes[l];
// The institutional relationship is a user-supplied project objective, not formal legal status.
for(const l of locales){Object.assign(labels[l],{preview:campusCopy[l].preview,previewNote:campusCopy[l].status,heroText:campusCopy[l].heroLead,collections:campusCopy[l].collections,compare:campusCopy[l].compare,events:campusCopy[l].events});}
overview.about[0]={title:cr.institutionalTitle,text:cr.institutionalBody};
overview.about[3].text=cr.committeeNote;
for(const x of institutions.filter(x=>['smbi','iapr'].includes(x.id))){
 const sid='s-'+x.id;
 if(!sources.some(s=>s.id===sid)){
  const s={id:sid,title:x.name,year:null,url:x.links[0][1],citation:`${x.name}. (n.d.). Official institutional website. Accessed 2026-10-01.`,kind:'hub',inspection:'official',checked:'2026-10-01',level:'V1',status:'PARTIALLY_VERIFIED',access:'Official home page and linked research, education, journal or conference pages inspected. Browser snapshots recorded for the home and a key internal page.',limit:'Institutional self-description is not trial evidence, partnership, endorsement or exhaustive evaluation of associated publications.'};
  sources.push(s);sourceById[sid]=s;
  resources.push({id:x.record,title:C(...locales.map(()=>x.name)),summary:x.summary,sections:['library','network','media'],topic:'network',sources:[sid],kind:'hub',review:'draft',translation:'draft',rights:'link-only',approval:null});
 }
}
for(const id of ['collections','compare','events'])if(!sections.some(s=>s.id===id))sections.push({id,title:cr[id],summary:cr[id==='collections'?'collectionLead':id==='compare'?'compareLead':'eventsLead'],group:id==='events'?'center':'research',topic:id==='events'?'network':'methods'});
const ext=(url,title,cls='text-link')=>`<a href="${e(safeURL(url)||'')}" class="${cls}" target="_blank" rel="noopener noreferrer">${e(title)} ${icon('external')}</a>`;
const link=(url,title,cls='text-link')=>`<a class="${cls}" href="${url}">${e(title)} ${icon('arrow')}</a>`;
const json=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const heading=(title,desc='',eyebrow='MARSAM')=>`<div class="section-heading"><div><span class="eyebrow">${e(eyebrow)}</span><h2>${e(title)}</h2>${desc?`<p>${e(desc)}</p>`:''}</div></div>`;
const intro=(l,title,text,b)=>`<div class="wide page-intro"><nav class="breadcrumbs" aria-label="${e(labels[l].home)}"><a href="${route(l,'',b)}">${e(labels[l].home)}</a><span aria-hidden="true">/</span><span>${e(title)}</span></nav><span class="eyebrow">MARSAM</span><h1>${e(title)}</h1><p class="page-deck">${e(text)}</p></div>`;
function compareButton(id,l){const c=campusCopy[l];return `<button type="button" class="compare-toggle" data-compare-id="${e(id)}" aria-pressed="false" title="${e(c.compareAdd)}">${icon('layers')}<span>${e(c.compareAdd)}</span></button>`;}
export function comparisonRows(items,l){return items.map(r=>{const s=sourceById[r.sources[0]];return {id:r.id,title:r.title[l],summary:r.summary[l],type:labels[l][typeKeys[s.kind]],citation:s.citation,inspection:labels[l][s.inspection==='official'?'officialPage':s.inspection==='metadata'?'metadataOnly':'abstractOnly'],limit:sourceNotes[s.id]?.[l]||labels[l].verificationNote,rights:s.id==='s-fica'?r.summary[l]:s.id==='s-flourish'?sourceNotes[s.id][l]:labels[l].rightsNote,review:`${s.level} / ${s.status}`,checked:s.checked,url:s.url};});}
function networkCards(l,b,compact=false){const c=campusCopy[l],t=labels[l];return `<div class="institution-grid ${compact?'compact':''}">${institutions.map((x,i)=>`<article class="institution-card"><div class="institution-card-top"><span class="institution-number">0${i+1}</span><span class="eyebrow">${e(x.type[l])}</span></div><h3 lang="en" dir="ltr">${e(x.name)}</h3><p>${e(x.summary[l])}</p><div class="institution-links">${x.links.map(([k,u])=>ext(u,c[k]||t[k])).join('')}</div>${link(resourceURL(l,x.record,b),t.viewRecord)}</article>`).join('')}</div>`;}
function collectionTiles(l,b){const t=labels[l],c=campusCopy[l];return `<div class="theme-grid">${collections.map((x,i)=>{const a=articles.find(a=>a.id===x.article);return `<a class="theme-tile" href="${route(l,'collections',b)}#${x.id}"><div class="tile-top"><span class="folio">0${i+1}</span>${icon(i%2?'book':'layers')}</div><h3>${e(topics[x.topic][l])}</h3><p>${e(a.prompt[l])}</p><span class="theme-bottom">${e(c.viewCollection)} ${icon('arrow')}</span></a>`;}).join('')}</div>`;}
export function renderCampusHome(l,b){const t=labels[l],c=campusCopy[l];
 const body=`<section class="campus-hero"><div class="wide campus-hero-grid"><div class="campus-hero-copy"><span class="eyebrow">${e(t.heroEyebrow)}</span><h1>${e(c.heroFirst)}<br><span>${e(c.heroSecond)}</span></h1><p>${e(c.heroLead)}</p><div class="hero-actions">${link(route(l,'library',b),t.browse,'button light')}${link(route(l,'learning',b),t.startLearning)}</div></div><aside class="hero-question"><span class="hero-question-index">01 <span>${e(c.question)}</span></span><h2>${e(c.heroQuestion)}</h2><p>${e(c.reviewNote)}</p>${link(articleURL(l,'understanding-spiritual-experience',b),t.readDossier)}<div class="question-foot"><span>${e(t.evidence)}</span><span>${e(t.meaning)}</span><span>${e(t.practice)}</span></div></aside></div></section>
 <div class="wide discovery-bar"><form action="${route(l,'search',b)}" method="get">${icon('search')}<label class="sr-only" for="hero-search">${e(t.searchLabel)}</label><input id="hero-search" type="search" name="q" placeholder="${e(t.searchLabel)}" maxlength="160" dir="auto"><button class="button" type="submit">${e(t.search)}</button></form><div class="discovery-links">${link(route(l,'measures',b),t.measures)}${link(route(l,'compare',b),c.compare)}</div></div>
 <section class="wide section"><div class="portal-introduction"><div><span class="eyebrow">${e(c.university)} · MARSAM</span><h2>${e(t.forYou)}</h2><p>${e(t.forYouIntro)}</p></div><div class="audience-routes">${learningPaths.map((p,i)=>`<a href="${route(l,`learning/${p.id}`,b)}"><span class="route-index">0${i+1}</span><div><h3>${e(t[p.audience])}</h3><p>${e(p.summary[l])}</p></div>${icon('arrow')}</a>`).join('')}</div></div></section>
 <section class="paper-section"><div class="wide section">${heading(c.collections,c.collectionLead)}${collectionTiles(l,b)}</div></section>
 <section class="wide section">${heading(t.readings,t.readingsIntro,t.ownSynthesis)}<div class="three-grid">${[articles[0],articles[1],articles[4]].map((a,i)=>dossierCard(a,l,b,i)).join('')}</div></section>
 <section class="research-desk"><div class="wide desk-layout"><div><span class="eyebrow">${e(c.sourceFirst)}</span><h2>${e(c.tools)}</h2><p>${e(c.toolsLead)}</p>${link(route(l,'compare',b),c.compare,'button')}</div><div class="desk-preview"><div class="desk-grid-head"><span>${e(t.sourceType)}</span><span>${e(t.sourceAccess)}</span><span>${e(t.limit)}</span></div>${['metaStudy','metaGuide','metaMeasure'].map((k,i)=>`<div class="desk-preview-row"><span>${e(t[k])}</span><span class="desk-line" aria-hidden="true"></span><span class="desk-line short" aria-hidden="true"></span></div>`).join('')}<p>${e(c.compareLead)}</p></div></div></section>
 <section class="wide section">${heading(c.institutionMap,c.mapLead,t.noAffiliationShort)}${networkCards(l,b,true)}<p class="network-disclaimer">${e(t.noAffiliation)}</p></section>
 <section class="wide section">${heading(t.selectedSources,t.selectedSourcesIntro,t.library)}<div class="source-list">${resources.slice(0,3).map(r=>resourceCard(r,l,b)).join('')}</div><div class="catalogue-actions">${link(route(l,'library',b),t.completeList)}<span>${resources.length} ${e(t.resources)} · ${articles.length} ${e(t.dossiers)} · ${locales.length} ${e(t.languages)}</span></div></section>
 <section class="wide section"><div class="campus-closing"><div><span class="eyebrow">${e(t.editorial)}</span><h2>${e(t.footerLine)}</h2><p>${e(c.status)}</p></div>${link(route(l,'editorial',b),t.readPolicy,'button')}</div></section>`;
 return shell(l,'',t.home,c.heroLead,body,b);
}
export function renderCollections(l,b){const c=campusCopy[l],t=labels[l];return shell(l,'collections',c.collections,c.collectionLead,intro(l,c.collections,c.collectionLead,b)+`<div class="wide section"><nav class="collection-jumps" aria-label="${e(c.collections)}">${collections.map(x=>`<a href="#${x.id}">${e(topics[x.topic][l])}</a>`).join('')}</nav>${collections.map((x,i)=>`<section class="collection-section" id="${x.id}">${heading(topics[x.topic][l],articles.find(a=>a.id===x.article).prompt[l],`0${i+1}`)}<div class="collection-columns"><div><h3 class="collection-label">${e(t.dossiers)}</h3>${x.readings.map(id=>{const a=articles.find(z=>z.id===id);return `<article class="collection-reading"><h3>${link(articleURL(l,id,b),a.title[l])}</h3><p>${e(a.summary[l])}</p></article>`;}).join('')}</div><div><h3 class="collection-label">${e(t.references)}</h3><div class="source-list">${x.resources.map(id=>resourceCard(resources.find(z=>z.id===id),l,b)).join('')}</div>${link(route(l,'compare',b)+'?ids='+x.resources.join(','),c.compare)}</div></div></section>`).join('')}</div>`,b);}
export function renderCompare(l,b){const c=campusCopy[l],t=labels[l];const rows=comparisonRows(resources,l);
 return shell(l,'compare',c.compare,c.compareLead,intro(l,c.compare,c.compareLead,b)+`<div class="wide section" data-compare-page><div class="notice">${icon('circle')}<p>${e(c.reviewNote)} ${e(t.verificationNote)}</p></div><form class="comparison-picker">${[1,2,3,4].map(i=>`<div><label for="compare-${i}">${e(c.choose)} ${i}</label><select id="compare-${i}" data-compare-slot><option value="">${e(c.none)}</option>${resources.map(r=>`<option value="${r.id}">${e(r.title[l])}</option>`).join('')}</select></div>`).join('')}</form><div class="comparison-actions"><a class="text-link" data-comparison-share href="${route(l,'compare',b)}">${e(c.share)} ${icon('external')}</a><button type="button" class="button secondary" data-comparison-export>${e(c.export)}</button></div><div data-compare-results aria-live="polite"></div><noscript><div class="source-list">${resources.slice(0,4).map(r=>resourceCard(r,l,b)).join('')}</div><p>${e(t.needsJS)}</p></noscript><script type="application/json" data-comparison-records>${json(rows)}</script></div>`,b);
}
export function renderEvents(l,b){const c=campusCopy[l],t=labels[l],today=new Date().toISOString().slice(0,10);return shell(l,'events',c.events,c.eventsLead,intro(l,c.events,c.eventsLead,b)+`<div class="wide section"><div class="notice">${icon('circle')}<p>${e(c.agenda)}</p></div><div class="event-filters" role="group" aria-label="${e(t.filter)}">${['all','upcoming','past'].map((s,i)=>`<button type="button" data-event-filter="${s}" aria-pressed="${i===0}">${e(s==='all'?t.all:c[s])}</button>`).join('')}</div><div class="event-list">${events.map(ev=>`<article class="event-card" data-event-end="${ev.end}" data-event-state="${eventState(ev.end,today)}"><div class="event-date">${ev.dates.map(d=>`<time datetime="${d}">${new Intl.DateTimeFormat(langTags[l],{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'))}</time>`).join(ev.range?' → ':' + ')}<span class="chip" data-event-status>${e(c[eventState(ev.end,today)])}</span></div><div><span class="eyebrow">${e(ev.organizer)}</span><h2 lang="en" dir="ltr">${e(ev.title)}</h2><p class="muted">${e(c.agenda)}</p>${ext(ev.url,t.openSource)}</div></article>`).join('')}</div><p class="empty-state" data-events-empty hidden>${e(t.noResults)}</p><p class="network-disclaimer">${e(t.noAffiliation)} ${e(t.checked)}. 01.10.2026.</p></div>`,b);}
export const campusRenderers={collections:renderCollections,compare:renderCompare,events:renderEvents};
export function decorate(html,l,path,b){if(!l)return html;const t=labels[l],c=campusCopy[l];
 html=html.replace('</head>',`<link rel="stylesheet" href="${b}campus.css"><script type="module" src="${b}campus.js"></script></head>`).replace('<body ',`<body data-campus="marmara-preview" `).replace('content="#173f38"','content="#003d72"');
 html=html.replace(/<a class="brand" href="[^"]+"[^>]*>[\s\S]*?<\/a>/,`<div class="institution-lockup"><a class="university-signature" href="https://www.marmara.edu.tr/" target="_blank" rel="noopener noreferrer"><img src="${b}assets/marmara-${l==='tr'?'tr':'en'}.png" alt="${e(c.university)}" width="210" height="66"></a><span class="lockup-rule" aria-hidden="true"></span><a class="brand campus-brand" href="${route(l,'',b)}"><span><span class="wordmark" dir="ltr">MARSAM</span><span class="brand-sub">${e(t.brand)}</span></span></a></div>`);
 const toolbar=`<div class="campus-tools"><nav class="wide" aria-label="${e(c.tools)}">${['collections','compare','events'].map(k=>`<a href="${route(l,k,b)}" ${path===k?'aria-current="page"':''} ${k==='compare'?'data-compare-nav':''}>${e(c[k])}${k==='compare'?'<span class="compare-count" data-compare-count>0</span>':''}</a>`).join('')}<a href="${route(l,'network',b)}">${e(t.network)}</a></nav></div>`;
 html=html.replace('</header>','</header>'+toolbar);
 html=html.replace(/<article class="source-card"[\s\S]*?<\/article>/g,card=>{const m=card.match(/\/resource\/([a-z0-9-]+)\//);return m?card.replace('</article>',compareButton(m[1],l)+'</article>'):card;});
 if(path.startsWith('resource/'))html=html.replace('<div class="aside-save">',compareButton(path.split('/')[1],l)+'<div class="aside-save">');
 if(path==='network')html=html.replace('<section data-filter-scope>',heading(c.institutionMap,c.mapLead)+networkCards(l,b)+`<h2 class="block-title">${e(t.completeList)}</h2><section data-filter-scope>`);
 html=html.replace('</body>',`<script type="application/json" id="campus-data">${json({locale:l,base:b,copy:c,labels:t,resourceIds:resources.map(r=>r.id)})}</script></body>`);
 return html;
}
