import {C} from './campus-copy.mjs';
const X=(id,name,type,summary,record,links)=>({id,name,type,summary,record,links,relationship:'external-resource',checked:'2026-10-01'});
export const institutions=[
 X('harvard','Harvard Human Flourishing Program',C('Üniversite araştırma programı','University research program','Universitäres Forschungsprogramm','大学研究项目','Университетская исследовательская программа','برنامج بحثي جامعي','Program penelitian universitas','Program penyelidikan universiti'),C('İyi oluş alanlarını, ölçme çalışmalarını ve toplumsal uygulamaları ilişkilendirir. Yayınlar tematik başlıklardan keşfedilebilir.','Connects flourishing domains, measurement and social applications. Publications can be explored through thematic categories.','Verbindet Flourishing-Dimensionen, Messung und gesellschaftliche Anwendungen. Publikationen sind thematisch zugänglich.','连接福祉领域、测量与社会应用，可按主题浏览出版物。','Связывает области благополучия, измерения и общественные применения. Публикации доступны по темам.','يربط مجالات الازدهار والقياس والتطبيقات المجتمعية، مع تصنيف المنشورات موضوعياً.','Menghubungkan ranah flourishing, pengukuran, dan penerapan sosial. Publikasi dapat ditelusuri menurut tema.','Menghubungkan domain flourishing, pengukuran dan aplikasi sosial. Penerbitan boleh diterokai mengikut tema.'),'harvard-resources',[
 ['home','https://hfh.fas.harvard.edu/'],['library','https://hfh.fas.harvard.edu/publications'],['measures','https://hfh.fas.harvard.edu/measuring-flourishing'],['research','https://hfh.fas.harvard.edu/domains-pathways']]),
 X('duke','Duke Center for Spirituality, Theology and Health',C('Tıp merkezi bağlamında araştırma merkezi','Research center in a medical setting','Forschungszentrum im medizinischen Kontext','医学背景下的研究中心','Исследовательский центр в медицинском контексте','مركز بحثي في سياق طبي','Pusat penelitian dalam konteks medis','Pusat penyelidikan dalam konteks perubatan'),C('Araştırma, araştırmacı eğitimi ve klinik uygulamaya aktarım ayrı girişlerle sunulur. RCBT yayınları, çalışma kitapları ve eğitim videoları birbirinden ayrılır.','Separates research, researcher training and clinical translation. RCBT publications, workbooks and training videos have distinct entry points.','Trennt Forschung, Forschungsausbildung und klinischen Transfer. RCBT-Publikationen, Arbeitsbücher und Videos sind gesondert zugänglich.','分别呈现研究、研究者培训与临床转化，RCBT 出版物、工作手册及培训视频有独立入口。','Разделяет исследования, подготовку исследователей и клиническое применение. Публикации, рабочие тетради и видео RCBT имеют отдельные входы.','يفصل بين البحث وتدريب الباحثين ونقل المعرفة للممارسة، مع مداخل مستقلة لمنشورات RCBT وكتبه وفيديوهاته.','Memisahkan penelitian, pelatihan peneliti, dan penerapan klinis. Publikasi, buku kerja, dan video RCBT memiliki jalur tersendiri.','Memisahkan penyelidikan, latihan penyelidik dan aplikasi klinikal. Penerbitan, buku kerja dan video RCBT mempunyai laluan tersendiri.'),'duke-resources',[
 ['home','https://spiritualityandhealth.duke.edu/'],['learning','https://spiritualityandhealth.duke.edu/index.php/education/education-programs/'],['practicePage','https://spiritualityandhealth.duke.edu/index.php/religious-cbt-study/therapy-manuals/'],['library','https://spiritualityandhealth.duke.edu/index.php/publications/crossroads/']]),
 X('smbi','Spirituality Mind Body Institute',C('Teachers College, Columbia University enstitüsü','Institute at Teachers College, Columbia University','Institut am Teachers College, Columbia University','哥伦比亚大学师范学院研究所','Институт Teachers College, Columbia University','معهد في كلية المعلمين بجامعة كولومبيا','Institut di Teachers College, Columbia University','Institut di Teachers College, Columbia University'),C('Araştırmayı eğitim, gelişim, doğa ve toplumsal katılımla ilişkilendiren bir yapı sunar. Kurumun misyon anlatısı, belirli bir müdahalenin etkililik kanıtından ayrı okunmalıdır.','Connects research with education, development, nature and societal engagement. Its mission narrative should be distinguished from evidence for a specific intervention.','Verbindet Forschung mit Bildung, Entwicklung, Natur und gesellschaftlicher Beteiligung. Mission und Evidenz einer konkreten Intervention sind getrennt zu lesen.','将研究与教育、发展、自然及社会参与相联系。机构使命叙述应与特定干预的疗效证据区分。','Связывает исследования с образованием, развитием, природой и общественным участием. Миссию следует отличать от данных об эффективности вмешательства.','يربط البحث بالتعليم والنمو والطبيعة والمشاركة المجتمعية. تُقرأ رسالة المؤسسة منفصلة عن دليل فعالية تدخل محدد.','Menghubungkan penelitian dengan pendidikan, perkembangan, alam, dan keterlibatan sosial. Narasi misi perlu dibedakan dari bukti efektivitas intervensi tertentu.','Menghubungkan penyelidikan dengan pendidikan, perkembangan, alam dan penglibatan masyarakat. Naratif misi perlu dibezakan daripada bukti keberkesanan intervensi tertentu.'),'smbi-resources',[
 ['home','https://spiritualitymindbody.tc.columbia.edu/'],['research','https://spiritualitymindbody.tc.columbia.edu/our-work/'],['learning','https://spiritualitymindbody.tc.columbia.edu/smb-graduate-studies/welcome/'],['events','https://spiritualitymindbody.tc.columbia.edu/events/']]),
 X('iapr','International Association for the Psychology of Religion',C('Uluslararası bilimsel dernek','International scholarly association','Internationale Fachgesellschaft','国际学术协会','Международная научная ассоциация','جمعية علمية دولية','Asosiasi ilmiah internasional','Persatuan ilmiah antarabangsa'),C('Din psikolojisinde bilimsel alışverişi dergi, konferans, üyelik ve söyleşi kanallarıyla destekler. Üniversite araştırma merkezi veya klinik hizmet sağlayıcısı olarak sınıflandırılmaz.','Supports exchange in the psychology of religion through a journal, conferences, membership and interviews. It is not classified as a university research center or clinical service.','Fördert Religionspsychologie durch Zeitschrift, Tagungen, Mitgliedschaft und Interviews. Kein universitäres Forschungszentrum oder klinischer Anbieter.','通过期刊、会议、会员及访谈促进宗教心理学交流，不归类为大学研究中心或临床服务机构。','Поддерживает обмен в психологии религии через журнал, конференции, членство и интервью. Не классифицируется как университетский центр или клиническая служба.','يدعم التبادل في علم نفس الدين عبر مجلة ومؤتمرات وعضوية ومقابلات. لا يُصنّف مركزاً جامعياً أو خدمة سريرية.','Mendukung pertukaran psikologi agama melalui jurnal, konferensi, keanggotaan, dan wawancara. Bukan pusat penelitian universitas atau penyedia layanan klinis.','Menyokong pertukaran psikologi agama melalui jurnal, persidangan, keahlian dan temu bual. Bukan pusat penyelidikan universiti atau penyedia perkhidmatan klinikal.'),'iapr-resources',[
 ['home','https://www.iaprweb.org/'],['about','https://www.iaprweb.org/about-us/'],['library','https://www.iaprweb.org/journal/'],['events','https://www.iaprweb.org/conferences/']])
];
export const collections=[
 {id:'preferences',topic:'practice',article:'understanding-spiritual-experience',readings:['understanding-spiritual-experience','preferences-and-boundaries'],resources:['client-preference','spiritual-competence','sacred-tensions']},
 {id:'meaning',topic:'foundations',article:'culture-and-worldviews',readings:['understanding-spiritual-experience','culture-and-worldviews'],resources:['flourishing-directory','harvard-resources','metaphysical-diversity']},
 {id:'theories',topic:'theory',article:'theory-and-integration',readings:['theory-and-integration','preferences-and-boundaries'],resources:['theories-book','duke-resources','integration-meta-analysis']},
 {id:'assessment',topic:'assessment',article:'assessment-and-permission',readings:['assessment-and-permission','question-to-design'],resources:['fica-directory','flourishing-directory','toad-directory']},
 {id:'ethics',topic:'ethics',article:'preferences-and-boundaries',readings:['preferences-and-boundaries','culture-and-worldviews'],resources:['aservic-principles','spiritual-competence','sacred-tensions']},
 {id:'digital',topic:'digital',article:'digital-tools-and-responsibility',readings:['digital-tools-and-responsibility','reading-evidence'],resources:['ai-health-ethics','prisma-guidance','three-waves']}
];
export const events=[
 {id:'duke-moral-injury-2026',title:'Update on Moral Injury Workshop',organizer:'Duke Center for Spirituality, Theology and Health',dates:['2026-10-03'],end:'2026-10-03',url:'https://spiritualityandhealth.duke.edu/index.php/education/education-programs/',kind:'external-event'},
 {id:'duke-flourishing-2026',title:'Faith and Human Flourishing Workshop',organizer:'Duke Center for Spirituality, Theology and Health',dates:['2026-10-17','2026-10-24'],end:'2026-10-24',url:'https://spiritualityandhealth.duke.edu/index.php/education/education-programs/',kind:'external-event'},
 {id:'duke-research-2026',title:'Spirituality and Health Research Workshop',organizer:'Duke Center for Spirituality, Theology and Health',dates:['2026-12-05'],end:'2026-12-05',url:'https://spiritualityandhealth.duke.edu/index.php/education/education-programs/',kind:'external-event'},
 {id:'iapr-birmingham-2025',title:'IAPR Conference 2025. Highlighting the Cross-Disciplinarity of the Psychology of Religion',organizer:'IAPR',dates:['2025-08-19','2025-08-22'],end:'2025-08-22',range:true,url:'https://www.iaprweb.org/conferences/',kind:'external-event'}
];
