/** Neutral publication and learning labels. Research questions remain inside readings. */
import {C} from './campus-copy.mjs';
export const dossierTitles={
 'understanding-spiritual-experience':C('Manevi deneyim ve psikolojik danışma','Spiritual experience and counseling','Spirituelles Erleben und Beratung','灵性经验与心理咨询','Духовный опыт и консультирование','الخبرة الروحية والإرشاد النفسي','Pengalaman spiritual dan konseling','Pengalaman kerohanian dan kaunseling'),
 'reading-evidence':C('Araştırma bulgularının değerlendirilmesi','Evaluating research findings','Forschungsbefunde beurteilen','评估研究结果','Оценка результатов исследований','تقييم نتائج البحث','Menilai temuan penelitian','Menilai dapatan penyelidikan'),
 'preferences-and-boundaries':C('Danışma sürecinde mesleki yeterlik ve etik','Professional competence and ethics in the counseling process','Kompetenz und Ethik in der Beratung','咨询中的专业胜任力与伦理','Компетентность и этика в консультировании','الكفاءة والأخلاقيات في الإرشاد','Kompetensi dan etika dalam konseling','Kecekapan dan etika dalam kaunseling'),
 'culture-and-worldviews':C('Kültürel bağlam ve dünya görüşü','Cultural context and worldview','Kultureller Kontext und Weltanschauung','文化情境与世界观','Культурный контекст и мировоззрение','السياق الثقافي ورؤية العالم','Konteks budaya dan pandangan hidup','Konteks budaya dan pandangan hidup'),
 'assessment-and-permission':C('Ölçme araçlarının seçimi','Selecting assessment instruments','Erfassungsinstrumente auswählen','选择评估工具','Выбор инструментов оценки','اختيار أدوات التقييم','Pemilihan instrumen asesmen','Pemilihan instrumen penilaian'),
 'question-to-design':C('Araştırma sorusu ve yöntem','Research questions and methods','Forschungsfragen und Methoden','研究问题与方法','Исследовательские вопросы и методы','أسئلة البحث ومناهجه','Pertanyaan dan metode penelitian','Soalan dan kaedah penyelidikan'),
 'theory-and-integration':C('Psikoterapi kuramlarında maneviyat','Spirituality in psychotherapy theories','Spiritualität in Psychotherapietheorien','心理治疗理论中的灵性','Духовность в теориях психотерапии','الروحانية في نظريات العلاج النفسي','Spiritualitas dalam teori psikoterapi','Kerohanian dalam teori psikoterapi'),
 'digital-tools-and-responsibility':C('Yapay zekâ ve mesleki sorumluluk','AI and professional responsibility','KI und berufliche Verantwortung','人工智能与专业责任','ИИ и профессиональная ответственность','الذكاء الاصطناعي والمسؤولية المهنية','AI dan tanggung jawab profesional','AI dan tanggungjawab profesional')
};
export const pathSummaries={
 foundations:C('Temel kavramlar, kuramsal yaklaşımlar ve başlangıç için önerilen okumalar.','Foundational concepts, theoretical approaches and introductory readings.','Grundbegriffe, theoretische Ansätze und Einstiegslektüre.','基本概念、理论取向与入门阅读。','Основные понятия, теоретические подходы и вводные материалы.','المفاهيم الأساسية والمقاربات النظرية والقراءات التمهيدية.','Konsep dasar, pendekatan teoretis, dan bacaan pengantar.','Konsep asas, pendekatan teori dan bacaan pengenalan.'),
 professional:C('Danışma süreci, kültüre duyarlı değerlendirme ve mesleki yeterlik.','Counseling processes, culturally responsive assessment and professional competence.','Beratungsprozesse, kultursensible Erfassung und berufliche Kompetenz.','咨询过程、文化回应性评估与专业胜任力。','Процесс консультирования, культурно чувствительная оценка и компетентность.','عملية الإرشاد والتقييم المراعي للثقافة والكفاءة المهنية.','Proses konseling, asesmen peka budaya, dan kompetensi profesional.','Proses kaunseling, penilaian peka budaya dan kecekapan profesional.'),
 research:C('Araştırma tasarımı, ölçme kaynakları ve bilimsel raporlama.','Research design, measurement resources and scientific reporting.','Forschungsdesign, Messressourcen und wissenschaftliche Berichterstattung.','研究设计、测量资源与科学报告。','Дизайн исследования, измерительные ресурсы и научная отчётность.','تصميم البحث وموارد القياس وإعداد التقارير العلمية.','Desain penelitian, sumber pengukuran, dan pelaporan ilmiah.','Reka bentuk penyelidikan, sumber pengukuran dan pelaporan saintifik.')
};
export const publicationSummaries={
 'theories-book':C('Psikoterapi ve psikolojik danışma yaklaşımlarının manevi boyutlarını ele alan, Halil Ekşi editörlüğündeki kitap.','A volume edited by Halil Ekşi on the spiritual dimensions of psychotherapy and counseling approaches.','Ein von Halil Ekşi herausgegebener Band über spirituelle Dimensionen von Psychotherapie und Beratung.','Halil Ekşi 主编，讨论心理治疗与咨询取向中灵性维度的著作。','Книга под редакцией Halil Ekşi о духовных измерениях психотерапии и консультирования.','كتاب بإشراف Halil Ekşi حول الأبعاد الروحية لمقاربات العلاج النفسي والإرشاد.','Buku suntingan Halil Ekşi tentang dimensi spiritual dalam pendekatan psikoterapi dan konseling.','Buku suntingan Halil Ekşi tentang dimensi kerohanian dalam pendekatan psikoterapi dan kaunseling.'),
 'integration-meta-analysis':C('Dini ve manevi açıdan uyarlanmış psikoterapileri, farklı karşılaştırma gruplarına ve sonuçlara göre inceleyen bir meta-analiz.','A meta-analysis of religiously and spiritually adapted psychotherapy across comparison conditions and outcomes.','Eine Metaanalyse religiös und spirituell angepasster Psychotherapie unter verschiedenen Vergleichsbedingungen und Ergebnismaßen.','针对宗教与灵性适配心理治疗的元分析，考察不同对照条件与结果。','Метаанализ религиозно и духовно адаптированной психотерапии с различными условиями сравнения и исходами.','تحليل تلوي للعلاج النفسي المكيف دينياً وروحياً عبر شروط مقارنة ونتائج مختلفة.','Meta-analisis psikoterapi yang disesuaikan secara religius dan spiritual pada berbagai kondisi perbandingan dan hasil.','Meta-analisis psikoterapi yang disesuaikan secara agama dan kerohanian merentas syarat perbandingan dan hasil.')
};
export const permissionsText=C('Kitap bölümleri, ölçek maddeleri, görseller ve video kayıtları, kullanım hakları incelenmeden sitede yeniden yayımlanmaz. Yayın kayıtlarında özgün kaynağa bağlantı verilir. Ders dosyaları, yayımlanmamış çalışmalar ve kişisel bilgiler bu koleksiyona alınmaz.','Book chapters, scale items, images and recordings are not republished without checking usage rights. Publication records link to original sources. Private coursework, unpublished work and personal information are not included in this collection.','Buchkapitel, Skalenitems, Bilder und Aufzeichnungen werden nicht ohne Prüfung der Nutzungsrechte erneut veröffentlicht. Einträge verlinken Originalquellen. Private Kursunterlagen, unveröffentlichte Arbeiten und personenbezogene Informationen gehören nicht in diese Sammlung.','书籍章节、量表条目、图片及录像在核查使用权之前不得转载。出版记录链接到原始来源。本合集不收录私人课程文件、未发表作品或个人信息。','Главы книг, пункты шкал, изображения и записи не переиздаются без проверки прав. Записи содержат ссылки на первоисточники. Частные учебные файлы, неопубликованные работы и личные сведения не входят в коллекцию.','لا يُعاد نشر فصول الكتب أو بنود المقاييس أو الصور أو التسجيلات قبل فحص حقوق الاستخدام. تربط السجلات بالمصادر الأصلية. لا تتضمن المجموعة ملفات دراسية خاصة أو أعمالاً غير منشورة أو معلومات شخصية.','Bab buku, butir skala, gambar, dan rekaman tidak diterbitkan kembali tanpa pemeriksaan hak penggunaan. Catatan publikasi menautkan sumber asli. Tugas kuliah privat, karya yang belum diterbitkan, dan informasi pribadi tidak dimasukkan dalam koleksi.','Bab buku, item skala, imej dan rakaman tidak diterbitkan semula tanpa semakan hak penggunaan. Rekod penerbitan memautkan sumber asal. Tugasan kursus peribadi, karya belum diterbitkan dan maklumat peribadi tidak dimasukkan dalam koleksi.');
