import {scholarlyCopy} from './scholarship.mjs';
import {L,labels} from './i18n.mjs';
const checked='2026-10-01';
const source=(id,title,year,url,citation,kind,inspection='abstract',extra={})=>({id,title,year,url,citation,kind,inspection,checked,level:'V1',status:'PARTIALLY_VERIFIED',access:inspection==='abstract'?'Authoritative bibliographic record and accessible abstract inspected.':inspection==='official'?'Relevant official public resource page inspected.':'Publisher bibliographic record and description inspected.',limit:'No comprehensive current correction/retraction or permissions clearance audit. Inspection is limited to the identified material. Not scientific editorial approval.',...extra});
export const sources=[
 source('s-aservic','Spiritual and religious best practices',2025,'https://aservic.org/wp-content/uploads/2026/02/ASERVIC.-2025.-Spiritual-and-Religious-Best-Practices-1.pdf','Association for Spiritual, Ethical, and Religious Values in Counseling. (2025). Spiritual and religious best practices.','guide','official',{access:'Official PDF and cover inspected. ASERVIC approval and pending ACA endorsement are recorded as wording of this document, not a claim about a separately checked current ACA decision.'}),
 source('s-vieten','Spiritual and religious competencies in psychology',2022,'https://pubmed.ncbi.nlm.nih.gov/34264695/','Vieten, C., & Lukoff, D. (2022). Spiritual and religious competencies in psychology. American Psychologist, 77(1), 26–38. https://doi.org/10.1037/amp0000821','theory'),
 source('s-captari','Integrating clients’ religion and spirituality within psychotherapy: A comprehensive meta-analysis',2018,'https://doi.org/10.1002/jclp.22681','Captari, L. E., Hook, J. N., Hoyt, W., Davis, D. E., McElroy-Heltzel, S. E., & Worthington, E. L., Jr. (2018). Integrating clients’ religion and spirituality within psychotherapy: A comprehensive meta-analysis. Journal of Clinical Psychology, 74(11), 1938–1951. https://doi.org/10.1002/jclp.22681','study'),
 source('s-swift','Client preference accommodation for religious/spiritual integration and psychotherapy outcomes in naturalistic practice settings',2022,'https://pubmed.ncbi.nlm.nih.gov/34553982/','Swift, J. K., Bird, M. O., Penix, E. A., & Trusty, W. T. (2022). Client preference accommodation for religious/spiritual integration and psychotherapy outcomes in naturalistic practice settings. Psychotherapy, 59(3), 392–399. https://doi.org/10.1037/pst0000386','study'),
 source('s-tunc','Sacred tensions: How mental health professionals navigate spirituality, ethics, and professional identity',2025,'https://doi.org/10.1007/s11089-025-01244-0','Tunç, M. F., & Ekşi, H. (2025). Sacred tensions: How mental health professionals navigate spirituality, ethics, and professional identity. Pastoral Psychology, 74(6), 937–958. https://doi.org/10.1007/s11089-025-01244-0','study','abstract',{access:'Marmara University AVESIS record and author abstract inspected. Eight-practitioner qualitative context; no prevalence or treatment-effect inference.'}),
 source('s-hodge','Metaphysical diversity in mental health discourse: The key to scientific progress in the helping professions',2021,'https://doi.org/10.37898/spc.2021.6.3.154','Hodge, D. R. (2021). Metaphysical diversity in mental health discourse: The key to scientific progress in the helping professions. Spiritual Psychology and Counseling, 6(3), 7–30. https://doi.org/10.37898/spc.2021.6.3.154','theory'),
 source('s-pargament','From research to practice: Three waves in the evolution of the psychology of religion and spirituality',2023,'https://doi.org/10.37898/spc.2023.8.3.191','Pargament, K. I. (2023). From research to practice: Three waves in the evolution of the psychology of religion and spirituality. Spiritual Psychology and Counseling, 8(3), 207–225. https://doi.org/10.37898/spc.2023.8.3.191','theory'),
 source('s-eksi','Psikoterapi ve psikolojik danışma kuramları: Manevi boyutlarıyla',2024,'https://www.kaknus.com.tr/urun/psikoterapi-ve-psikolojik-danisma-kuramlari/','Ekşi, H. (Ed.). (2024). Psikoterapi ve psikolojik danışma kuramları: Manevi boyutlarıyla. Kaknüs. ISBN 9789752567153.','theory','metadata'),
 source('s-toad','Türkiye Ölçme Araçları Dizini',null,'https://toad.halileksi.net/','TOAD. (n.d.). Türkiye Ölçme Araçları Dizini. Accessed 2026-10-01.','measure','official',{limit:'An index listing does not itself establish permission, suitability for a population or validity of a new translation. No API integration or partnership is claimed.'}),
 source('s-prisma','PRISMA statement',null,'https://www.prisma-statement.org/','PRISMA. (n.d.). PRISMA statement. Official website, accessed 2026-10-01.','method','official'),
 source('s-who-ai','Ethics and governance of artificial intelligence for health',2021,'https://www.who.int/publications/i/item/9789240029200','World Health Organization. (2021). Ethics and governance of artificial intelligence for health. WHO.','guide','official'),
];
const section=(id,summary,group,topic)=>({id,title:Object.fromEntries(Object.entries(labels).map(([l,v])=>[l,v[id]])),summary,group,topic});
export const sections=[
 section('library',L('Kaynağın türünü, erişilen kapsamını ve yorum sınırını birlikte gör.','See each source’s type, inspected material and interpretive limits.','Quellentyp, geprüften Umfang und Aussagegrenzen gemeinsam sehen.','同时查看来源类型、已核查范围及解释边界。','Изучайте тип источника, проверенный материал и границы выводов.'),'research','evidence'),
 section('concepts',L('Manevi yaşantı, tercih, anlam ve iyi oluş. Aynı kelimeler her bağlamda aynı şeyi anlatmaz.','Spiritual experience, preferences, meaning and well-being. Words do not carry identical meanings in every context.','Spirituelles Erleben, Präferenzen, Sinn und Wohlbefinden. Begriffe bedeuten nicht in jedem Kontext dasselbe.','灵性经验、偏好、意义与福祉。同一词语在不同情境中未必含义相同。','Духовный опыт, предпочтения, смысл и благополучие. В разных контекстах слова могут означать разное.'),'explore','foundations'),
 section('approaches',L('Kuramın insana, değişime ve manevi yaşantıya nasıl yaklaştığını karşılaştırarak oku.','Compare how theories understand the person, change and spiritual experience.','Vergleichen Sie Menschenbild, Veränderungsverständnis und spirituelles Erleben verschiedener Ansätze.','比较不同理论对人、改变与灵性经验的理解。','Сравнивайте понимание человека, изменений и духовного опыта в разных подходах.'),'explore','theory'),
 section('practice',L('Danışanın gündemi, değerlendirme ve ortak hedefler. Eğitim amaçlı okuma, kişiye özel müdahale değil.','The client’s agenda, assessment and shared goals. Educational reading, not individualized intervention.','Anliegen, Erfassung und gemeinsame Ziele. Lernmaterial, keine individuelle Intervention.','来访者议题、评估与共同目标。用于学习，而非个体化干预。','Запрос клиента, оценка и общие цели. Учебное чтение, не индивидуальная интервенция.'),'learn','practice'),
 section('ethics',L('Değer dayatmama, yeterlik, gizlilik ve hesap verebilirlik.','Non-imposition of values, competence, confidentiality and accountability.','Verzicht auf Werteaufdrängung, Kompetenz, Vertraulichkeit und Rechenschaftspflicht.','避免价值强加、胜任力、保密与责任。','Ненавязывание ценностей, компетентность, конфиденциальность и ответственность.'),'learn','ethics'),
 section('methods',L('Araştırma sorusu, tasarım, kanıt türü ve çıkarım sınırını aynı çerçevede tut.','Keep the question, design, evidence type and limits of inference aligned.','Fragestellung, Design, Evidenzart und Schlussfolgerungen aufeinander abstimmen.','使研究问题、设计、证据类型与推断边界保持一致。','Согласуйте вопрос, дизайн, вид доказательств и границы вывода.'),'research','methods'),
 section('measures',L('Araç seçmeden önce amaç, hedef grup, uyarlama ve kullanım iznini incele. Burada ölçek uygulanmaz veya puanlanmaz.','Check purpose, population, adaptation and permission before selecting a tool. No scales are administered or scored here.','Vor der Auswahl Zweck, Zielgruppe, Anpassung und Erlaubnis prüfen. Hier werden keine Skalen angewendet oder ausgewertet.','选择工具前核查目的、目标群体、适配与授权。本页不施测或评分。','До выбора инструмента проверьте цель, группу, адаптацию и разрешения. Здесь шкалы не применяются и не оцениваются.'),'research','assessment'),
 section('learning',L('Öğrenci, uygulayıcı ve araştırmacılar için takip edilebilir okuma rotaları.','Structured reading paths for students, practitioners and researchers.','Strukturierte Lesepfade für Studierende, Praktizierende und Forschende.','为学生、实践工作者与研究者设计的阅读路径。','Последовательные маршруты чтения для студентов, практиков и исследователей.'),'learn','learning'),
 section('media',L('Kurumların kendi sayfalarındaki eğitim ve video koleksiyonlarına eriş.','Explore learning and video collections on their original institutions’ pages.','Lern- und Videosammlungen auf den Originalseiten der Einrichtungen entdecken.','浏览原机构网站上的学习与视频资源。','Учебные и видеоколлекции на сайтах самих организаций.'),'learn','learning'),
 section('projects',L('İleride geliştirilebilecek araştırma alanları. Onaylı, finanse edilmiş veya başlamış projeler olarak sunulmaz.','Possible areas for future research. Not approved, funded or active projects.','Mögliche künftige Forschungsfelder. Keine genehmigten, finanzierten oder laufenden Projekte.','未来可发展的研究方向，不代表已获批、获资助或启动的项目。','Возможные направления исследований. Это не утверждённые, финансируемые или начатые проекты.'),'research','methods'),
 section('participate',L('Katılımcı çağrılarında etik, sorumluluk ve veri güvenliği bilgileri birlikte yer almalıdır.','Recruitment calls must specify ethics, responsibility and data safeguards together.','Studienaufrufe sollen Ethik, Verantwortlichkeit und Datenschutz gemeinsam ausweisen.','研究招募应同时说明伦理、责任人与数据保护。','В приглашениях к участию должны быть указаны этические условия, ответственность и защита данных.'),'research','methods'),
 section('news',L('Site güncellemeleri ve editoryal gündem. Doğrulanmamış etkinlik ve kurum haberleri eklenmez.','Site updates and the editorial agenda. No unverified events or institutional news.','Aktualisierungen der Website und redaktionelle Themen. Keine ungeprüften Veranstaltungen oder Institutionsmeldungen.','网站更新与编辑议程，不添加未经核实的活动或机构新闻。','Обновления сайта и редакционная повестка. Без неподтверждённых событий и новостей центра.'),'center','learning'),
 section('about',L('Merkezin tanıtımı, amacı ve hedef kitlesi.','An introduction to the center, its purpose and its audience.','Vorstellung des Zentrums, seines Ziels und seiner Zielgruppen.','中心简介、宗旨与受众。','О центре, его цели и аудитории.'),'center','network'),
 section('editorial',L('Bir içerik nasıl önerilir, kaynaklandırılır, incelenir, çevrilir ve güncellenir.','How content is proposed, sourced, reviewed, translated and updated.','Wie Inhalte vorgeschlagen, belegt, geprüft, übersetzt und aktualisiert werden.','内容如何提出、引用、审核、翻译与更新。','Как материалы предлагаются, обосновываются, проверяются, переводятся и обновляются.'),'center','ethics'),
 section('contribute',L('Henüz gönderim yapmadan bir kaynak veya içerik önerisini yapılandır.','Structure a source or content proposal without submitting it.','Einen Quellen- oder Inhaltsvorschlag strukturieren, ohne ihn zu versenden.','先整理资源或内容建议，无需发送。','Составьте предложение источника или материала без отправки.'),'center','ethics'),
 section('saved',L('Kendi okuma sıranı oluştur. Liste yalnız kullandığın tarayıcıda saklanır.','Create your reading order. The list stays only in your browser.','Ihre Lesereihenfolge. Die Liste bleibt nur in Ihrem Browser.','安排自己的阅读顺序，清单仅存于当前浏览器。','Составьте порядок чтения. Список хранится только в вашем браузере.'),'center','learning'),
 section('search',L('Dosyalar, kaynak kayıtları ve konu sayfalarında birlikte ara.','Search dossiers, source records and topic pages together.','Dossiers, Quelleneinträge und Themenseiten gemeinsam durchsuchen.','同时搜索专题、资源记录与主题页面。','Ищите одновременно по досье, записям источников и тематическим страницам.'),'center','learning')
];
// Every entry is a catalogue record, not a MARSAM publication or a claim of partnership.
const R=(id,sid,title,summary,sections,topic)=>({id,title,summary,sections,topic,sources:[sid],kind:sources.find(s=>s.id===sid).kind,review:'draft',translation:'draft',rights:'link-only',approval:null});
export const resources=[
 R('aservic-principles','s-aservic',L('Manevi ve dini konularda mesleki uygulama ilkeleri','Professional practice principles for spirituality and religion','Fachliche Prinzipien für Spiritualität und Religion','灵性与宗教领域的专业实践原则','Профессиональные принципы работы с духовностью и религией'),L('ASERVIC’in 2025 mesleki rehberi. Belgenin onay bilgisi ve mesleki kapsamı kaydında ayrıca açıklanır.','ASERVIC’s 2025 professional guidance. The record distinguishes the document’s approval wording and professional scope.','Fachliche Orientierung von ASERVIC 2025. Freigabevermerk und fachlicher Geltungsbereich werden getrennt erläutert.','ASERVIC 2025 年专业指南，条目分别说明文件中的批准信息及适用范围。','Профессиональное руководство ASERVIC 2025 года. Формулировки одобрения и профессиональный охват указаны отдельно.'),['library','ethics','practice'],'ethics'),
 R('spiritual-competence','s-vieten',L('Manevi ve dini yeterlikler','Spiritual and religious competencies','Spirituelle und religiöse Kompetenz','灵性与宗教胜任力','Духовная и религиозная компетентность'),L('Değerlendirme, tedavi planlaması ve mesleki yeterliği ele alan bir çerçeve. Tam metin incelemesi yerine özet kapsamıyla kullanılır.','A framework addressing assessment, treatment planning and competence. Used within the accessible abstract’s scope.','Ein Rahmen für Erfassung, Behandlungsplanung und Kompetenz. Nutzung im Umfang der zugänglichen Zusammenfassung.','讨论评估、治疗规划与胜任力的框架，使用范围限于可访问摘要。','Рамка оценки, планирования помощи и компетентности. Использована в пределах доступной аннотации.'),['library','practice','learning','ethics'],'practice'),
 R('integration-meta-analysis','s-captari',L('Manevi uyarlamalar için meta-analitik kanıt','Meta-analytic evidence for spiritual adaptations','Metaanalytische Evidenz zu spirituellen Anpassungen','灵性适配的元分析证据','Метааналитические данные о духовной адаптации терапии'),L('Karşılaştırma koşulu önemlidir. Psikolojik sıkıntı ve manevi iyi oluş sonuçları birbirinin yerine yorumlanmamalıdır.','The comparator matters. Psychological distress and spiritual well-being outcomes must not be treated as interchangeable.','Die Vergleichsbedingung zählt. Psychische Belastung und spirituelles Wohlbefinden sind unterschiedliche Ergebnisbereiche.','比较条件十分重要。心理困扰与灵性福祉不能作为可互换的结果解读。','Условие сравнения имеет значение. Психологический дистресс и духовное благополучие нельзя считать взаимозаменяемыми исходами.'),['library','methods','practice'],'evidence'),
 R('client-preference','s-swift',L('Danışanın manevi entegrasyon tercihi','Client preferences for spiritual integration','Präferenzen für spirituelle Integration','来访者对灵性整合的偏好','Предпочтения клиента относительно духовной интеграции'),L('Doğal uygulama ortamında danışan tercihlerinin karşılanmasını inceleyen gözlemsel çalışma. İlişki, tek başına nedensellik göstermez.','An observational study of preference accommodation in routine practice. Association alone does not establish causation.','Beobachtungsstudie zur Berücksichtigung von Präferenzen in der Praxis. Ein Zusammenhang allein belegt keine Kausalität.','在实际实践中考察偏好满足的观察性研究。关联本身不能证明因果关系。','Наблюдательное исследование учёта предпочтений в обычной практике. Связь сама по себе не доказывает причинность.'),['library','practice','methods'],'practice'),
 R('sacred-tensions','s-tunc',L('Türkiye’de manevi yaşantı ve mesleki sınırlar','Spiritual experience and professional boundaries in Türkiye','Spirituelles Erleben und berufliche Grenzen in der Türkei','土耳其的灵性经验与专业边界','Духовный опыт и профессиональные границы в Турции'),L('Sekiz uygulayıcıyla nitel araştırma. Kültürel alçakgönüllülük, özerklik ve mesleki kimlik hakkında bağlamsal bir okuma.','Qualitative research with eight practitioners. A contextual reading of cultural humility, autonomy and professional identity.','Qualitative Forschung mit acht Praktizierenden. Kontextbezogene Perspektiven auf kulturelle Bescheidenheit, Autonomie und berufliche Identität.','对八位实践工作者的质性研究，讨论文化谦逊、自主性与专业身份的具体情境。','Качественное исследование с восемью практиками. Контекстуальный взгляд на культурную скромность, автономию и профессиональную идентичность.'),['library','ethics','practice'],'culture'),
 R('metaphysical-diversity','s-hodge',L('Metafizik çeşitlilik üzerine kuramsal tartışma','A theoretical discussion of metaphysical diversity','Theoretische Diskussion metaphysischer Vielfalt','关于形而上学多样性的理论讨论','Теоретическое обсуждение метафизического разнообразия'),L('Ruh sağlığı söylemindeki metafizik varsayımları tartışan kuramsal metin. Bir yaklaşımın üstün etkililiğini sınamaz.','A theoretical examination of metaphysical assumptions in mental health discourse. It does not test treatment superiority.','Theoretische Analyse metaphysischer Annahmen im Diskurs über psychische Gesundheit. Kein Überlegenheitsnachweis einer Behandlung.','讨论心理健康话语中的形而上学假设，未检验任何疗法的优越效果。','Теоретический анализ метафизических предпосылок. Работа не проверяет превосходство терапевтического подхода.'),['library','concepts','approaches'],'culture'),
 R('three-waves','s-pargament',L('Araştırmadan uygulamaya üç dalga','Three waves from research to practice','Drei Wellen von Forschung zur Praxis','从研究到实践的三次发展浪潮','Три волны от исследования к практике'),L('Din ve maneviyat psikolojisinde kuram, araştırma ve uygulama ilişkisini inceleyen alan değerlendirmesi.','A field review of the relationship between theory, research and practice in the psychology of religion and spirituality.','Ein Überblick zum Verhältnis von Theorie, Forschung und Praxis in der Religions- und Spiritualitätspsychologie.','回顾宗教与灵性心理学中理论、研究及实践之间的关系。','Обзор связей между теорией, исследованиями и практикой в психологии религии и духовности.'),['library','concepts','methods'],'foundations'),
 R('theories-book','s-eksi',L('Psikoterapi kuramlarını manevi boyutlarıyla okumak','Reading psychotherapy theories through spiritual dimensions','Psychotherapietheorien und spirituelle Dimensionen','从灵性维度阅读心理治疗理论','Духовные измерения психотерапевтических теорий'),L('Halil Ekşi editörlüğündeki 2024 kitabının yayıncı kaydı. Kitap bölümleri bu sitede yeniden yayımlanmamaktadır.','Publisher record for the 2024 volume edited by Halil Ekşi. Book chapters are not republished on this site.','Verlagseintrag des von Halil Ekşi herausgegebenen Bandes von 2024. Buchkapitel werden hier nicht erneut veröffentlicht.','Halil Ekşi 主编的 2024 年著作之出版方记录。本网站不转载书籍章节。','Запись издателя о книге 2024 года под редакцией Halil Ekşi. Главы книги здесь не переиздаются.'),['library','approaches','learning'],'theory'),
 R('toad-directory','s-toad',L('TOAD · Türkçe ölçme kaynağı aramak','TOAD · Finding Turkish assessment resources','TOAD · Türkischsprachige Instrumente finden','TOAD · 查找土耳其语测量资源','TOAD · Поиск инструментов на турецком языке'),L('Türkçe ölçme kaynakları için dış dizin. MARSAM ile entegrasyon veya iş birliği varmış gibi sunulmaz.','An external index for Turkish assessment resources. No MARSAM integration or partnership is implied.','Externes Verzeichnis türkischsprachiger Instrumente. Keine behauptete Integration oder Partnerschaft mit MARSAM.','土耳其语测量资源的外部索引，不表示与 MARSAM 有系统整合或合作。','Внешний каталог инструментов на турецком языке. Интеграция или партнёрство с MARSAM не заявляются.'),['library','measures'],'assessment'),
 R('prisma-guidance','s-prisma',L('PRISMA · Şeffaf derleme raporlaması','PRISMA · Transparent review reporting','PRISMA · Transparente Berichterstattung','PRISMA · 透明的综述报告','PRISMA · Прозрачная отчётность обзоров'),L('Resmî bildirim ve uzantılara başlangıç noktası. Raporlama kontrol listesi, araştırma tasarımını veya kanıt kalitesini kendiliğinden doğrulamaz.','An entry point to the official statement and extensions. A reporting checklist does not itself validate design or evidence quality.','Zugang zur offiziellen Erklärung und ihren Erweiterungen. Eine Checkliste bestätigt nicht automatisch Design oder Evidenzqualität.','官方声明与扩展指南的入口。报告清单本身不能验证研究设计或证据质量。','Вход к официальному заявлению и расширениям. Чек-лист сам по себе не подтверждает качество дизайна или доказательств.'),['library','methods'],'methods'),
 R('ai-health-ethics','s-who-ai',L('Sağlıkta yapay zekâ, etik ve yönetişim','Ethics and governance of artificial intelligence for health','KI für Gesundheit, Ethik und Governance','健康领域人工智能的伦理与治理','ИИ в здравоохранении: этика и управление'),L('DSÖ’nün 2021 rehberi. Teknik performans ile klinik yarar, insan denetimi ve sorumluluk ayrı değerlendirilmelidir.','WHO’s 2021 guidance. Technical performance, clinical benefit, human oversight and responsibility require separate consideration.','WHO-Leitlinie von 2021. Technische Leistung, klinischer Nutzen, menschliche Aufsicht und Verantwortung sind getrennt zu beurteilen.','WHO 2021 年指南。技术表现、临床获益、人工监督与责任应分别评估。','Руководство ВОЗ 2021 года. Технические показатели, клиническая польза, человеческий надзор и ответственность требуют отдельной оценки.'),['library','ethics','methods'],'digital'),
];
export const typeKeys={study:'metaStudy',theory:'metaTheory',guide:'metaGuide',measure:'metaMeasure',hub:'metaHub',method:'metaMethod'};
export const topics={
 foundations:L('Temel kavramlar','Foundations','Grundlagen','基础概念','Основы'),
 practice:L('Danışma süreci','Counseling process','Beratungsprozess','咨询过程','Процесс консультирования'),
 ethics:L('Etik ve yetkinlik','Ethics and competence','Ethik und Kompetenz','伦理与胜任力','Этика и компетентность'),
 culture:L('Kültür ve çeşitlilik','Culture and diversity','Kultur und Vielfalt','文化与多样性','Культура и разнообразие'),
 evidence:L('Kanıtı değerlendirmek','Evaluating evidence','Evidenz beurteilen','评估证据','Оценка доказательств'),
 assessment:L('Ölçme ve değerlendirme','Measurement and assessment','Messung und Erfassung','测量与评估','Измерение и оценка'),
 theory:L('Kuram ve maneviyat','Theory and spirituality','Theorie und Spiritualität','理论与灵性','Теория и духовность'),
 methods:L('Araştırma tasarımı','Research design','Forschungsdesign','研究设计','Дизайн исследования'),
 learning:L('Öğrenme','Learning','Lernen','学习','Обучение'),
 network:L('Dış kaynaklar','External resources','Externe Ressourcen','外部资源','Внешние ресурсы'),
 digital:L('Dijital araçlar','Digital tools','Digitale Werkzeuge','数字工具','Цифровые инструменты')
};

import {regionalSources,regionalResources} from './regional.mjs';
sources.push(...regionalSources);
resources.push(...regionalResources);

import {applyPublications} from './publications-data.mjs';
applyPublications(sources,resources);
import {strategicSources,strategicResources,strategicSections} from './roadmap/platform.mjs';
sources.push(...strategicSources);
resources.push(...strategicResources);
sections.push(...strategicSections);
typeKeys.book='metaBook';

import {h as heritageLabels} from './heritage-copy.mjs';
for(const id of ['publications','books'])if(!sections.some(s=>s.id===id))sections.push({id,title:heritageLabels[id],summary:heritageLabels[id+'Lead'],group:'explore',topic:'theory'});

sections.push({id:'evidence',title:scholarlyCopy.evidence,summary:scholarlyCopy.lead,group:'research',topic:'evidence'});
