import {L} from './i18n.mjs';
export const learningPaths=[
 {id:'foundations',title:L('Temelden başla','Start with foundations','Mit Grundlagen beginnen','从基础开始','Начните с основ'),summary:L('Kavramı öğren, kuramsal çerçeveyi karşılaştır, kaynağı sınırlarıyla oku.','Learn the concepts, compare theoretical frames and read sources with their limits.','Begriffe klären, theoretische Rahmen vergleichen und Quellengrenzen beachten.','学习概念、比较理论框架，并连同局限阅读来源。','Изучите понятия, сравните рамки и читайте источники с учётом ограничений.'),audience:'student',articles:['understanding-spiritual-experience','culture-and-worldviews','theory-and-integration','reading-evidence']},
 {id:'professional',title:L('Danışma sürecini düşün','Reflect on counseling','Beratung reflektieren','反思咨询过程','Осмыслите консультирование'),summary:L('Danışan tercihini, manevi değerlendirmeyi ve mesleki sınırları birlikte ele al.','Connect client preferences, spiritual assessment and professional boundaries.','Präferenzen, spirituelle Erfassung und berufliche Grenzen zusammen betrachten.','把来访者偏好、灵性评估与专业边界联系起来。','Свяжите предпочтения, духовную оценку и профессиональные границы.'),audience:'professional',articles:['understanding-spiritual-experience','preferences-and-boundaries','culture-and-worldviews','assessment-and-permission']},
 {id:'research',title:L('Araştırmaya hazırlan','Prepare for research','Forschung vorbereiten','为研究做准备','Подготовьтесь к исследованию'),summary:L('İddiayı ve tasarımı ayır, ölçme kaynağını seç, dijital sorumluluğu koru.','Distinguish claims and design, select measurement resources and retain digital responsibility.','Aussagen und Design unterscheiden, Instrumente wählen und digitale Verantwortung bewahren.','区分主张与设计，选择测量资源，保留数字责任。','Различайте утверждение и дизайн, выбирайте измерения, сохраняйте цифровую ответственность.'),audience:'researcher',articles:['reading-evidence','question-to-design','assessment-and-permission','digital-tools-and-responsibility']}
];
export const overview = {
 about:[
  {title:L('Bir merkezin dijital başlangıcını düşünmek','Designing a center’s digital beginning','Den digitalen Anfang eines Zentrums gestalten','构思研究中心的数字起点','Проектировать цифровое начало центра'),text:L('MARSAM, maneviyat ve ruh sağlığı alanında araştırma, mesleki öğrenme ve kaynak paylaşımını bir araya getirmeyi amaçlayan bir merkezdir. Bu site, merkezin çalışma alanlarını ve içerik yapısını tanıtır.','MARSAM is a center that aims to bring together research, professional learning and resources in spirituality and mental health. This website introduces its areas of work and content structure.','MARSAM ist ein Zentrum, das Forschung, berufliches Lernen und Ressourcen zu Spiritualität und psychischer Gesundheit zusammenführen will. Diese Website stellt seine Arbeitsfelder und seine Inhaltsstruktur vor.','MARSAM 是一个致力于汇集灵性与心理健康领域研究、专业学习与资源分享的中心。本网站介绍中心的工作领域与内容结构。','MARSAM — центр, призванный объединить исследования, профессиональное обучение и ресурсы в области духовности и психического здоровья. Сайт знакомит с направлениями его работы и структурой материалов.')},
  {title:L('Kimler için','Who it is for','Für wen','服务对象','Для кого'),text:L('Ruh sağlığı profesyonelleri, psikolojik danışma ve ilgili alanların öğrencileri ile araştırmacılar için tasarlanmıştır. Alanı tanımak isteyen okurlar da kaynaklara erişebilir. İçeriklere erişim, mesleki uygulama yeterliği kazandırmaz; kişiye özel yardım veya kriz hizmeti sunulmaz.','Designed for mental health professionals, counseling and related-field students, and researchers. Interested readers may also explore resources. Access does not confer practice competence, personalized support or crisis care.','Für Fachpersonen im Bereich psychischer Gesundheit, Studierende der Beratung und verwandter Fächer sowie Forschende. Interessierte können ebenfalls lesen. Zugriff verleiht keine berufliche Kompetenz und bietet keine individuelle Hilfe oder Krisenversorgung.','面向心理健康专业人员、心理咨询及相关领域学生与研究者，也欢迎希望了解本领域的读者。访问内容不授予专业执业能力，也不提供个体支持或危机服务。','Для специалистов по психическому здоровью, студентов консультирования и смежных направлений и исследователей. Ресурсы доступны и заинтересованным читателям. Доступ не даёт профессиональной квалификации, индивидуальной помощи или кризисной поддержки.')},
  {title:L('Birlikte tutulan üç sorumluluk','Three connected responsibilities','Drei verbundene Verantwortlichkeiten','三项相互关联的责任','Три взаимосвязанные ответственности'),text:L('Danışanın kendi anlamı, araştırmanın gerçekten desteklediği iddia ve uygulayıcının mesleki sınırı birlikte düşünülür. Dini ve din dışı dünya görüşleri tek bir hiyerarşiye yerleştirilmez. Farklı görüşlerin varlığı, her uygulamanın bilimsel veya etik bakımdan eşdeğer olduğu iddiasına dönüştürülmez.','The person’s own meaning, the claim actually supported by research, and the practitioner’s professional limits are considered together. Religious and nonreligious worldviews are not ranked in a single hierarchy. Diversity does not imply that every practice is scientifically or ethically equivalent.','Persönlicher Sinn, tatsächlich belegte Aussagen und berufliche Grenzen werden gemeinsam betrachtet. Religiöse und nichtreligiöse Weltanschauungen werden nicht hierarchisiert. Vielfalt bedeutet nicht, dass jede Praxis wissenschaftlich oder ethisch gleichwertig ist.','同时考虑个人的意义、研究实际支持的主张以及专业人员的能力边界。不将宗教与非宗教世界观排列成单一等级，也不把多样性等同于所有实践在科学或伦理上等价。','Личный смысл, реально подтверждённое утверждение и профессиональные границы рассматриваются вместе. Религиозные и нерелигиозные взгляды не ранжируются в единой иерархии. Разнообразие не означает научной или этической равноценности любой практики.')},
  {title:L('Sonraki adımlar','Next steps','Nächste Schritte','后续工作','Дальнейшие шаги'),text:L('Merkeze ilişkin kurumsal bilgiler yalnızca yetkili onayla yayımlanır.','Institutional information about the center is published only with authorized approval.','Institutionelle Angaben zum Zentrum werden nur mit autorisierter Freigabe veröffentlicht.','中心的机构信息仅在获得授权批准后发布。','Институциональная информация о центре публикуется только с разрешения уполномоченных лиц.')}
 ],
 editorial:[
  {title:L('İddia ve kaynak aynı kayıt içinde','Claim and source in the same record','Aussage und Quelle in einem Eintrag','在同一条目中记录主张与来源','Утверждение и источник в одной записи'),text:L('Her dosya kaynaklarını ve yorum sınırını gösterir. Kaynağın kimliği ile erişilen metnin iddiayı desteklemesi ayrı denetlenir. Dosyalar editoryal metinlerdir; dış kaynaklar MARSAM yayını gibi sunulmaz. IAPOS kanonunun ilgili iddia, atıf, dil ve onay ayrımları içerik tasarımına aktarılmıştır.','Each dossier shows sources and interpretive boundaries. Source identity and direct support are checked separately. Dossiers are editorial texts; external sources are not represented as MARSAM publications. Relevant IAPOS distinctions between claims, citations, language and authorization inform the content design.','Jedes Dossier zeigt Quellen und Aussagegrenzen. Identität und direkte Belegkraft werden getrennt geprüft. Die Dossiers sind redaktionelle Texte; externe Quellen gelten nicht als MARSAM-Publikationen. IAPOS-Unterscheidungen zu Aussage, Beleg, Sprache und Freigabe prägen das Inhaltsmodell.','每个专题显示来源与解释边界，分别核查来源身份及直接支持。专题内容为编辑文本，外部来源不被视作 MARSAM 出版物。内容设计采用 IAPOS 对主张、引用、语言与授权的相关区分。','Каждое досье показывает источники и границы выводов. Идентичность и прямое обоснование проверяются отдельно. Досье являются редакционными текстами; внешние источники не выдаются за публикации MARSAM. В модели учтены различия IAPOS между утверждением, ссылкой, языком и разрешением.')},
  {title:L('Yayın öncesi önerilen süreç','Proposed pre-publication process','Vorgeschlagener Freigabeprozess','拟议的发布前流程','Предлагаемый процесс до публикации'),text:L('Taslak hazırlanır. Kaynak kimliği, iddia desteği, haklar ve güncellik kontrol edilir. Bilimsel içerik ve çeviri ayrı incelenir. Sorumlu kişi belirli sürümü onaylar. Maddi değişiklikte önceki onay yeni sürüme kendiliğinden aktarılmaz. Çeviriler yapay zekâ desteğiyle hazırlanmıştır.','Draft, check source identity, support, rights and currency, then review scientific content and translation separately. A responsible person approves a specific version. Material changes do not inherit prior approval automatically. Translations were prepared with AI assistance.','Entwurf, Prüfung von Identität, Beleg, Rechten und Aktualität, dann getrennte fachliche und sprachliche Prüfung. Eine verantwortliche Person gibt eine bestimmte Version frei. Wesentliche Änderungen übernehmen alte Freigaben nicht automatisch. Die Übersetzungen wurden mit KI-Unterstützung erstellt.','先形成草稿，核查身份、支持、权利与时效，再分别进行学术及翻译审核。责任人批准具体版本。实质修改不会自动继承旧批准。译文在人工智能辅助下完成。','Черновик, проверка идентичности, поддержки, прав и актуальности, затем отдельная научная и языковая проверка. Ответственный одобряет конкретную версию. Существенные изменения не наследуют одобрение автоматически. Переводы подготовлены с помощью ИИ.')},
  {title:L('Açık erişim, açık izin demek değildir','Accessible is not automatically reusable','Zugänglich heißt nicht frei nachnutzbar','可访问不等于可自由再用','Доступность не означает свободное использование'),text:L('Kitap bölümleri, ölçekler, görseller ve videolar hakları doğrulanmadan yeniden yayımlanmaz. Başlangıç koleksiyonu özgün kaynağa bağlantı verir. Kaynak açıklamaları yeni editoryal metindir. FICA gibi özel kısıtları bulunan araçlarda çeviri veya puanlama özelliği yoktur. Yayımlanmamış özel dosyalar bu depoya aktarılmamıştır.','Chapters, instruments, images and videos are not republished without rights checks. The initial collection links to original sources. Descriptions are new editorial text. Restricted tools such as FICA have no translation or scoring feature here. Unpublished private files have not been transferred to this repository.','Kapitel, Instrumente, Bilder und Videos werden ohne Rechteprüfung nicht erneut veröffentlicht. Die Sammlung verlinkt Originalquellen; Beschreibungen sind neue redaktionelle Texte. Eingeschränkte Instrumente wie FICA werden weder übersetzt noch ausgewertet. Private unveröffentlichte Dateien wurden nicht in dieses Repository übertragen.','未经权利核查，不再发布章节、工具、图片或视频。首批资源链接到原始来源，说明文本为新写的编辑内容。FICA 等受限工具不提供翻译或评分功能，未将非公开私人文件转入本仓库。','Главы, инструменты, изображения и видео не переиздаются без проверки прав. Подборка ссылается на оригиналы, описания написаны заново. Для ограниченных инструментов вроде FICA нет функции перевода или оценки. Неопубликованные частные файлы не перенесены в репозиторий.')},
  {title:L('Gizlilik ve erişilebilirlik','Privacy and accessibility','Datenschutz und Zugänglichkeit','隐私与无障碍','Конфиденциальность и доступность'),text:L('Site hesabı, çerez takibi veya üçüncü taraf analitiği yoktur. Okuma listesi, yalnız kullanıcı kaydettiğinde tarayıcısında tutulur. Arama aynı sitedeki dizinde çalışır. Dış kaynağa gidildiğinde o sitenin koşulları geçerlidir. Klavye ile gezinme, görünür odak, hareket azaltma ve mobil düzen desteklenir. Bu bir bağımsız erişilebilirlik sertifikası değildir.','No accounts, tracking cookies or third-party analytics. Reading lists stay in the browser only when saved by the user. Search uses this site’s index. External sites have their own conditions. Keyboard navigation, visible focus, reduced motion and mobile layout are supported. This is not independent accessibility certification.','Keine Konten, Tracking-Cookies oder externen Analysedienste. Leselisten bleiben nach bewusstem Speichern im Browser. Suche nutzt den eigenen Index. Externe Websites haben eigene Bedingungen. Tastaturbedienung, sichtbarer Fokus, reduzierte Bewegung und mobiles Layout werden unterstützt. Keine unabhängige Barrierefreiheitszertifizierung.','无账户、追踪 Cookie 或第三方分析。阅读清单仅在用户主动保存后存于浏览器。搜索使用本站索引，外部网站适用各自条件。支持键盘导航、可见焦点、减少动态效果与移动布局，但不构成独立无障碍认证。','Нет аккаунтов, отслеживающих cookie или сторонней аналитики. Список сохраняется в браузере только по действию пользователя. Поиск использует индекс сайта. У внешних сайтов свои условия. Поддерживаются клавиатура, видимый фокус, уменьшение анимации и мобильная вёрстка. Это не независимая сертификация доступности.')},
  {title:L('Düzeltme ve sürüm kaydı','Corrections and version history','Korrekturen und Versionsverlauf','更正与版本历史','Исправления и история версий'),text:L('Kaynak kimliği, yorum, çeviri veya bağlantıda sorun bulunduğunda kayıt yeniden incelenir. Eski ve yeni sürüm Git geçmişinde ayrılır. İzin veya destek sorunu çözülemeyen materyal onaylı yayına yükseltilmez. Katkı aracı yalnız yerel bir öneri dosyası oluşturur; gizli bir başvuru sistemi değildir.','Identity, interpretation, translation or link issues prompt a new review. Git history distinguishes old and new versions. Material with unresolved rights or support issues is not promoted to approved publication. The contribution tool creates a local proposal only; it is not a private submission service.','Probleme mit Identität, Deutung, Übersetzung oder Links führen zur erneuten Prüfung. Git trennt alte und neue Versionen. Ungeklärte Rechte oder Belege verhindern die Freigabe. Das Beitragswerkzeug erzeugt nur einen lokalen Vorschlag, kein vertrauliches Einreichungssystem.','若身份、解释、翻译或链接出现问题，应重新审核。Git 历史区分新旧版本。权利或支持问题未解决的材料不升级为获批出版物。贡献工具只生成本地提案，并非保密投稿系统。','Проблемы идентичности, интерпретации, перевода или ссылок требуют новой проверки. Git различает версии. Неразрешённые вопросы прав или доказательств препятствуют одобрению. Инструмент предложений создаёт локальный файл, а не конфиденциальную систему подачи.')}
 ]
};
export const researchAreas=[
 {title:L('Danışan tercihi ve danışma süreci','Client preferences and counseling processes','Präferenzen und Beratungsprozesse','来访者偏好与咨询过程','Предпочтения и процессы консультирования'),text:L('Tercihin nasıl öğrenildiği, uygulamanın nasıl deneyimlendiği ve iki tarafın değerlendirmelerinin nasıl ayrıldığı üzerine geliştirilebilecek sorular. Aktif bir çalışma veya veri toplama duyurusu değildir.','Questions to develop about how preferences are learned, practice is experienced and the two parties’ accounts differ. Not an active study or recruitment announcement.','Mögliche Fragen zur Erfassung von Präferenzen, zum Erleben der Praxis und zu unterschiedlichen Perspektiven. Keine laufende Studie oder Rekrutierung.','可围绕偏好如何被了解、实践如何被体验及双方视角如何不同发展问题。不是进行中的研究或招募。','Вопросы о выявлении предпочтений, переживании практики и различии оценок сторон. Не действующее исследование и не набор участников.'),article:'understanding-spiritual-experience'},
 {title:L('Ölçme, dil ve kültürel bağlam','Measurement, language and cultural context','Messung, Sprache und kultureller Kontext','测量、语言与文化情境','Измерение, язык и культурный контекст'),text:L('Yapı tanımları, çeviri/uyarlama kökeni ve ölçme araçlarının hedef kullanımına ilişkin bir araştırma gündemi. Yeni ölçek, izin veya geçerlik sonucu ileri sürülmez.','An agenda on construct definitions, translation/adaptation provenance and intended uses of instruments. No new scale, permission or validity finding is claimed.','Eine Agenda zu Konstrukten, Übersetzungsherkunft und Einsatzzwecken. Keine neue Skala, Erlaubnis oder Validitätsaussage.','关于构念定义、翻译适配来源及工具用途的议程。不声称已有新量表、授权或效度结果。','Повестка о конструктах, происхождении переводов и назначении инструментов. Новые шкалы, разрешения и валидность не заявляются.'),article:'assessment-and-permission'},
 {title:L('Dijital araçlar ve mesleki sorumluluk','Digital tools and professional responsibility','Digitale Werkzeuge und berufliche Verantwortung','数字工具与专业责任','Цифровые инструменты и профессиональная ответственность'),text:L('Yapay zekâ destekli bilgi üretiminde kaynak, mahremiyet, insan denetimi ve klinik iddianın sınırlarını incelemek için önerilen alan. Klinik yapay zekâ ürünü sunulmaz.','A proposed area examining sources, privacy, human oversight and the limits of clinical claims in AI-assisted knowledge work. No clinical AI product is offered.','Vorgeschlagenes Feld zu Quellen, Privatsphäre, Aufsicht und klinischen Aussagegrenzen bei KI-gestützter Wissensarbeit. Kein klinisches KI-Produkt.','拟研究人工智能辅助知识工作中的来源、隐私、人工监督及临床主张边界。不提供临床人工智能产品。','Предлагаемое направление о ссылках, приватности, надзоре и клинических утверждениях при использовании ИИ. Клинический ИИ-продукт не предлагается.'),article:'digital-tools-and-responsibility'}
];
export const participationFields=[
 L('Araştırmacı ve kurum sorumluluğu','Researcher and institutional responsibility','Forschungs- und Institutionsverantwortung','研究者与机构责任','Ответственность исследователя и организации'),
 L('Etik onay ve gerekli izinlerin kaydı','Ethics approval and required permissions','Ethikfreigabe und erforderliche Erlaubnisse','伦理批准与必要许可记录','Этическое одобрение и необходимые разрешения'),
 L('Dahil edilme koşulları ve gönüllü onam','Eligibility and voluntary informed consent','Teilnahmebedingungen und freiwillige Einwilligung','纳入条件与自愿知情同意','Критерии участия и добровольное информированное согласие'),
 L('Veri sorumlusu, saklama ve silme planı','Data responsibility, retention and deletion','Datenverantwortung, Speicherung und Löschung','数据责任、保存与删除计划','Ответственность за данные, хранение и удаление'),
 L('Araştırmadan çekilme ve iletişim yolu','Withdrawal and contact pathway','Rückzug und Kontaktweg','退出研究与联系方式','Выход из исследования и канал связи'),
 L('Katılım yükü, olası riskler ve kapsam','Participation burden, possible risks and scope','Aufwand, mögliche Risiken und Umfang','参与负担、潜在风险与范围','Нагрузка, возможные риски и объём участия')
];
export const conceptCards=[
 {title:L('Manevi yaşantı','Spiritual experience','Spirituelles Erleben','灵性经验','Духовный опыт'),text:L('Kişi neye anlam veriyor, bu alanı nasıl adlandırıyor?','What is meaningful to the person, and how do they name it?','Was ist der Person bedeutsam und wie benennt sie es?','个体赋予什么以意义，又如何称呼这种经验？','Что значимо для человека и как он это называет?'),article:'understanding-spiritual-experience'},
 {title:L('Danışan tercihi','Client preference','Präferenz der Klient:innen','来访者偏好','Предпочтение клиента'),text:L('Konuyu açmak, konuşmayı istemek ve bir uygulamayı seçmek ayrı mı?','Are raising a topic, wanting discussion and choosing a practice distinct?','Sind Ansprechen, Gesprächswunsch und Praxiswahl getrennt?','提起主题、愿意讨论与选择某种实践是否不同？','Различаются ли упоминание темы, желание обсудить и выбор практики?'),article:'preferences-and-boundaries'},
 {title:L('Dünya görüşü','Worldview','Weltanschauung','世界观','Мировоззрение'),text:L('Kendi yorumumuz, kişinin açıklamasına ne zaman baskın geliyor?','When does our interpretation overshadow the person’s account?','Wann überlagert unsere Deutung die Erklärung der Person?','我们的解释何时盖过了当事人的表述？','Когда наша интерпретация заслоняет рассказ человека?'),article:'culture-and-worldviews'},
 {title:L('Kanıt ve yorum','Evidence and interpretation','Evidenz und Deutung','证据与解释','Доказательство и интерпретация'),text:L('Kaynağın bulgusu ile okurun çıkarımı nerede ayrılıyor?','Where does the finding end and the reader’s inference begin?','Wo endet der Befund und beginnt die eigene Folgerung?','研究结果在哪里结束，读者推断又从哪里开始？','Где заканчивается результат и начинается вывод читателя?'),article:'reading-evidence'},
 {title:L('Ölçme ve uyarlama','Measurement and adaptation','Messung und Anpassung','测量与适配','Измерение и адаптация'),text:L('Çeviri, izin ve hedef kullanım için kanıt birbirinden ayrı mı?','Are translation, permission and evidence for intended use distinct?','Sind Übersetzung, Erlaubnis und Nutzungsevidenz getrennt?','翻译、许可与预期用途证据是否分别处理？','Различаются ли перевод, разрешение и доказательства для применения?'),article:'assessment-and-permission'},
 {title:L('Kuramsal bütünleştirme','Theoretical integration','Theoretische Integration','理论整合','Теоретическая интеграция'),text:L('Bir yaklaşımı taşırken hangi varsayımları koruyoruz?','Which assumptions do we preserve when transferring an approach to a new context?','Welche Annahmen bleiben bei einer Integration erhalten?','整合一种取向时保留了哪些假设？','Какие предпосылки сохраняются при интеграции подхода?'),article:'theory-and-integration'}
];
export const approachMap=[
 [L('Bilişsel ve davranışsal yaklaşımlar','Cognitive and behavioral approaches','Kognitive und verhaltensorientierte Ansätze','认知与行为取向','Когнитивные и поведенческие подходы'),L('İnanç içeriği ile düşünmenin işlevini nasıl ayırıyoruz?','How do we distinguish belief content from the function of thinking?','Wie trennen wir Glaubensinhalte und Denkfunktionen?','如何区分信仰内容与思维功能？','Как различать содержание убеждения и функцию мышления?')],
 [L('Kabul ve değer odaklı yaklaşımlar','Acceptance and values-focused approaches','Akzeptanz- und werteorientierte Ansätze','接纳与价值取向','Подходы, основанные на принятии и ценностях'),L('Değerler danışanın diliyle nasıl öğreniliyor?','How are values explored in the client’s own terms?','Wie werden Werte in der Sprache der Person erschlossen?','如何用当事人的语言了解价值？','Как узнавать ценности на языке самого человека?')],
 [L('Varoluşçu ve anlam odaklı okumalar','Existential and meaning-focused readings','Existenzielle und sinnorientierte Lektüren','存在与意义取向阅读','Экзистенциальные и смысловые прочтения'),L('Anlam arayışıyla manevi anlamı ne zaman aynı sayıyoruz?','When do we equate searching for meaning with spiritual meaning?','Wann setzen wir Sinnsuche mit spirituellem Sinn gleich?','何时把寻找意义等同于灵性意义？','Когда поиск смысла отождествляется с духовным смыслом?')],
 [L('Kişi merkezli ve ilişkisel okumalar','Person-centered and relational readings','Personzentrierte und relationale Lektüren','人本与关系取向阅读','Личностно-центрированные и реляционные прочтения'),L('Danışanın açıklaması terapistin yorumunu değiştirebiliyor mu?','Can the client’s account change the therapist’s interpretation?','Kann die Erklärung der Person die therapeutische Deutung ändern?','来访者的解释能否改变咨询师的理解？','Может ли рассказ человека изменить интерпретацию терапевта?')],
 [L('Öyküsel ve kültürel okumalar','Narrative and cultural readings','Narrative und kulturelle Lektüren','叙事与文化取向阅读','Нарративные и культурные прочтения'),L('Bir anlatının anlamını kim belirliyor?','Who determines the meaning of a narrative?','Wer bestimmt die Bedeutung einer Erzählung?','谁决定一种叙事的意义？','Кто определяет смысл повествования?')],
 [L('Dinî yönelimli ve karşılaştırmalı modeller','Religiously oriented and comparative models','Religiös orientierte und vergleichende Modelle','宗教取向与比较模型','Религиозно ориентированные и сравнительные модели'),L('Modelin varsayımı ile danışanın tercihi nasıl ayrılıyor?','How are model assumptions separated from client preferences?','Wie werden Modellannahmen von den Präferenzen der Klientin oder des Klienten getrennt?','如何区分模型假设与来访者偏好？','Как отделить предпосылки модели от предпочтений клиента?')]
];
