import copy from './ui-copy.json' with {type:'json'};
import {createHash} from 'node:crypto';
import {locales} from './languages.mjs';

export const messages = copy;
export function message(id, locale) {
  const value = copy[id]?.[locale];
  if (!locales.includes(locale) || typeof value !== 'string' || !value.trim()) {
    throw new Error(`Missing stable message ${id} in ${locale}`);
  }
  return value;
}
function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (value && typeof value === 'object') return Object.fromEntries(Object.keys(value).sort().map(k => [k, canonical(value[k])]));
  return value;
}
export function digest(value) {
  return createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');
}
/** Review records are evidence, not authorization generated by a software flag. */
export function translationRecord(id, locale, source, target, review = null) {
  const sourceHash = digest(source), targetHash = digest(target);
  const changed = review && (review.sourceHash !== sourceHash || review.targetHash !== targetHash);
  const approved = !changed && review?.status === 'reviewed' && !!review?.reviewedBy?.trim() && /^\d{4}-\d{2}-\d{2}$/.test(review?.reviewedAt || '');
  return {id, locale, sourceHash, targetHash, status:changed?'outdated':approved?'reviewed':'draft',
    humanReviewed:Boolean(approved), reviewedBy:approved?review.reviewedBy:null, reviewedAt:approved?review.reviewedAt:null,
    method:'AI_ASSISTED_DRAFT', direction:locale==='ar'?'rtl':'ltr'};
}
for (const id of Object.keys(copy)) for (const locale of locales) message(id,locale);
