import {books,recentPapers,publicationRecords} from './publications-data.mjs';
import {h} from './heritage-copy.mjs';
import {langTags} from './languages.mjs';
import {labels} from './catalogue.mjs';
import {message} from './messages.mjs';
import {escapeHTML as e,route,normalizeText} from './lib.mjs';
import {shell} from './chrome.mjs';
import {icon,resourceURL} from './ui.mjs';

const textLink=(url,text,cls='text-link')=>`<a class="${cls}" href="${url}">${e(text)} ${icon('arrow')}</a>`;
export function dateText(date,l){
 const parts=date.split('-').map(Number);if(parts.length===1)return date;
 return new Intl.DateTimeFormat(langTags[l],{year:'numeric',month:'long',...(parts.length===3?{day:'numeric'}:{})}).format(new Date(Date.UTC(parts[0],parts[1]-1,parts[2]||1,12)));
}
const recordLink=(p,l,b)=>resourceURL(l,p.id,b);
function people(p,l,short=false){const d=p.bibliography,arr=d.authors.length?d.authors:d.editors;return `${d.authors.length?'':h[d.editors.length>1?'editors':'editor'][l]+'. '}${arr.map(e).join(', ')}`;}
export function bookCard(p,l,b,filterable=false){
 const d=p.bibliography;
 return `<article class="book-object" ${filterable?filterAttrs(p,l):''}><a class="book-cover-link" href="${recordLink(p,l,b)}" aria-label="${e(p.display[l])}"><img src="${b}${d.cover}" width="212" height="300" loading="lazy" decoding="async" alt="" class="book-cover"></a><div class="book-description"><div class="book-imprint"><span>${e(d.publisher.replace(' Yayıncılık','').replace(' Yayınları',''))}</span><time datetime="${d.date}">${p.year}</time></div><h3>${textLink(recordLink(p,l,b),p.display[l],'book-title')}</h3><p class="book-credit" dir="auto">${people(p,l)}</p><p class="book-edition">${e(h.edition[l])} ${e(d.edition)}${d.editionUpdated?' · '+e(h.updated[l]):''}</p>${filterable?`<p class="book-synopsis">${e(p.summary[l])}</p><p class="bibliography-isbn" dir="ltr">ISBN ${e(d.isbn)}</p>`:''}</div></article>`;
}
export function paperCard(p,l,b,filterable=false,index=0){
 const d=p.bibliography;
 return `<article class="research-record" ${filterable?filterAttrs(p,l):''}><div class="research-record-date"><span class="folio" aria-hidden="true">${String(index+1).padStart(2,'0')}</span><time datetime="${d.date}">${e(dateText(d.date,l))}</time></div><div class="research-record-main"><span class="research-journal" dir="ltr">${e(d.journal)}</span><h3>${textLink(recordLink(p,l,b),p.display[l],'research-title')}</h3><p class="research-authors" dir="ltr">${e(d.authors.join(', '))}</p><p>${e(p.summary[l])}</p>${filterable?`<details class="record-original"><summary>${e(h.record[l])}</summary><p lang="${p.language}" dir="auto">${e(p.title)}</p><p class="record-limits">${e(d.note[l])}</p><a class="text-link" href="https://doi.org/${e(d.doi)}" target="_blank" rel="noopener noreferrer"><span dir="ltr">DOI ${e(d.doi)}</span>${icon('external')}</a></details>`:''}<div class="research-record-bottom">${textLink(recordLink(p,l,b),labels[l].viewRecord)}<span dir="ltr">${d.volume?e(d.volume)+(d.issue?'('+e(d.issue)+')':''):d.issue?e(d.issue):e(h.onlineFirst[l])}</span></div></div></article>`;
}
function filterAttrs(p,l){const d=p.bibliography;return `data-bib-record data-identifiers="${e(JSON.stringify([d.doi,d.isbn].filter(Boolean)))}" data-year="${p.year}" data-authors="${e(JSON.stringify([...d.authors,...d.editors,...d.contributors||[]]))}" data-search="${e(normalizeText(p.title+' '+Object.values(p.display).join(' ')+' '+[...d.authors,...d.editors,...d.contributors||[]].join(' ')+' '+Object.values(p.summary).join(' ')+' '+(d.doi||'')+' '+(d.isbn||'')+' '+(d.isbn||'').replaceAll('-',''),l))}"`;}
export function recentFeature(l,b){const p=recentPapers[0],d=p.bibliography,book=books[0];return `
<section class="wide section recent-research" aria-labelledby="recent-title">
 <div class="editorial-section-heading"><div><span class="eyebrow">2025 / 2026</span><h2 id="recent-title">${e(h.publications[l])}</h2></div><div><p>${e(h.publicationsLead[l])}</p>${textLink(route(l,'publications',b),h.allPapers[l])}</div></div>
 <div class="research-feature-layout"><article class="research-lead"><div class="research-lead-meta"><span>${e(h.latest[l])}</span><time datetime="${d.date}">${e(dateText(d.date,l))}</time></div><div class="research-lead-copy"><span class="eyebrow" dir="ltr">${e(d.journal)}</span><h3>${textLink(recordLink(p,l,b),p.display[l],'research-title')}</h3><p>${e(p.summary[l])}</p><p class="research-authors" dir="ltr">${e(d.authors.join(', '))}</p></div>${textLink(recordLink(p,l,b),labels[l].viewRecord,'text-link pale')}<img src="${b}assets/heritage/rosette.svg" alt="" aria-hidden="true" class="research-rosette" width="220" height="220" loading="lazy"></article>
 <article class="new-book-feature"><span class="eyebrow">${e(h.newBook[l])} · 2026</span><a class="new-book-cover" href="${recordLink(book,l,b)}" aria-label="${e(book.display[l])}"><img src="${b}${book.bibliography.cover}" alt="" width="207" height="300" loading="lazy"></a><h3>${textLink(recordLink(book,l,b),book.display[l],'book-title')}</h3><p>${people(book,l)}</p>${textLink(recordLink(book,l,b),labels[l].viewRecord)}</article></div>
 <div class="recent-research-pair">${recentPapers.slice(1,3).map((p,i)=>paperCard(p,l,b,false,i+1)).join('')}</div>
</section>`;}
export function booksFeature(l,b){const selection=['spiritual-counselling-book','theories-book','techniques-101','group-counselling','discovering-spirituality','cbt-spiritual'].map(id=>books.find(p=>p.id===id));return `<section class="book-room"><div class="wide section"><div class="editorial-section-heading"><div><span class="eyebrow">${e(h.selection[l])}</span><h2>${e(h.books[l])}</h2></div><div><p>${e(h.booksLead[l])}</p>${textLink(route(l,'books',b),h.allBooks[l])}</div></div><div class="book-gallery">${selection.map(p=>bookCard(p,l,b)).join('')}</div></div></section>`;}
export function bibliographyPage(l,b,type){
 const isBook=type==='books',items=isBook?books:recentPapers,title=h[type][l],lead=h[type+'Lead'][l];
 const names=[...new Set(items.flatMap(p=>[...p.bibliography.authors,...p.bibliography.editors,...p.bibliography.contributors||[]]))].sort((a,b)=>a.localeCompare(b,langTags[l],{numeric:true,sensitivity:'base'}));
 const years=[...new Set(items.map(p=>p.year))].sort((a,b)=>b-a);
 const filters=`<form class="bibliography-filters" action="${route(l,type,b)}" method="get" data-bib-form><div class="field bib-query"><label for="bib-q">${e(h.search[l])}</label><input id="bib-q" name="q" type="search" maxlength="160" dir="auto" data-bib-query></div><div class="field"><label for="bib-author">${e(h.authorFilter[l])}</label><select id="bib-author" name="author" data-bib-author><option value="">${e(h.allAuthors[l])}</option>${names.map(n=>`<option value="${e(n)}">${e(n)}</option>`).join('')}</select></div><div class="field"><label for="bib-year">${e(h.year[l])}</label><select id="bib-year" name="year" data-bib-year><option value="">${e(h.allYears[l])}</option>${years.map(y=>`<option value="${y}">${y}</option>`).join('')}</select></div><button class="text-button" type="reset">${e(h.reset[l])}</button></form>`;
 return shell(l,type,title,lead,`<section class="wide page-intro bibliography-intro"><div class="breadcrumbs"><a href="${route(l,'',b)}">${e(labels[l].home)}</a><span aria-hidden="true">/</span><span>${e(title)}</span></div><span class="eyebrow">${e(h.selection[l])} · 01.10.2026</span><h1>${e(title)}</h1><p class="page-deck">${e(lead)}</p><div class="publication-switch">${textLink(route(l,'publications',b),h.publications[l],!isBook?'active':'')}${textLink(route(l,'books',b),h.books[l],isBook?'active':'')}</div></section><section class="wide section bibliography-page" data-bibliography data-results-label="${e(h.results[l])}"><noscript><p class="notice">${e(message('nojs.filter',l))}</p></noscript>${filters}<p class="input-help">${e(message('catalogue.roleHint',l))}</p>${isBook?`<fieldset class="view-switch" data-view-switch hidden><legend>${e(message('catalogue.views',l))}</legend><button type="button" data-view="covers" aria-pressed="true">${e(message('catalogue.covers',l))}</button><button type="button" data-view="list" aria-pressed="false">${e(message('catalogue.list',l))}</button></fieldset>`:''}<p class="bibliography-count" role="status" aria-live="polite" data-bib-count>${items.length} ${e(h.results[l])}</p><p class="bibliography-empty" data-bib-empty hidden>${e(h.noResults[l])}</p><div class="${isBook?'book-gallery books-full':'research-index'}">${items.map((p,i)=>isBook?bookCard(p,l,b,true):paperCard(p,l,b,true,i)).join('')}</div><div class="bibliography-scope"><p>${e(h.scope[l])}</p>${isBook?`<p>${e(h.sourceLanguage[l])}</p>`:''}</div></section>`,b);
}
export function bibliographyDetail(source,l,b){
 const d=source.bibliography;if(!d)return '';
 const fields=[[h.published[l],dateText(d.date,l)],...(d.type==='book'?[[h.publisher[l],d.publisher],[h.edition[l],d.edition+(d.editionUpdated?' · '+h.updated[l]:'')],[h.pages[l],d.pages],['ISBN',d.isbn]]:[[h.journal[l],d.journal],[h.volume[l],[d.volume,d.issue].filter(Boolean).join(' / ')],[h.pages[l],d.pages],['DOI',d.doi]])];
 return `<section class="bibliographic-detail"><dl class="bibliographic-grid">${fields.filter(([,v])=>v).map(([k,v])=>`<div><dt>${e(k)}</dt><dd dir="auto">${e(v)}</dd></div>`).join('')}</dl>${d.authors?.length?`<div class="bibliographic-people"><h3>${e(h.authors[l])}</h3><p dir="ltr">${e(d.authors.join(', '))}</p></div>`:''}${d.editors?.length?`<div class="bibliographic-people"><h3>${e(h[d.editors.length>1?'editors':'editor'][l])}</h3><p dir="ltr">${e(d.editors.join(', '))}</p></div>`:''}${d.contributors?.length?`<details class="record-original"><summary>${e(h.contributors[l])}</summary><p dir="ltr">${e(d.contributors.join(', '))}</p></details>`:''}<p class="bibliographic-note">${e(d.note[l])}</p>${d.type==='book'&&l!=='tr'?`<p class="bibliographic-note">${e(h.sourceLanguage[l])}</p>`:''}</section>`;
}
