/** Academic entry points, not partners or evidence of intervention efficacy. */
import {locales} from './languages.mjs';
const all = (tr,en,de,zh,ru,ar,id,ms) => Object.fromEntries(locales.map((l,i)=>[l,[tr,en,de,zh,ru,ar,id,ms][i]]));
export const regionalSources = [
 {id:'s-ukm-counselling',title:'The Islamic counselling approach in addressing anxiety among adolescents in higher education institutions (HEIs)',year:2024,url:'https://spaj.ukm.my/jalhikmah/index.php/jalhikmah/article/view/514',citation:'Sazali, N. A., & Hanin Hamjah, S. (2024). The Islamic counselling approach in addressing anxiety among adolescents in higher education institutions (HEIs). Al-Hikmah, 16(1), 153–172. https://doi.org/10.17576/alhikmah.2024.161/514',kind:'theory',inspection:'abstract',language:'en',checked:'2026-10-01',level:'V1',status:'PARTIALLY_VERIFIED',access:'Official UKM journal landing page, author names, bibliographic record and abstract inspected. The abstract identifies content analysis of previous studies, articles and scholarly works.',limit:'Literature-based content analysis, not a new clinical trial. Claims about reducing anxiety are not treated as independently established causal effects. Full text, all cited studies and exhaustive correction/retraction checks were not inspected.'},
 {id:'s-uii-pspi',title:'Pusat Studi Psikologi Islam',year:null,url:'https://psychology.uii.ac.id/pusat-studi-psikologi-islam/',citation:'Universitas Islam Indonesia. (n.d.). Pusat Studi Psikologi Islam. Official resource page, accessed 2026-10-01.',kind:'hub',inspection:'official',language:'id',checked:'2026-10-01',level:'V1',status:'PARTIALLY_VERIFIED',access:'Official UII psychology page and its Islamic psychology study-center section inspected. Search-index and fetched versions differ in detail, so this record makes only a narrow institutional-resource identification.',limit:'Institutional resource, not a clinical efficacy study or MARSAM partnership. Current staffing, program availability and accreditation were not audited. No private contact details or protected content copied.'}
];
export const regionalResources = [
 {id:'malaysia-ukm-counselling',sources:['s-ukm-counselling'],kind:'theory',topic:'culture',sections:['library','network','approaches'],review:'draft',translation:'draft',rights:'link-only',approval:null,
 title:all('Malezya · UKM, İslami danışma literatürü','Malaysia · UKM, Islamic counselling literature','Malaysia · UKM, Literatur zur islamischen Beratung','马来西亚 · UKM，伊斯兰咨询文献','Малайзия · UKM, литература об исламском консультировании','ماليزيا · UKM، أدبيات الإرشاد الإسلامي','Malaysia · UKM, literatur konseling Islam','Malaysia · UKM, literatur kaunseling Islam'),
 summary:all('2024 tarihli, önceki yayınlara dayalı içerik analizi. Yeni bir klinik deney değildir. Kaygıyı azaltma konusunda bağımsız nedensel kanıt olarak yorumlanmaz.','A 2024 content analysis of previous publications, not a new clinical trial. It is not treated as independent causal evidence for anxiety reduction.','Inhaltsanalyse früherer Publikationen von 2024, keine neue klinische Studie. Kein unabhängiger Kausalnachweis einer Angstreduktion.','2024年对既有文献的内容分析，并非新的临床试验。不将其视为缓解焦虑的独立因果证据。','Контент-анализ предыдущих публикаций 2024 года, не новое клиническое испытание. Не рассматривается как независимое доказательство причинного снижения тревоги.','تحليل محتوى لمنشورات سابقة، نُشر عام 2024، وليس تجربة سريرية جديدة. لا يُعامل كدليل سببي مستقل على خفض القلق.','Analisis isi publikasi sebelumnya tahun 2024, bukan uji klinis baru. Tidak dianggap sebagai bukti kausal independen tentang penurunan kecemasan.','Analisis kandungan penerbitan terdahulu pada tahun 2024, bukan percubaan klinikal baharu. Tidak dianggap bukti sebab-akibat bebas tentang pengurangan kebimbangan.')},
 {id:'indonesia-uii-psychology',sources:['s-uii-pspi'],kind:'hub',topic:'network',sections:['library','network'],review:'draft',translation:'draft',rights:'link-only',approval:null,
 title:all('Endonezya · UII, İslami Psikoloji Araştırmaları','Indonesia · UII, Islamic Psychology Studies','Indonesien · UII, Islamische Psychologiestudien','印度尼西亚 · UII，伊斯兰心理学研究','Индонезия · UII, исследования исламской психологии','إندونيسيا · UII، دراسات علم النفس الإسلامي','Indonesia · UII, Pusat Studi Psikologi Islam','Indonesia · UII, Pusat Pengajian Psikologi Islam'),
 summary:all('Universitas Islam Indonesia bünyesindeki Pusat Studi Psikologi Islam için resmî kaynak sayfası. Araştırma odağına giriş sağlar, MARSAM ortaklığı veya klinik etkililik iddiası değildir.','Official resource page for UII’s Pusat Studi Psikologi Islam. An academic entry point, not a MARSAM partnership or a clinical efficacy claim.','Offizielle Ressourcenseite des Pusat Studi Psikologi Islam der UII. Akademischer Einstieg, keine MARSAM-Partnerschaft oder klinische Wirksamkeitsaussage.','UII伊斯兰心理学研究中心官方资源页面。作为学术入口，不表示与MARSAM合作，也不作临床疗效主张。','Официальная страница Pusat Studi Psikologi Islam в UII. Академический ресурс, не партнёрство с MARSAM и не утверждение о клинической эффективности.','صفحة رسمية لمركز دراسات علم النفس الإسلامي في UII. مدخل أكاديمي، وليس شراكة مع MARSAM أو ادعاءً بفاعلية سريرية.','Halaman resmi Pusat Studi Psikologi Islam UII. Pintu masuk akademik, bukan kemitraan MARSAM atau klaim efektivitas klinis.','Halaman rasmi Pusat Studi Psikologi Islam UII. Titik permulaan akademik, bukan perkongsian MARSAM atau dakwaan keberkesanan klinikal.')}
];
