/** Academic entry points, not partners or evidence of intervention efficacy. */
import {locales} from './languages.mjs';
const all = (tr,en,de,zh,ru,ar,id,ms) => Object.fromEntries(locales.map((l,i)=>[l,[tr,en,de,zh,ru,ar,id,ms][i]]));
export const regionalSources = [
 {id:'s-ukm-counselling',title:'The Islamic counselling approach in addressing anxiety among adolescents in higher education institutions (HEIs)',year:2024,url:'https://spaj.ukm.my/jalhikmah/index.php/jalhikmah/article/view/514',citation:'Sazali, N. A., & Hanin Hamjah, S. (2024). The Islamic counselling approach in addressing anxiety among adolescents in higher education institutions (HEIs). Al-Hikmah, 16(1), 153–172. https://doi.org/10.17576/alhikmah.2024.161/514',kind:'theory',inspection:'abstract',language:'en',checked:'2026-10-01',level:'V1',status:'PARTIALLY_VERIFIED',access:'Official UKM journal landing page, author names, bibliographic record and abstract inspected. The abstract identifies content analysis of previous studies, articles and scholarly works.',limit:'Literature-based content analysis, not a new clinical trial. Claims about reducing anxiety are not treated as independently established causal effects. Full text, all cited studies and exhaustive correction/retraction checks were not inspected.'},
];
export const regionalResources = [
 {id:'malaysia-ukm-counselling',sources:['s-ukm-counselling'],kind:'theory',topic:'culture',sections:['library','approaches'],review:'draft',translation:'draft',rights:'link-only',approval:null,
 title:all('İslami danışma ve kaygı üzerine literatür incelemesi','Islamic counseling and anxiety: A literature review','Islamische Beratung und Angst. Eine Literaturstudie','伊斯兰咨询与焦虑文献研究','Исламское консультирование и тревога. Анализ литературы','الإرشاد الإسلامي والقلق: مراجعة الأدبيات','Konseling Islam dan kecemasan. Kajian literatur','Kaunseling Islam dan kebimbangan. Kajian literatur'),
 summary:all('2024 tarihli, önceki yayınlara dayalı içerik analizi. Yeni bir klinik deney değildir. Kaygıyı azaltma konusunda bağımsız nedensel kanıt olarak yorumlanmaz.','A 2024 content analysis of previous publications, not a new clinical trial. It is not treated as independent causal evidence for anxiety reduction.','Inhaltsanalyse früherer Publikationen von 2024, keine neue klinische Studie. Kein unabhängiger Kausalnachweis einer Angstreduktion.','2024年对既有文献的内容分析，并非新的临床试验。不将其视为缓解焦虑的独立因果证据。','Контент-анализ предыдущих публикаций 2024 года, не новое клиническое испытание. Не рассматривается как независимое доказательство причинного влияния на снижение тревоги.','تحليل محتوى لمنشورات سابقة، نُشر عام 2024، وليس تجربة سريرية جديدة. لا يُعامل كدليل سببي مستقل على خفض القلق.','Analisis isi publikasi sebelumnya tahun 2024, bukan uji klinis baru. Tidak dianggap sebagai bukti kausal independen tentang penurunan kecemasan.','Analisis kandungan penerbitan terdahulu pada tahun 2024, bukan percubaan klinikal baharu. Tidak dianggap bukti sebab-akibat bebas tentang pengurangan kebimbangan.')}
];
