import {evidenceRecordPanel,instrumentOverview,founderSection,measureProfiles} from './scholarly-view.mjs';
import {scholarlyThemes,evidence,sc} from './scholarship.mjs';
import {researchGuides} from './research-data.mjs';
import {bibliographyDetail} from './publications-view.mjs';
import {locales,langTags,sourceNotes} from './i18n.mjs';
import {labels,sources,resources,sections,topics,typeKeys,articles,learningPaths,overview,campusCopy,sourceById} from './catalogue.mjs';
import {shell} from './chrome.mjs';
import {icon,articleURL,resourceURL,compareButton} from './ui.mjs';
import {message} from './messages.mjs';
import {sourceReviewPanel,identifiersFor} from './provenance.mjs';
export {shell,icon,articleURL,resourceURL,sourceById};
import {researchAreas,participationFields,conceptCards,approachMap} from './info.mjs';
import {escapeHTML as e,route,safeURL,readingMinutes,normalizeText} from './lib.mjs';
export const allSectionIds=sections.map(s=>s.id);
const typeName=(kind,t)=>t[typeKeys[kind]]||t.dossiers;
const ext=(url,text,cls='text-link')=>`<a class="${cls}" href="${e(safeURL(url)||'#')}" target="_blank" rel="noopener noreferrer">${e(text)} ${icon('external')}</a>`;
const chip=(text,cls='')=>`<span class="chip ${cls}">${e(text)}</span>`;
const sourceMeta=(item,l)=>{const s=sourceById[item.sources[0]];return `${s.year?e(s.year)+'<span aria-hidden="true"> · </span>':''}${e(typeName(s.kind,labels[l]))}`;};
const bookButton=(item,l)=>`<button class="save-button" type="button" data-save="${item.id}" aria-pressed="false" aria-label="${e(labels[l].bookmark)}: ${e(item.title[l])}" title="${e(labels[l].bookmark)}">${icon('bookmark')}<span class="save-label">${e(labels[l].bookmark)}</span></button>`;
export function dossierCard(a,l,b,index=0){const t=labels[l];return `<article class="dossier-card" data-card data-topic="${a.topic}" data-kind="dossier" data-search="${e(normalizeText(a.title[l]+' '+a.summary[l],l))}"><div class="card-top"><span class="folio">${String(index+1).padStart(2,'0')}</span>${chip(topics[a.topic][l])}${icon('leaf')}</div><h3><a href="${articleURL(l,a.id,b)}">${e(a.title[l])}</a></h3><p>${e(a.summary[l])}</p><div class="card-bottom"><span>${readingMinutes(a.body[l].map(x=>x.text).join(' '),l)} ${e(t.readingTime)}</span><a class="arrow-link" href="${articleURL(l,a.id,b)}" aria-label="${e(t.read)}: ${e(a.title[l])}">${icon('arrow')}</a></div></article>`;}
export function resourceCard(r,l,b){const t=labels[l];return `<article class="source-card" data-identifiers="${e(JSON.stringify(identifiersFor(sourceById[r.sources[0]])))}" data-card data-topic="${r.topic}" data-kind="${r.kind}" data-search="${e(normalizeText(r.title[l]+' '+r.summary[l]+' '+sourceById[r.sources[0]].title+' '+sourceById[r.sources[0]].citation+' '+identifiersFor(sourceById[r.sources[0]]).join(' '),l))}"><div class="source-icon">${icon(r.kind==='hub'?'globe':r.kind==='measure'?'layers':'file')}</div><div class="source-info"><div class="eyebrow small">${sourceMeta(r,l)}</div><h3><a href="${resourceURL(l,r.id,b)}">${e(r.title[l])}</a></h3><p>${e(r.summary[l])}</p><span class="source-origin" dir="ltr">${e(new URL(sourceById[r.sources[0]].url).hostname)}</span></div><a class="source-arrow" href="${resourceURL(l,r.id,b)}" aria-label="${e(t.viewRecord)}: ${e(r.title[l])}">${icon('arrow')}</a>${compareButton(r.id,l,campusCopy[l])}</article>`;}
const draftNotice=t=>`<div class="review-notice"><span class="chip clay">${e(t.editorialDraft)}</span><p>${e(t.translationNote)}</p></div>`;
const sectionHead=(eyebrow,title,desc,link='',linktext='')=>`<div class="section-heading"><div><span class="eyebrow">${e(eyebrow)}</span><h2>${e(title)}</h2>${desc?`<p>${e(desc)}</p>`:''}</div>${link?`<a class="text-link" href="${link}">${e(linktext)} ${icon('arrow')}</a>`:''}</div>`;
function pageIntro(l,title,summary,b,tag=''){const t=labels[l];return `<div class="wide page-intro"><nav class="breadcrumbs" aria-label="${e(t.home)}"><a href="${route(l,'',b)}">${e(t.home)}</a><span aria-hidden="true">/</span><span>${e(title)}</span></nav><span class="eyebrow">${e(tag||'MARSAM')}</span><h1>${e(title)}</h1><p class="page-deck">${e(summary)}</p></div>`;}
function filterBar(l,items){const t=labels[l];const kinds=[...new Set(items.map(x=>x.kind))];const ts=[...new Set(items.map(x=>x.topic))];return `<form class="filter-bar" data-filter-form><div class="filter-search"><label for="filter-query">${e(t.searchLabel)}</label><div>${icon('search')}<input id="filter-query" dir="auto" type="search" placeholder="${e(t.searchHint)}" maxlength="160" data-filter-q></div></div><div><label for="filter-type">${e(t.sourceType)}</label><select id="filter-type" data-filter-type><option value="">${e(t.allTypes)}</option>${kinds.map(k=>`<option value="${k}">${e(typeName(k,t))}</option>`).join('')}</select></div><div><label for="filter-topic">${e(t.topics)}</label><select id="filter-topic" data-filter-topic><option value="">${e(t.allTopics)}</option>${ts.map(k=>`<option value="${k}">${e(topics[k][l])}</option>`).join('')}</select></div><button class="button compact" type="reset">${e(t.clearFilters)}</button></form><div class="result-meta" aria-live="polite"><span data-filter-count>${items.length}</span> ${e(t.results)}</div>`;}
function infoBlocks(items,l){return `<div class="prose info-prose">${items.map((s,i)=>`<section id="${i===3?'privacy':'section-'+i}"><h2>${e(s.title[l])}</h2><p>${e(s.text[l])}</p></section>`).join('')}</div>`;}
export function sectionPage(id,l,b){const t=labels[l];const s=sections.find(x=>x.id===id);const title=id==='practice'?t.practicePage:id==='search'?t.searchPage:s.title[l];let body='';const aa=articles.filter(a=>a.sections.includes(id));const rr=resources.filter(r=>r.sections.includes(id));
 if(['library','measures','media','network'].includes(id)){body=`${id==='measures'?instrumentOverview(l,b):''}${id==='measures'?`<div class="notice">${icon('circle')}<p>${e(t.rightsNote)}</p></div>`:''}${id==='media'?`<div class="notice">${icon('external')}<p>${e(t.externalMedia)}</p></div>`:''}${id==='network'?`<div class="notice">${icon('globe')}<p>${e(t.noAffiliation)}</p></div>`:''}<section data-filter-scope><noscript><p class="notice">${e(message('nojs.filter',l))}</p></noscript>${filterBar(l,rr)}<div class="source-list">${rr.map(r=>resourceCard(r,l,b)).join('')}</div><p class="empty-state" data-filter-empty hidden>${e(t.noResults)}</p></section>${id==='library'?`<a class="text-link export-ledger" href="${b}data/source-ledger.json" download>${e(t.sourceLedger)} ${icon('arrow')}</a>`:''}${aa.length?`<h2 class="block-title">${e(t.related)}</h2><div class="three-grid">${aa.map((a,i)=>dossierCard(a,l,b,i)).join('')}</div>`:''}`;}
 else if(id==='concepts'){body=`<div class="concept-grid">${conceptCards.map((c,i)=>`<a class="concept-card" href="${articleURL(l,c.article,b)}"><span class="folio">${String(i+1).padStart(2,'0')}</span><h2>${e(c.title[l])}</h2><p>${e(c.text[l])}</p>${icon('arrow')}</a>`).join('')}</div><h2 class="block-title">${e(t.allDossiers)}</h2><div class="three-grid">${articles.map((a,i)=>dossierCard(a,l,b,i)).join('')}</div>`;}
 else if(id==='approaches'){body=`${draftNotice(t)}<div class="two-grid">${aa.map((a,i)=>dossierCard(a,l,b,i)).join('')}</div><h2 class="block-title">${e(t.readingMap)}</h2><p class="muted roomy">${e(t.proposedMap)}</p><div class="approach-grid">${approachMap.map(([name,q],i)=>`<div class="approach-card"><span class="folio">${String(i+1).padStart(2,'0')}</span><h3>${e(name[l])}</h3><p>${e(q[l])}</p><a class="text-link" href="${articleURL(l,'theory-and-integration',b)}">${e(t.readDossier)} ${icon('arrow')}</a></div>`).join('')}</div><h2 class="block-title">${e(t.references)}</h2><div class="source-list">${rr.map(r=>resourceCard(r,l,b)).join('')}</div>`;}
 else if(['practice','ethics','methods'].includes(id)){body=`${draftNotice(t)}<div class="three-grid">${aa.map((a,i)=>dossierCard(a,l,b,i)).join('')}</div><h2 class="block-title">${e(t.references)}</h2><div class="source-list">${rr.map(r=>resourceCard(r,l,b)).join('')}</div>`;}
 else if(id==='learning'){body=`<div class="notice">${icon('book')}<p>${e(t.noProgram)}</p></div><div class="three-grid">${learningPaths.map((p,i)=>`<article class="path-card"><span class="eyebrow">${e(t[p.audience])}</span><span class="path-number">0${i+1}</span><h2>${e(p.title[l])}</h2><p>${e(p.summary[l])}</p><a class="button" href="${route(l,`learning/${p.id}`,b)}">${e(t.open)} ${icon('arrow')}</a></article>`).join('')}</div>`;}
 else if(id==='projects'){body=`<div class="notice">${icon('circle')}<p>${e(t.planned)} · ${e(t.noActiveStudies)}</p></div><div class="three-grid">${researchAreas.map((r,i)=>`<article class="agenda-card"><span class="folio">0${i+1}</span><h2>${e(r.title[l])}</h2><p>${e(r.text[l])}</p><a class="text-link" href="${articleURL(l,r.article,b)}">${e(t.readDossier)} ${icon('arrow')}</a></article>`).join('')}</div><a class="text-link block-link" href="${route(l,'participate',b)}">${e(t.participate)} ${icon('arrow')}</a>`;}
 else if(id==='participate'){body=`<div class="empty-hero">${icon('layers')}<h2>${e(t.noActiveStudies)}</h2><p>${e(t.noActiveStudiesDesc)}</p><a class="button" href="${route(l,'methods',b)}">${e(t.methods)} ${icon('arrow')}</a></div><h2 class="block-title">${e(t.researchChecklist)}</h2><ol class="checklist">${participationFields.map(x=>`<li>${icon('circle')}<span>${e(x[l])}</span></li>`).join('')}</ol>`;}
 else if(id==='about'||id==='editorial'){body=`<div class="info-layout"><aside class="info-aside"><span class="eyebrow">${e(id==='about'?t.previewShort:t.editorialDraft)}</span><p>${e(id==='about'?t.previewNote:t.translationNote)}</p><a class="text-link" href="${route(l,id==='about'?'editorial':'contribute',b)}">${e(id==='about'?t.readPolicy:t.contribute)} ${icon('arrow')}</a></aside>${infoBlocks(overview[id],l)}</div>${id==='about'?founderSection(l,b):''}`;}
 else if(id==='news'){body=`<article class="release-note"><div class="eyebrow"><time datetime="2026-10-01">01.10.2026</time> · ${e(t.previewShort)}</div><h2>${e(t.updatesTitle)}</h2><p>${e(t.updatesText)}</p><a class="text-link" href="${route(l,'editorial',b)}">${e(t.readPolicy)} ${icon('arrow')}</a></article><h2 class="block-title">${e(t.readings)}</h2><div class="three-grid">${articles.filter(a=>['culture-and-worldviews','question-to-design','digital-tools-and-responsibility'].includes(a.id)).map((a,i)=>dossierCard(a,l,b,i)).join('')}</div>`;}
 else if(id==='contribute'){body=`<div class="contribution-layout"><div><div class="notice">${icon('circle')}<p>${e(t.contributeIntro)}</p></div><form class="contribution-form" data-draft-form><div class="error-summary" data-error-summary tabindex="-1" role="alert" hidden><h2>${e(message('form.errors',l))}</h2><ul></ul></div><div class="field"><label for="draft-title">${e(t.fieldTitle)}</label><input id="draft-title" dir="auto" required maxlength="140" autocomplete="off"></div><div class="field"><label for="draft-url">${e(t.fieldURL)}</label><input id="draft-url" dir="ltr" type="url" required maxlength="600" autocomplete="off" placeholder="https://"></div><div class="field"><label for="draft-note">${e(t.fieldNote)}</label><textarea id="draft-note" dir="auto" required maxlength="1200" rows="6" aria-describedby="note-help"></textarea><p class="input-help" id="note-help">${e(t.fieldNoteHelp)}</p></div><label class="checkbox-label"><input id="draft-confirm" type="checkbox" required><span>${e(t.fieldConfirm)}</span></label><button type="submit" class="button" data-requires-js hidden>${e(t.downloadDraft)} ${icon('arrow')}</button><noscript><p>${e(t.needsJS)}</p></noscript><p class="form-status" role="status" aria-live="polite" data-form-status></p></form></div><aside class="side-note"><span class="eyebrow">${e(t.localTool)}</span><h2>${e(t.noContact)}</h2><p>${e(t.notClinical)}</p><a href="${route(l,'editorial',b)}" class="text-link">${e(t.editorial)} ${icon('arrow')}</a></aside></div>`;}
 else if(id==='saved'){body=`<div class="notice">${icon('bookmark')}<p>${e(message('saved.storage',l))}</p></div><div data-saved-list><p class="empty-state">${e(t.savedEmpty)}</p></div><button type="button" class="button secondary" data-clear-saved hidden>${e(t.clearSaved)}</button><noscript><p>${e(t.needsJS)}</p></noscript>`;}
 else if(id==='search'){body=`<form class="search-form page-search" data-search-form action="${route(l,'search',b)}" method="get">${icon('search')}<label class="sr-only" for="page-search">${e(t.searchLabel)}</label><input id="page-search" dir="auto" type="search" name="q" placeholder="${e(message('search.prompt',l))}" maxlength="160" autocomplete="off"><button class="button" type="submit">${e(t.search)}</button></form><p class="result-meta" data-search-status role="status" aria-live="polite">${e(t.searchStart)}</p><div class="search-results" data-search-results></div><noscript><p>${e(t.needsJS)}</p><div class="source-list">${resources.map(r=>resourceCard(r,l,b)).join('')}</div></noscript>`;}
 return shell(l,id,title,s.summary[l],pageIntro(l,title,s.summary[l],b)+`<div class="wide section page-content">${body}</div>`,b);
}
export function dossierPage(a,l,b){const t=labels[l];const bodytext=a.body[l].map(x=>x.text).join(' ');return shell(l,`dossier/${a.id}`,a.title[l],a.summary[l],`${pageIntro(l,a.title[l],a.summary[l],b,topics[a.topic][l])}<div class="wide article-meta"><span>${readingMinutes(bodytext,l)} ${e(t.readingTime)}</span><span>01.10.2026</span>${bookButton(a,l)}<button type="button" class="text-button" data-print>${e(t.print)}</button></div><div class="wide article-layout"><aside class="article-toc"><span class="eyebrow">${e(t.contents)}</span><nav>${a.body[l].map((x,i)=>`<a href="#part-${i+1}"><span>0${i+1}</span>${e(x.heading)}</a>`).join('')}<a href="#source-list">${e(t.references)}</a></nav><p>${e(t.notClinical)}</p></aside><article class="reading-body">${draftNotice(t)}${a.body[l].map((x,i)=>`<section id="part-${i+1}"><h2>${e(x.heading)}</h2><p>${e(x.text)}</p></section>`).join('')}<aside class="reading-limit"><span class="eyebrow">${e(t.limit)}</span><p>${e(a.limit[l])}</p></aside><section class="reflection-box"><span class="eyebrow">${e(t.readingPrompt)}</span><h2>${e(a.prompt[l])}</h2></section><section id="source-list"><h2>${e(t.references)}</h2><p class="muted">${e(t.verificationNote)}</p><ol class="references">${a.sources.map(sid=>{const s=sourceById[sid],r=resources.find(x=>x.sources.includes(sid));return `<li><p dir="ltr">${e(s.citation)}</p><a href="${resourceURL(l,r.id,b)}">${e(t.viewRecord)} ${icon('arrow')}</a></li>`;}).join('')}</ol></section></article></div><section class="wide section">${sectionHead(t.readings,t.related,'')}<div class="three-grid">${articles.filter(x=>x.id!==a.id).slice(0,3).map((x,i)=>dossierCard(x,l,b,i)).join('')}</div></section>`,b);}
export function resourcePage(r,l,b){const t=labels[l];const s=sourceById[r.sources[0]];const access=s.inspection==='official'?t.officialPage:s.inspection==='metadata'?t.metadataOnly:t.abstractOnly;const body=`${pageIntro(l,r.title[l],r.summary[l],b,typeName(s.kind,t))}<div class="wide resource-layout"><article class="resource-main">${s.bibliography?.cover?`<div class="resource-book-cover"><img src="${b}${s.bibliography.cover}" alt="" width="212" height="300"></div>`:''}<div class="original-publication"><span class="eyebrow">${e(t.references)}</span><h2 lang="${s.language|| (s.id==='s-eksi'?'tr':'en')}" dir="auto">${e(s.title)}</h2><p class="citation-text" dir="ltr" data-citation>${e(s.citation)}</p><div class="citation-actions"><button type="button" class="text-button" data-copy-citation>${icon('file')}${e(t.copyCitation)}</button><a href="${b}citations/${s.id}.ris" download>${e(t.exportRIS)}</a><a href="${b}citations/${s.id}.bib" download>${e(t.exportBib)}</a></div></div>${bibliographyDetail(s,l,b)}${evidenceRecordPanel(s,l)}${sourceReviewPanel(s,r,l,b)}<section class="prose"><h2>${e(t.sourceAccess)}</h2><p>${e(access)}</p>${sourceNotes[s.id]?`<p>${e(sourceNotes[s.id][l])}</p>`:''}<p class="muted">${e(t.sourceDate)}</p><h2>${e(t.limit)}</h2><p>${e(t.verificationNote)}</p><h2>${e(t.rights)}</h2><p>${e(t.rightsNote)}</p>${s.id==='s-fica'?`<div class="notice"><p>${e(r.summary[l])}</p></div>`:''}</section>${draftNotice(t)}</article><aside class="resource-aside"><span class="eyebrow">${e(t.verification)}</span><div class="source-status">${e(message('review.pending',l))}</div><code dir="ltr">${s.level} / ${s.status}</code><dl><dt>${e(t.sourceType)}</dt><dd>${e(typeName(s.kind,t))}</dd><dt>${e(t.checked)}</dt><dd><time dir="ltr" datetime="${s.checked}">${s.checked}</time></dd></dl>${ext(s.url,t.openSource,'button')}${compareButton(r.id,l,campusCopy[l])}<div class="aside-save">${bookButton(r,l)}</div><p>${e(t.noAffiliation)}</p></aside></div><section class="wide section">${sectionHead(t.readings,t.related,'')}<div class="three-grid">${articles.filter(a=>a.sources.includes(s.id)).map((a,i)=>dossierCard(a,l,b,i)).join('')||articles.slice(0,3).map((a,i)=>dossierCard(a,l,b,i)).join('')}</div></section>`;return shell(l,`resource/${r.id}`,r.title[l],r.summary[l],body,b);}
export function pathPage(p,l,b){const t=labels[l];return shell(l,`learning/${p.id}`,p.title[l],p.summary[l],pageIntro(l,p.title[l],p.summary[l],b,t[p.audience])+`<div class="wide section"><div class="notice">${icon('book')}<p>${e(t.noProgram)}</p></div><ol class="learning-steps">${p.articles.map((id,i)=>{const a=articles.find(x=>x.id===id);return `<li><span class="step-no">0${i+1}</span><div><span class="eyebrow">${e(topics[a.topic][l])}</span><h2><a href="${articleURL(l,id,b)}">${e(a.title[l])}</a></h2><p>${e(a.summary[l])}</p><div class="step-prompt">${e(a.prompt[l])}</div><a class="text-link" href="${articleURL(l,id,b)}">${e(t.readDossier)} ${icon('arrow')}</a></div></li>`;}).join('')}</ol></div>`,b);}
export function searchIndex(l,b){
 const indexed=(record,rawText)=>({...record,rawText,text:normalizeText(rawText,l)});
 return [
  ...sections.map(s=>indexed({id:'section-'+s.id,originalTitle:measureProfiles.find(p=>'measure-'+p.id===s.id)?.title||'',title:s.id==='practice'?labels[l].practicePage:s.id==='search'?labels[l].searchPage:s.title[l],summary:s.summary[l],kind:labels[l].topics,url:route(l,s.id,b),identifiers:[]},(measureProfiles.find(p=>'measure-'+p.id===s.id)?.title||'')+' '+s.title[l]+' '+s.summary[l]+' '+(s.id==='evidence'?scholarlyThemes.map(t=>t.title[l]+' '+t.text[l]).join(' '):s.id==='about'?sc('founderText',l):s.id==='measure-rss-14'?sc('rssNote',l):s.id.startsWith('measure-')?JSON.stringify(evidence.find(r=>r.id===s.id.slice(8))?.editions[l]||{}):'')+' '+(researchGuides.find(g=>g.id===s.id)?.blocks.map(x=>x.heading[l]+' '+x.text[l]).join(' ')||''))),
  ...articles.map(a=>indexed({id:a.id,title:a.title[l],summary:a.summary[l],kind:labels[l].dossiers,url:articleURL(l,a.id,b),identifiers:[]},a.title[l]+' '+a.summary[l]+' '+a.body[l].map(x=>x.heading+' '+x.text).join(' '))),
  ...resources.map(r=>{const source=sourceById[r.sources[0]];return indexed({id:r.id,title:r.title[l],originalTitle:source.title,summary:r.summary[l],kind:typeName(r.kind,labels[l]),url:resourceURL(l,r.id,b),identifiers:identifiersFor(source)},r.title[l]+' '+r.summary[l]+' '+(evidence.find(x=>x.id===r.id)?.editions[l].population||'')+' '+source.title+' '+source.citation);})
 ];
}
